// Code generated by grpc-gen. DO NOT EDIT.
// gRPC client wrapper for the audit service (with cache layer).

package client

import (
	"context"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"

	pb "github.com/thaily/lms/proto/audit"
	"github.com/thaily/lms/src/server/graph/cache"
)

type AuditClient struct {
	conn  *grpc.ClientConn
	stub  pb.AuditServiceClient
	cache cache.Cache
	ttl   time.Duration
}

func NewAuditClient(addr string, ca cache.Cache, ttl time.Duration, opts ...grpc.DialOption) (*AuditClient, error) {
	conn, err := grpc.NewClient(addr, opts...)
	if err != nil { return nil, err }
	return &AuditClient{conn: conn, stub: pb.NewAuditServiceClient(conn), cache: ca, ttl: ttl}, nil
}

func (c *AuditClient) Close() error { return c.conn.Close() }
func (c *AuditClient) Stub() pb.AuditServiceClient { return c.stub }

func (c *AuditClient) CreateAuditLog(ctx context.Context, in *pb.CreateAuditLogRequest, opts ...grpc.CallOption) (*pb.CreateAuditLogResponse, error) {
	resp, err := c.stub.CreateAuditLog(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:AuditLog:v:*")
	}
	return resp, err
}

func (c *AuditClient) UpdateAuditLog(ctx context.Context, in *pb.UpdateAuditLogRequest, opts ...grpc.CallOption) (*pb.UpdateAuditLogResponse, error) {
	resp, err := c.stub.UpdateAuditLog(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:AuditLog:v:*")
	}
	return resp, err
}

func (c *AuditClient) DeleteAuditLog(ctx context.Context, in *pb.DeleteAuditLogRequest, opts ...grpc.CallOption) (*pb.DeleteAuditLogResponse, error) {
	resp, err := c.stub.DeleteAuditLog(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:AuditLog:v:*")
	}
	return resp, err
}

func (c *AuditClient) ListAuditLog(ctx context.Context, in *pb.ListAuditLogRequest, opts ...grpc.CallOption) (*pb.ListAuditLogResponse, error) {
	if c.cache == nil { return c.stub.ListAuditLog(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListAuditLog(ctx, in, opts...) }
	key := cache.ListKey("AuditLog", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListAuditLogResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListAuditLog(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

