// Code generated by grpc-gen. DO NOT EDIT.
// Shared helpers used by every per-service cache wrap.

package client

import (
	"context"

	"github.com/thaily/lms/src/server/graph/auth"
)

// viewerID returns the request's user id, or cache.ViewerAnon for
// anonymous traffic. Lives here so the per-service files don't have to
// import auth themselves.
func viewerID(ctx context.Context) string {
	v := auth.FromContext(ctx)
	if v == nil { return "" }
	return v.UserID
}
