// Code generated by grpc-gen. DO NOT EDIT.
// gRPC client wrapper for the class service (with cache layer).

package client

import (
	"context"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"

	pb "github.com/thaily/lms/proto/class"
	"github.com/thaily/lms/src/server/graph/cache"
)

type ClassClient struct {
	conn  *grpc.ClientConn
	stub  pb.ClassServiceClient
	cache cache.Cache
	ttl   time.Duration
}

func NewClassClient(addr string, ca cache.Cache, ttl time.Duration, opts ...grpc.DialOption) (*ClassClient, error) {
	conn, err := grpc.NewClient(addr, opts...)
	if err != nil { return nil, err }
	return &ClassClient{conn: conn, stub: pb.NewClassServiceClient(conn), cache: ca, ttl: ttl}, nil
}

func (c *ClassClient) Close() error { return c.conn.Close() }
func (c *ClassClient) Stub() pb.ClassServiceClient { return c.stub }

func (c *ClassClient) CreateClass(ctx context.Context, in *pb.CreateClassRequest, opts ...grpc.CallOption) (*pb.CreateClassResponse, error) {
	resp, err := c.stub.CreateClass(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Class:v:*")
	}
	return resp, err
}

func (c *ClassClient) UpdateClass(ctx context.Context, in *pb.UpdateClassRequest, opts ...grpc.CallOption) (*pb.UpdateClassResponse, error) {
	resp, err := c.stub.UpdateClass(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Class:v:*")
	}
	return resp, err
}

func (c *ClassClient) DeleteClass(ctx context.Context, in *pb.DeleteClassRequest, opts ...grpc.CallOption) (*pb.DeleteClassResponse, error) {
	resp, err := c.stub.DeleteClass(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Class:v:*")
	}
	return resp, err
}

func (c *ClassClient) ListClass(ctx context.Context, in *pb.ListClassRequest, opts ...grpc.CallOption) (*pb.ListClassResponse, error) {
	if c.cache == nil { return c.stub.ListClass(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListClass(ctx, in, opts...) }
	key := cache.ListKey("Class", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListClassResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListClass(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *ClassClient) CreateClassInviteKey(ctx context.Context, in *pb.CreateClassInviteKeyRequest, opts ...grpc.CallOption) (*pb.CreateClassInviteKeyResponse, error) {
	resp, err := c.stub.CreateClassInviteKey(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ClassInviteKey:v:*")
	}
	return resp, err
}

func (c *ClassClient) UpdateClassInviteKey(ctx context.Context, in *pb.UpdateClassInviteKeyRequest, opts ...grpc.CallOption) (*pb.UpdateClassInviteKeyResponse, error) {
	resp, err := c.stub.UpdateClassInviteKey(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ClassInviteKey:v:*")
	}
	return resp, err
}

func (c *ClassClient) DeleteClassInviteKey(ctx context.Context, in *pb.DeleteClassInviteKeyRequest, opts ...grpc.CallOption) (*pb.DeleteClassInviteKeyResponse, error) {
	resp, err := c.stub.DeleteClassInviteKey(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ClassInviteKey:v:*")
	}
	return resp, err
}

func (c *ClassClient) ListClassInviteKey(ctx context.Context, in *pb.ListClassInviteKeyRequest, opts ...grpc.CallOption) (*pb.ListClassInviteKeyResponse, error) {
	if c.cache == nil { return c.stub.ListClassInviteKey(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListClassInviteKey(ctx, in, opts...) }
	key := cache.ListKey("ClassInviteKey", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListClassInviteKeyResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListClassInviteKey(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *ClassClient) CreateEnrollment(ctx context.Context, in *pb.CreateEnrollmentRequest, opts ...grpc.CallOption) (*pb.CreateEnrollmentResponse, error) {
	resp, err := c.stub.CreateEnrollment(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Enrollment:v:*")
	}
	return resp, err
}

func (c *ClassClient) UpdateEnrollment(ctx context.Context, in *pb.UpdateEnrollmentRequest, opts ...grpc.CallOption) (*pb.UpdateEnrollmentResponse, error) {
	resp, err := c.stub.UpdateEnrollment(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Enrollment:v:*")
	}
	return resp, err
}

func (c *ClassClient) DeleteEnrollment(ctx context.Context, in *pb.DeleteEnrollmentRequest, opts ...grpc.CallOption) (*pb.DeleteEnrollmentResponse, error) {
	resp, err := c.stub.DeleteEnrollment(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Enrollment:v:*")
	}
	return resp, err
}

func (c *ClassClient) ListEnrollment(ctx context.Context, in *pb.ListEnrollmentRequest, opts ...grpc.CallOption) (*pb.ListEnrollmentResponse, error) {
	if c.cache == nil { return c.stub.ListEnrollment(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListEnrollment(ctx, in, opts...) }
	key := cache.ListKey("Enrollment", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListEnrollmentResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListEnrollment(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

