// Code generated by grpc-gen. DO NOT EDIT.
// Aggregates per-service clients + their shared cache backend.

package client

import (
	"fmt"
	"time"

	"google.golang.org/grpc"

	"github.com/thaily/lms/src/server/graph/cache"
)

// Endpoints lists the dial address of each gRPC service.
type Endpoints struct {
	Audit string
	Class string
	Exam string
	Lesson string
	Material string
	Notification string
	Submission string
	User string
}

type Clients struct {
	Cache cache.Cache
	TTL   time.Duration
	Audit *AuditClient
	Class *ClassClient
	Exam *ExamClient
	Lesson *LessonClient
	Material *MaterialClient
	Notification *NotificationClient
	Submission *SubmissionClient
	User *UserClient
}

// NewClients dials every service and shares the same Cache + TTL across
// them. Pass cache.Noop{} (or any zero ttl) to disable caching.
func NewClients(ep Endpoints, ca cache.Cache, ttl time.Duration, opts ...grpc.DialOption) (*Clients, error) {
	if ca == nil { ca = cache.Noop{} }
	c := &Clients{Cache: ca, TTL: ttl}
	var err error

	if c.Audit, err = NewAuditClient(ep.Audit, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial audit: %w", err)
	}
	if c.Class, err = NewClassClient(ep.Class, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial class: %w", err)
	}
	if c.Exam, err = NewExamClient(ep.Exam, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial exam: %w", err)
	}
	if c.Lesson, err = NewLessonClient(ep.Lesson, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial lesson: %w", err)
	}
	if c.Material, err = NewMaterialClient(ep.Material, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial material: %w", err)
	}
	if c.Notification, err = NewNotificationClient(ep.Notification, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial notification: %w", err)
	}
	if c.Submission, err = NewSubmissionClient(ep.Submission, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial submission: %w", err)
	}
	if c.User, err = NewUserClient(ep.User, ca, ttl, opts...); err != nil {
		c.Close()
		return nil, fmt.Errorf("dial user: %w", err)
	}
	return c, nil
}

func (c *Clients) Close() error {
	var firstErr error
	if c.Audit != nil {
		if err := c.Audit.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	if c.Class != nil {
		if err := c.Class.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	if c.Exam != nil {
		if err := c.Exam.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	if c.Lesson != nil {
		if err := c.Lesson.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	if c.Material != nil {
		if err := c.Material.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	if c.Notification != nil {
		if err := c.Notification.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	if c.Submission != nil {
		if err := c.Submission.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	if c.User != nil {
		if err := c.User.Close(); err != nil && firstErr == nil { firstErr = err }
	}
	return firstErr
}
