// Code generated by grpc-gen. DO NOT EDIT.
// gRPC client wrapper for the exam service (with cache layer).

package client

import (
	"context"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"

	pb "github.com/thaily/lms/proto/exam"
	"github.com/thaily/lms/src/server/graph/cache"
)

type ExamClient struct {
	conn  *grpc.ClientConn
	stub  pb.ExamServiceClient
	cache cache.Cache
	ttl   time.Duration
}

func NewExamClient(addr string, ca cache.Cache, ttl time.Duration, opts ...grpc.DialOption) (*ExamClient, error) {
	conn, err := grpc.NewClient(addr, opts...)
	if err != nil { return nil, err }
	return &ExamClient{conn: conn, stub: pb.NewExamServiceClient(conn), cache: ca, ttl: ttl}, nil
}

func (c *ExamClient) Close() error { return c.conn.Close() }
func (c *ExamClient) Stub() pb.ExamServiceClient { return c.stub }

func (c *ExamClient) CreateExam(ctx context.Context, in *pb.CreateExamRequest, opts ...grpc.CallOption) (*pb.CreateExamResponse, error) {
	resp, err := c.stub.CreateExam(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Exam:v:*")
	}
	return resp, err
}

func (c *ExamClient) UpdateExam(ctx context.Context, in *pb.UpdateExamRequest, opts ...grpc.CallOption) (*pb.UpdateExamResponse, error) {
	resp, err := c.stub.UpdateExam(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Exam:v:*")
	}
	return resp, err
}

func (c *ExamClient) DeleteExam(ctx context.Context, in *pb.DeleteExamRequest, opts ...grpc.CallOption) (*pb.DeleteExamResponse, error) {
	resp, err := c.stub.DeleteExam(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Exam:v:*")
	}
	return resp, err
}

func (c *ExamClient) ListExam(ctx context.Context, in *pb.ListExamRequest, opts ...grpc.CallOption) (*pb.ListExamResponse, error) {
	if c.cache == nil { return c.stub.ListExam(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListExam(ctx, in, opts...) }
	key := cache.ListKey("Exam", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListExamResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListExam(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *ExamClient) CreateExamAssignment(ctx context.Context, in *pb.CreateExamAssignmentRequest, opts ...grpc.CallOption) (*pb.CreateExamAssignmentResponse, error) {
	resp, err := c.stub.CreateExamAssignment(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ExamAssignment:v:*")
	}
	return resp, err
}

func (c *ExamClient) UpdateExamAssignment(ctx context.Context, in *pb.UpdateExamAssignmentRequest, opts ...grpc.CallOption) (*pb.UpdateExamAssignmentResponse, error) {
	resp, err := c.stub.UpdateExamAssignment(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ExamAssignment:v:*")
	}
	return resp, err
}

func (c *ExamClient) DeleteExamAssignment(ctx context.Context, in *pb.DeleteExamAssignmentRequest, opts ...grpc.CallOption) (*pb.DeleteExamAssignmentResponse, error) {
	resp, err := c.stub.DeleteExamAssignment(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ExamAssignment:v:*")
	}
	return resp, err
}

func (c *ExamClient) ListExamAssignment(ctx context.Context, in *pb.ListExamAssignmentRequest, opts ...grpc.CallOption) (*pb.ListExamAssignmentResponse, error) {
	if c.cache == nil { return c.stub.ListExamAssignment(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListExamAssignment(ctx, in, opts...) }
	key := cache.ListKey("ExamAssignment", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListExamAssignmentResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListExamAssignment(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *ExamClient) CreateQuestion(ctx context.Context, in *pb.CreateQuestionRequest, opts ...grpc.CallOption) (*pb.CreateQuestionResponse, error) {
	resp, err := c.stub.CreateQuestion(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Question:v:*")
	}
	return resp, err
}

func (c *ExamClient) UpdateQuestion(ctx context.Context, in *pb.UpdateQuestionRequest, opts ...grpc.CallOption) (*pb.UpdateQuestionResponse, error) {
	resp, err := c.stub.UpdateQuestion(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Question:v:*")
	}
	return resp, err
}

func (c *ExamClient) DeleteQuestion(ctx context.Context, in *pb.DeleteQuestionRequest, opts ...grpc.CallOption) (*pb.DeleteQuestionResponse, error) {
	resp, err := c.stub.DeleteQuestion(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Question:v:*")
	}
	return resp, err
}

func (c *ExamClient) ListQuestion(ctx context.Context, in *pb.ListQuestionRequest, opts ...grpc.CallOption) (*pb.ListQuestionResponse, error) {
	if c.cache == nil { return c.stub.ListQuestion(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListQuestion(ctx, in, opts...) }
	key := cache.ListKey("Question", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListQuestionResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListQuestion(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *ExamClient) CreateQuestionChoice(ctx context.Context, in *pb.CreateQuestionChoiceRequest, opts ...grpc.CallOption) (*pb.CreateQuestionChoiceResponse, error) {
	resp, err := c.stub.CreateQuestionChoice(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:QuestionChoice:v:*")
	}
	return resp, err
}

func (c *ExamClient) UpdateQuestionChoice(ctx context.Context, in *pb.UpdateQuestionChoiceRequest, opts ...grpc.CallOption) (*pb.UpdateQuestionChoiceResponse, error) {
	resp, err := c.stub.UpdateQuestionChoice(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:QuestionChoice:v:*")
	}
	return resp, err
}

func (c *ExamClient) DeleteQuestionChoice(ctx context.Context, in *pb.DeleteQuestionChoiceRequest, opts ...grpc.CallOption) (*pb.DeleteQuestionChoiceResponse, error) {
	resp, err := c.stub.DeleteQuestionChoice(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:QuestionChoice:v:*")
	}
	return resp, err
}

func (c *ExamClient) ListQuestionChoice(ctx context.Context, in *pb.ListQuestionChoiceRequest, opts ...grpc.CallOption) (*pb.ListQuestionChoiceResponse, error) {
	if c.cache == nil { return c.stub.ListQuestionChoice(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListQuestionChoice(ctx, in, opts...) }
	key := cache.ListKey("QuestionChoice", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListQuestionChoiceResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListQuestionChoice(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *ExamClient) CreateQuestionAnswer(ctx context.Context, in *pb.CreateQuestionAnswerRequest, opts ...grpc.CallOption) (*pb.CreateQuestionAnswerResponse, error) {
	resp, err := c.stub.CreateQuestionAnswer(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:QuestionAnswer:v:*")
	}
	return resp, err
}

func (c *ExamClient) UpdateQuestionAnswer(ctx context.Context, in *pb.UpdateQuestionAnswerRequest, opts ...grpc.CallOption) (*pb.UpdateQuestionAnswerResponse, error) {
	resp, err := c.stub.UpdateQuestionAnswer(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:QuestionAnswer:v:*")
	}
	return resp, err
}

func (c *ExamClient) DeleteQuestionAnswer(ctx context.Context, in *pb.DeleteQuestionAnswerRequest, opts ...grpc.CallOption) (*pb.DeleteQuestionAnswerResponse, error) {
	resp, err := c.stub.DeleteQuestionAnswer(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:QuestionAnswer:v:*")
	}
	return resp, err
}

func (c *ExamClient) ListQuestionAnswer(ctx context.Context, in *pb.ListQuestionAnswerRequest, opts ...grpc.CallOption) (*pb.ListQuestionAnswerResponse, error) {
	if c.cache == nil { return c.stub.ListQuestionAnswer(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListQuestionAnswer(ctx, in, opts...) }
	key := cache.ListKey("QuestionAnswer", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListQuestionAnswerResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListQuestionAnswer(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

