// Code generated by grpc-gen. DO NOT EDIT.
// gRPC client wrapper for the notification service (with cache layer).

package client

import (
	"context"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"

	pb "github.com/thaily/lms/proto/notification"
	"github.com/thaily/lms/src/server/graph/cache"
)

type NotificationClient struct {
	conn  *grpc.ClientConn
	stub  pb.NotificationServiceClient
	cache cache.Cache
	ttl   time.Duration
}

func NewNotificationClient(addr string, ca cache.Cache, ttl time.Duration, opts ...grpc.DialOption) (*NotificationClient, error) {
	conn, err := grpc.NewClient(addr, opts...)
	if err != nil { return nil, err }
	return &NotificationClient{conn: conn, stub: pb.NewNotificationServiceClient(conn), cache: ca, ttl: ttl}, nil
}

func (c *NotificationClient) Close() error { return c.conn.Close() }
func (c *NotificationClient) Stub() pb.NotificationServiceClient { return c.stub }

func (c *NotificationClient) CreateNotification(ctx context.Context, in *pb.CreateNotificationRequest, opts ...grpc.CallOption) (*pb.CreateNotificationResponse, error) {
	resp, err := c.stub.CreateNotification(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Notification:v:*")
	}
	return resp, err
}

func (c *NotificationClient) UpdateNotification(ctx context.Context, in *pb.UpdateNotificationRequest, opts ...grpc.CallOption) (*pb.UpdateNotificationResponse, error) {
	resp, err := c.stub.UpdateNotification(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Notification:v:*")
	}
	return resp, err
}

func (c *NotificationClient) DeleteNotification(ctx context.Context, in *pb.DeleteNotificationRequest, opts ...grpc.CallOption) (*pb.DeleteNotificationResponse, error) {
	resp, err := c.stub.DeleteNotification(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:Notification:v:*")
	}
	return resp, err
}

func (c *NotificationClient) ListNotification(ctx context.Context, in *pb.ListNotificationRequest, opts ...grpc.CallOption) (*pb.ListNotificationResponse, error) {
	if c.cache == nil { return c.stub.ListNotification(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListNotification(ctx, in, opts...) }
	key := cache.ListKey("Notification", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListNotificationResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListNotification(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *NotificationClient) CreateCommunityReport(ctx context.Context, in *pb.CreateCommunityReportRequest, opts ...grpc.CallOption) (*pb.CreateCommunityReportResponse, error) {
	resp, err := c.stub.CreateCommunityReport(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:CommunityReport:v:*")
	}
	return resp, err
}

func (c *NotificationClient) UpdateCommunityReport(ctx context.Context, in *pb.UpdateCommunityReportRequest, opts ...grpc.CallOption) (*pb.UpdateCommunityReportResponse, error) {
	resp, err := c.stub.UpdateCommunityReport(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:CommunityReport:v:*")
	}
	return resp, err
}

func (c *NotificationClient) DeleteCommunityReport(ctx context.Context, in *pb.DeleteCommunityReportRequest, opts ...grpc.CallOption) (*pb.DeleteCommunityReportResponse, error) {
	resp, err := c.stub.DeleteCommunityReport(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:CommunityReport:v:*")
	}
	return resp, err
}

func (c *NotificationClient) ListCommunityReport(ctx context.Context, in *pb.ListCommunityReportRequest, opts ...grpc.CallOption) (*pb.ListCommunityReportResponse, error) {
	if c.cache == nil { return c.stub.ListCommunityReport(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListCommunityReport(ctx, in, opts...) }
	key := cache.ListKey("CommunityReport", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListCommunityReportResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListCommunityReport(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

