// Code generated by grpc-gen. DO NOT EDIT.
// gRPC client wrapper for the submission service (with cache layer).

package client

import (
	"context"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"

	pb "github.com/thaily/lms/proto/submission"
	"github.com/thaily/lms/src/server/graph/cache"
)

type SubmissionClient struct {
	conn  *grpc.ClientConn
	stub  pb.SubmissionServiceClient
	cache cache.Cache
	ttl   time.Duration
}

func NewSubmissionClient(addr string, ca cache.Cache, ttl time.Duration, opts ...grpc.DialOption) (*SubmissionClient, error) {
	conn, err := grpc.NewClient(addr, opts...)
	if err != nil { return nil, err }
	return &SubmissionClient{conn: conn, stub: pb.NewSubmissionServiceClient(conn), cache: ca, ttl: ttl}, nil
}

func (c *SubmissionClient) Close() error { return c.conn.Close() }
func (c *SubmissionClient) Stub() pb.SubmissionServiceClient { return c.stub }

func (c *SubmissionClient) CreateExamAttempt(ctx context.Context, in *pb.CreateExamAttemptRequest, opts ...grpc.CallOption) (*pb.CreateExamAttemptResponse, error) {
	resp, err := c.stub.CreateExamAttempt(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ExamAttempt:v:*")
	}
	return resp, err
}

func (c *SubmissionClient) UpdateExamAttempt(ctx context.Context, in *pb.UpdateExamAttemptRequest, opts ...grpc.CallOption) (*pb.UpdateExamAttemptResponse, error) {
	resp, err := c.stub.UpdateExamAttempt(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ExamAttempt:v:*")
	}
	return resp, err
}

func (c *SubmissionClient) DeleteExamAttempt(ctx context.Context, in *pb.DeleteExamAttemptRequest, opts ...grpc.CallOption) (*pb.DeleteExamAttemptResponse, error) {
	resp, err := c.stub.DeleteExamAttempt(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:ExamAttempt:v:*")
	}
	return resp, err
}

func (c *SubmissionClient) ListExamAttempt(ctx context.Context, in *pb.ListExamAttemptRequest, opts ...grpc.CallOption) (*pb.ListExamAttemptResponse, error) {
	if c.cache == nil { return c.stub.ListExamAttempt(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListExamAttempt(ctx, in, opts...) }
	key := cache.ListKey("ExamAttempt", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListExamAttemptResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListExamAttempt(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *SubmissionClient) CreateAttemptAnswer(ctx context.Context, in *pb.CreateAttemptAnswerRequest, opts ...grpc.CallOption) (*pb.CreateAttemptAnswerResponse, error) {
	resp, err := c.stub.CreateAttemptAnswer(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:AttemptAnswer:v:*")
	}
	return resp, err
}

func (c *SubmissionClient) UpdateAttemptAnswer(ctx context.Context, in *pb.UpdateAttemptAnswerRequest, opts ...grpc.CallOption) (*pb.UpdateAttemptAnswerResponse, error) {
	resp, err := c.stub.UpdateAttemptAnswer(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:AttemptAnswer:v:*")
	}
	return resp, err
}

func (c *SubmissionClient) DeleteAttemptAnswer(ctx context.Context, in *pb.DeleteAttemptAnswerRequest, opts ...grpc.CallOption) (*pb.DeleteAttemptAnswerResponse, error) {
	resp, err := c.stub.DeleteAttemptAnswer(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:AttemptAnswer:v:*")
	}
	return resp, err
}

func (c *SubmissionClient) ListAttemptAnswer(ctx context.Context, in *pb.ListAttemptAnswerRequest, opts ...grpc.CallOption) (*pb.ListAttemptAnswerResponse, error) {
	if c.cache == nil { return c.stub.ListAttemptAnswer(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListAttemptAnswer(ctx, in, opts...) }
	key := cache.ListKey("AttemptAnswer", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListAttemptAnswerResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListAttemptAnswer(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

