// Code generated by grpc-gen. DO NOT EDIT.
// gRPC client wrapper for the user service (with cache layer).

package client

import (
	"context"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"

	pb "github.com/thaily/lms/proto/user"
	"github.com/thaily/lms/src/server/graph/cache"
)

type UserClient struct {
	conn  *grpc.ClientConn
	stub  pb.UserServiceClient
	cache cache.Cache
	ttl   time.Duration
}

func NewUserClient(addr string, ca cache.Cache, ttl time.Duration, opts ...grpc.DialOption) (*UserClient, error) {
	conn, err := grpc.NewClient(addr, opts...)
	if err != nil { return nil, err }
	return &UserClient{conn: conn, stub: pb.NewUserServiceClient(conn), cache: ca, ttl: ttl}, nil
}

func (c *UserClient) Close() error { return c.conn.Close() }
func (c *UserClient) Stub() pb.UserServiceClient { return c.stub }

func (c *UserClient) CreateUser(ctx context.Context, in *pb.CreateUserRequest, opts ...grpc.CallOption) (*pb.CreateUserResponse, error) {
	resp, err := c.stub.CreateUser(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:User:v:*")
	}
	return resp, err
}

func (c *UserClient) UpdateUser(ctx context.Context, in *pb.UpdateUserRequest, opts ...grpc.CallOption) (*pb.UpdateUserResponse, error) {
	resp, err := c.stub.UpdateUser(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:User:v:*")
	}
	return resp, err
}

func (c *UserClient) DeleteUser(ctx context.Context, in *pb.DeleteUserRequest, opts ...grpc.CallOption) (*pb.DeleteUserResponse, error) {
	resp, err := c.stub.DeleteUser(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:User:v:*")
	}
	return resp, err
}

func (c *UserClient) ListUser(ctx context.Context, in *pb.ListUserRequest, opts ...grpc.CallOption) (*pb.ListUserResponse, error) {
	if c.cache == nil { return c.stub.ListUser(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListUser(ctx, in, opts...) }
	key := cache.ListKey("User", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListUserResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListUser(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *UserClient) CreateTeacherProfile(ctx context.Context, in *pb.CreateTeacherProfileRequest, opts ...grpc.CallOption) (*pb.CreateTeacherProfileResponse, error) {
	resp, err := c.stub.CreateTeacherProfile(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:TeacherProfile:v:*")
	}
	return resp, err
}

func (c *UserClient) UpdateTeacherProfile(ctx context.Context, in *pb.UpdateTeacherProfileRequest, opts ...grpc.CallOption) (*pb.UpdateTeacherProfileResponse, error) {
	resp, err := c.stub.UpdateTeacherProfile(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:TeacherProfile:v:*")
	}
	return resp, err
}

func (c *UserClient) DeleteTeacherProfile(ctx context.Context, in *pb.DeleteTeacherProfileRequest, opts ...grpc.CallOption) (*pb.DeleteTeacherProfileResponse, error) {
	resp, err := c.stub.DeleteTeacherProfile(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:TeacherProfile:v:*")
	}
	return resp, err
}

func (c *UserClient) ListTeacherProfile(ctx context.Context, in *pb.ListTeacherProfileRequest, opts ...grpc.CallOption) (*pb.ListTeacherProfileResponse, error) {
	if c.cache == nil { return c.stub.ListTeacherProfile(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListTeacherProfile(ctx, in, opts...) }
	key := cache.ListKey("TeacherProfile", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListTeacherProfileResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListTeacherProfile(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *UserClient) CreateStudentProfile(ctx context.Context, in *pb.CreateStudentProfileRequest, opts ...grpc.CallOption) (*pb.CreateStudentProfileResponse, error) {
	resp, err := c.stub.CreateStudentProfile(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:StudentProfile:v:*")
	}
	return resp, err
}

func (c *UserClient) UpdateStudentProfile(ctx context.Context, in *pb.UpdateStudentProfileRequest, opts ...grpc.CallOption) (*pb.UpdateStudentProfileResponse, error) {
	resp, err := c.stub.UpdateStudentProfile(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:StudentProfile:v:*")
	}
	return resp, err
}

func (c *UserClient) DeleteStudentProfile(ctx context.Context, in *pb.DeleteStudentProfileRequest, opts ...grpc.CallOption) (*pb.DeleteStudentProfileResponse, error) {
	resp, err := c.stub.DeleteStudentProfile(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:StudentProfile:v:*")
	}
	return resp, err
}

func (c *UserClient) ListStudentProfile(ctx context.Context, in *pb.ListStudentProfileRequest, opts ...grpc.CallOption) (*pb.ListStudentProfileResponse, error) {
	if c.cache == nil { return c.stub.ListStudentProfile(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListStudentProfile(ctx, in, opts...) }
	key := cache.ListKey("StudentProfile", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListStudentProfileResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListStudentProfile(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *UserClient) CreateRefreshToken(ctx context.Context, in *pb.CreateRefreshTokenRequest, opts ...grpc.CallOption) (*pb.CreateRefreshTokenResponse, error) {
	resp, err := c.stub.CreateRefreshToken(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:RefreshToken:v:*")
	}
	return resp, err
}

func (c *UserClient) UpdateRefreshToken(ctx context.Context, in *pb.UpdateRefreshTokenRequest, opts ...grpc.CallOption) (*pb.UpdateRefreshTokenResponse, error) {
	resp, err := c.stub.UpdateRefreshToken(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:RefreshToken:v:*")
	}
	return resp, err
}

func (c *UserClient) DeleteRefreshToken(ctx context.Context, in *pb.DeleteRefreshTokenRequest, opts ...grpc.CallOption) (*pb.DeleteRefreshTokenResponse, error) {
	resp, err := c.stub.DeleteRefreshToken(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:RefreshToken:v:*")
	}
	return resp, err
}

func (c *UserClient) ListRefreshToken(ctx context.Context, in *pb.ListRefreshTokenRequest, opts ...grpc.CallOption) (*pb.ListRefreshTokenResponse, error) {
	if c.cache == nil { return c.stub.ListRefreshToken(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListRefreshToken(ctx, in, opts...) }
	key := cache.ListKey("RefreshToken", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListRefreshTokenResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListRefreshToken(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

func (c *UserClient) CreatePasswordReset(ctx context.Context, in *pb.CreatePasswordResetRequest, opts ...grpc.CallOption) (*pb.CreatePasswordResetResponse, error) {
	resp, err := c.stub.CreatePasswordReset(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:PasswordReset:v:*")
	}
	return resp, err
}

func (c *UserClient) UpdatePasswordReset(ctx context.Context, in *pb.UpdatePasswordResetRequest, opts ...grpc.CallOption) (*pb.UpdatePasswordResetResponse, error) {
	resp, err := c.stub.UpdatePasswordReset(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:PasswordReset:v:*")
	}
	return resp, err
}

func (c *UserClient) DeletePasswordReset(ctx context.Context, in *pb.DeletePasswordResetRequest, opts ...grpc.CallOption) (*pb.DeletePasswordResetResponse, error) {
	resp, err := c.stub.DeletePasswordReset(ctx, in, opts...)
	if err == nil && c.cache != nil {
		_ = c.cache.DelByPattern(ctx, "e:PasswordReset:v:*")
	}
	return resp, err
}

func (c *UserClient) ListPasswordReset(ctx context.Context, in *pb.ListPasswordResetRequest, opts ...grpc.CallOption) (*pb.ListPasswordResetResponse, error) {
	if c.cache == nil { return c.stub.ListPasswordReset(ctx, in, opts...) }
	reqBytes, mErr := proto.MarshalOptions{Deterministic: true}.Marshal(in)
	if mErr != nil { return c.stub.ListPasswordReset(ctx, in, opts...) }
	key := cache.ListKey("PasswordReset", viewerID(ctx), cache.HashBytes(reqBytes))
	if b, ok, _ := c.cache.Get(ctx, key); ok {
		var cached pb.ListPasswordResetResponse
		if proto.Unmarshal(b, &cached) == nil { return &cached, nil }
	}
	resp, err := c.stub.ListPasswordReset(ctx, in, opts...)
	if err != nil { return nil, err }
	if b, mErr := proto.Marshal(resp); mErr == nil { _ = c.cache.Set(ctx, key, b, c.ttl) }
	return resp, nil
}

