version: '3.8'

services:
  notification:
    build:
      context: ../../..
      dockerfile: src/service/notification/Dockerfile
    image: github.com/thaily/lms/notification:latest
    container_name: notification_service
    env_file:
      - notification.env
    ports:
      - "50057:50057"
    volumes:
      - .:/app/service:ro
      - ../../../logs:/app/logs
    networks:
      - notification_network
    restart: unless-stopped

networks:
  notification_network:
    driver: bridge
