package gateway

import (
	"os"
	"path/filepath"
	"strings"
)

// CacheGenInput drives gen of graph/cache/*.
type CacheGenInput struct {
	ServerDir  string
	ModulePath string
}

// GenerateCache writes the cache package: a Cache interface, a Redis impl,
// a Noop impl, and key builders for entity / list keys with per-viewer scope.
func GenerateCache(in CacheGenInput) error {
	dir := filepath.Join(in.ServerDir, "graph", "cache")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	files := map[string]string{
		"cache.go": cacheCore,
		"redis.go": redisImpl,
		"noop.go":  noopImpl,
		"keys.go":  keysHelpers,
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(strings.TrimLeft(body, "\n")), 0644); err != nil {
			return err
		}
	}
	return nil
}

const cacheCore = `
// Code generated by grpc-gen. DO NOT EDIT.
// Two-layer cache shared by graph/client (gRPC response cache) and
// graph/dataloader (per-id cache). Scope is per-viewer; invalidation is
// pattern-based on mutation. See keys.go for the key layout.

package cache

import (
	"context"
	"time"
)

// Cache is the minimal interface the gateway uses. Implementations must be
// safe for concurrent use. Get returns (nil, false, nil) on a clean miss.
type Cache interface {
	Get(ctx context.Context, key string) ([]byte, bool, error)
	Set(ctx context.Context, key string, val []byte, ttl time.Duration) error
	Del(ctx context.Context, keys ...string) error
	// DelByPattern removes every key matching the glob pattern (Redis SCAN
	// semantics). Used by mutation invalidation to wipe all viewers' entries
	// for an affected entity.
	DelByPattern(ctx context.Context, pattern string) error
}
`

const redisImpl = `
// Code generated by grpc-gen. DO NOT EDIT.

package cache

import (
	"context"
	"errors"
	"time"

	"github.com/redis/go-redis/v9"
)

// RedisCache implements Cache against a single go-redis client. SCAN is
// used for pattern delete to avoid the production-killer that is KEYS.
type RedisCache struct {
	rdb *redis.Client
}

// NewRedis dials Redis at addr (e.g. "localhost:6379") with the given
// password (empty for none) and selects the given DB number.
func NewRedis(addr, password string, db int) (*RedisCache, error) {
	rdb := redis.NewClient(&redis.Options{Addr: addr, Password: password, DB: db})
	if err := rdb.Ping(context.Background()).Err(); err != nil {
		return nil, err
	}
	return &RedisCache{rdb: rdb}, nil
}

func (r *RedisCache) Get(ctx context.Context, key string) ([]byte, bool, error) {
	b, err := r.rdb.Get(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return b, true, nil
}

func (r *RedisCache) Set(ctx context.Context, key string, val []byte, ttl time.Duration) error {
	return r.rdb.Set(ctx, key, val, ttl).Err()
}

func (r *RedisCache) Del(ctx context.Context, keys ...string) error {
	if len(keys) == 0 {
		return nil
	}
	return r.rdb.Del(ctx, keys...).Err()
}

// DelByPattern uses SCAN+DEL in batches of 500. Slow but safe vs. KEYS.
// For small-ish caches (< 1M keys) this is acceptable; switch to event-
// driven invalidation if the pattern volume grows.
func (r *RedisCache) DelByPattern(ctx context.Context, pattern string) error {
	iter := r.rdb.Scan(ctx, 0, pattern, 500).Iterator()
	batch := make([]string, 0, 500)
	flush := func() error {
		if len(batch) == 0 {
			return nil
		}
		err := r.rdb.Del(ctx, batch...).Err()
		batch = batch[:0]
		return err
	}
	for iter.Next(ctx) {
		batch = append(batch, iter.Val())
		if len(batch) >= 500 {
			if err := flush(); err != nil {
				return err
			}
		}
	}
	if err := iter.Err(); err != nil {
		return err
	}
	return flush()
}

func (r *RedisCache) Close() error { return r.rdb.Close() }
`

const noopImpl = `
// Code generated by grpc-gen. DO NOT EDIT.
// Noop is the zero-impact Cache: every Get is a miss, every Set/Del is a
// no-op. Use it when CACHE_REDIS_ADDR is unset so the gateway still works
// (just without caching).

package cache

import (
	"context"
	"time"
)

type Noop struct{}

func (Noop) Get(context.Context, string) ([]byte, bool, error)         { return nil, false, nil }
func (Noop) Set(context.Context, string, []byte, time.Duration) error  { return nil }
func (Noop) Del(context.Context, ...string) error                      { return nil }
func (Noop) DelByPattern(context.Context, string) error                { return nil }
`

const keysHelpers = `
// Code generated by grpc-gen. DO NOT EDIT.
// Key layout:
//   entity load:   e:<Type>:v:<ViewerID>:id:<id>
//   list result:   e:<Type>:v:<ViewerID>:list:<hash>
// Invalidation patterns (cross-viewer):
//   single id:     e:<Type>:v:*:id:<id>
//   any list:      e:<Type>:v:*:list:*

package cache

import (
	"crypto/sha1"
	"encoding/hex"
)

// ViewerAnon is the key segment used for unauthenticated requests so an
// empty UserID can't accidentally collide with a real viewer.
const ViewerAnon = "anon"

func EntityKey(typ, viewerID, id string) string {
	if viewerID == "" {
		viewerID = ViewerAnon
	}
	return "e:" + typ + ":v:" + viewerID + ":id:" + id
}

func ListKey(typ, viewerID, hash string) string {
	if viewerID == "" {
		viewerID = ViewerAnon
	}
	return "e:" + typ + ":v:" + viewerID + ":list:" + hash
}

func EntityPattern(typ, id string) string {
	return "e:" + typ + ":v:*:id:" + id
}

func ListPattern(typ string) string {
	return "e:" + typ + ":v:*:list:*"
}

// HashBytes turns a marshalled proto request into a stable cache key
// fragment. SHA-1 truncated to 16 chars is enough collision resistance
// for cache keys (cardinality bounded by distinct queries per viewer).
func HashBytes(b []byte) string {
	sum := sha1.Sum(b)
	return hex.EncodeToString(sum[:])[:16]
}
`
