package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ConvertGenInput drives gen of graph/convert/*.go (proto ↔ gqlgen model).
type ConvertGenInput struct {
	ServerDir  string
	ModulePath string
	Protos     []ProtoInfo
}

// GenerateConverters writes one file per service in graph/convert/.
// Each file holds PBTo<Entity> and <Entity>ToPB functions plus slice helpers.
func GenerateConverters(in ConvertGenInput) error {
	dir := filepath.Join(in.ServerDir, "graph", "convert")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	for _, p := range in.Protos {
		path := filepath.Join(dir, p.ServiceName+".go")
		content := renderConvertFile(p, in.ModulePath)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func renderConvertFile(p ProtoInfo, modulePath string) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "// Code generated by grpc-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// proto ↔ gqlgen-model converters for service %q.\n\n", p.ServiceName)
	fmt.Fprintf(&sb, "package convert\n\n")

	// Determine which imports we actually need by scanning entity fields.
	imports := computeConvertImports(p)
	fmt.Fprintf(&sb, "import (\n")
	for _, imp := range imports {
		fmt.Fprintf(&sb, "\t%s\n", imp)
	}
	fmt.Fprintf(&sb, "\n\tpb \"%s/proto/%s\"\n", modulePath, p.ServiceName)
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/model\"\n", modulePath)
	fmt.Fprintf(&sb, ")\n\n")

	// Enum conversions first — they're called from entity converters.
	for _, en := range sortedEnums(p.Enums) {
		renderEnumConvert(&sb, en)
	}

	// Entity converters.
	for _, m := range sortedMessages(p.Messages) {
		if !IsEntityMessage(m.Name) {
			continue
		}
		renderEntityConvert(&sb, m, p)
	}
	return sb.String()
}

func computeConvertImports(p ProtoInfo) []string {
	need := map[string]bool{}
	for _, m := range p.Messages {
		if !IsEntityMessage(m.Name) {
			continue
		}
		for _, f := range m.Fields {
			if isIDField(f.Name) {
				need[`"strconv"`] = true
			}
			// timestamppb is only needed once we gen ModelToPB (Phase 5 only
			// does PB→Model, which calls *.AsTime() — no import required).
		}
	}
	var out []string
	for k := range need {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// modelFieldName turns a snake_case proto field name into its Go name in the
// gqlgen-generated model, applying the same initialism rules gqlgen does
// (URL, ID, IP, API, JSON, UUID, ...). Used for `out.<field>` assignments;
// proto-side access uses plain PascalCase via pascalCaseFromSnake.
func modelFieldName(snake string) string {
	initialisms := map[string]string{
		"id": "ID", "url": "URL", "uri": "URI", "ip": "IP",
		"api": "API", "json": "JSON", "uuid": "UUID",
		"http": "HTTP", "https": "HTTPS", "html": "HTML", "xml": "XML",
		"sql": "SQL", "tcp": "TCP", "tls": "TLS", "ttl": "TTL",
	}
	parts := strings.Split(snake, "_")
	for i, p := range parts {
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			parts[i] = up
		} else if p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func renderEnumConvert(sb *strings.Builder, en EnumInfo) {
	// PB→Model: proto enum.String() returns the constant name (e.g. "ADMIN")
	// which exactly matches the gqlgen-emitted enum value name.
	fmt.Fprintf(sb, "// %sFromPB maps the proto %s value to the GraphQL enum string.\n", en.Name, en.Name)
	fmt.Fprintf(sb, "func %sFromPB(v pb.%s) model.%s {\n", en.Name, en.Name, en.Name)
	fmt.Fprintf(sb, "\treturn model.%s(v.String())\n", en.Name)
	fmt.Fprintf(sb, "}\n\n")

	// Model→PB: lookup the string name → proto enum value via the generated map.
	fmt.Fprintf(sb, "// %sToPB maps the GraphQL enum back to its proto value.\n", en.Name)
	fmt.Fprintf(sb, "func %sToPB(v model.%s) pb.%s {\n", en.Name, en.Name, en.Name)
	fmt.Fprintf(sb, "\treturn pb.%s(pb.%s_value[string(v)])\n", en.Name, en.Name)
	fmt.Fprintf(sb, "}\n\n")
}

func renderEntityConvert(sb *strings.Builder, msg MessageInfo, p ProtoInfo) {
	// PB→Model
	fmt.Fprintf(sb, "// PBTo%s converts a proto %s into the GraphQL model. Returns nil when in is nil.\n", msg.Name, msg.Name)
	fmt.Fprintf(sb, "func PBTo%s(in *pb.%s) *model.%s {\n", msg.Name, msg.Name, msg.Name)
	fmt.Fprintf(sb, "\tif in == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(sb, "\tout := &model.%s{}\n", msg.Name)
	for _, f := range msg.Fields {
		writePBToModelField(sb, f)
	}
	fmt.Fprintf(sb, "\treturn out\n")
	fmt.Fprintf(sb, "}\n\n")

	// Slice helper
	fmt.Fprintf(sb, "// PBTo%sSlice converts a slice of proto %s into models.\n", msg.Name, msg.Name)
	fmt.Fprintf(sb, "func PBTo%sSlice(in []*pb.%s) []*model.%s {\n", msg.Name, msg.Name, msg.Name)
	fmt.Fprintf(sb, "\tout := make([]*model.%s, 0, len(in))\n", msg.Name)
	fmt.Fprintf(sb, "\tfor _, x := range in {\n\t\tout = append(out, PBTo%s(x))\n\t}\n", msg.Name)
	fmt.Fprintf(sb, "\treturn out\n")
	fmt.Fprintf(sb, "}\n\n")
}

func writePBToModelField(sb *strings.Builder, f FieldInfo) {
	pbName := pascalCaseFromSnake(f.Name)    // protoc Go convention (no initialism)
	modName := modelFieldName(f.Name)         // gqlgen Go convention (initialism)

	// modelNull: the model field is a pointer (forced nullable by a
	// field-level @auth/@policy guard) while the proto field itself is NOT
	// optional. Take the value form and address-of it.
	modelNull := f.ModelNullable && !f.IsOptional

	// Special-case: ID-ish fields (id, *_id) → string in the GraphQL model.
	if isIDField(f.Name) {
		switch {
		case f.IsOptional:
			fmt.Fprintf(sb, "\tif in.%s != nil { s := strconv.FormatUint(*in.%s, 10); out.%s = &s }\n", pbName, pbName, modName)
		case modelNull:
			fmt.Fprintf(sb, "\t{ s := strconv.FormatUint(in.Get%s(), 10); out.%s = &s }\n", pbName, modName)
		default:
			fmt.Fprintf(sb, "\tout.%s = strconv.FormatUint(in.Get%s(), 10)\n", modName, pbName)
		}
		return
	}

	// Enum.
	if f.IsEnum {
		switch {
		case f.IsOptional:
			fmt.Fprintf(sb, "\tif in.%s != nil { v := %sFromPB(*in.%s); out.%s = &v }\n", pbName, f.Type, pbName, modName)
		case modelNull:
			fmt.Fprintf(sb, "\t{ v := %sFromPB(in.Get%s()); out.%s = &v }\n", f.Type, pbName, modName)
		default:
			fmt.Fprintf(sb, "\tout.%s = %sFromPB(in.Get%s())\n", modName, f.Type, pbName)
		}
		return
	}

	// Timestamp.
	if f.Type == "google.protobuf.Timestamp" {
		switch {
		case f.IsOptional:
			fmt.Fprintf(sb, "\tif in.%s != nil { t := in.%s.AsTime(); out.%s = &t }\n", pbName, pbName, modName)
		case modelNull:
			fmt.Fprintf(sb, "\t{ t := in.Get%s().AsTime(); out.%s = &t }\n", pbName, modName)
		default:
			fmt.Fprintf(sb, "\tout.%s = in.Get%s().AsTime()\n", modName, pbName)
		}
		return
	}

	// Scalars. gqlgen maps Int to Go `int`; proto values may be (u)int{32,64}.
	switch f.Type {
	case "string", "bool", "double", "float", "bytes":
		switch {
		case f.IsOptional:
			fmt.Fprintf(sb, "\tout.%s = in.%s\n", modName, pbName)
		case modelNull:
			fmt.Fprintf(sb, "\t{ v := in.Get%s(); out.%s = &v }\n", pbName, modName)
		default:
			fmt.Fprintf(sb, "\tout.%s = in.Get%s()\n", modName, pbName)
		}
	case "int32", "int64", "uint32", "uint64", "sint32", "sint64", "fixed32", "fixed64", "sfixed32", "sfixed64":
		switch {
		case f.IsOptional:
			fmt.Fprintf(sb, "\tif in.%s != nil { v := int(*in.%s); out.%s = &v }\n", pbName, pbName, modName)
		case modelNull:
			fmt.Fprintf(sb, "\t{ v := int(in.Get%s()); out.%s = &v }\n", pbName, modName)
		default:
			fmt.Fprintf(sb, "\tout.%s = int(in.Get%s())\n", modName, pbName)
		}
	default:
		fmt.Fprintf(sb, "\t// TODO: convert field %s of type %s\n", f.Name, f.Type)
	}
}

func isIDField(name string) bool {
	return name == "id" || strings.HasSuffix(name, "_id")
}

func isIntegerType(t string) bool {
	switch t {
	case "int32", "int64", "uint32", "uint64", "sint32", "sint64", "fixed32", "fixed64", "sfixed32", "sfixed64":
		return true
	}
	return false
}
