package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GenerateInputConverters appends Model→PB input converters to the existing
// service convert files (one Create+Update input converter per entity).
// Also writes a single graph/convert/common.go for SearchInput / FilterCriteria.
func GenerateInputConverters(in ConvertGenInput) error {
	dir := filepath.Join(in.ServerDir, "graph", "convert")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// 1. graph/convert/common.go — shared SearchInput / FilterCriteria.
	if err := os.WriteFile(filepath.Join(dir, "common.go"), []byte(commonConvertSource(in.ModulePath)), 0644); err != nil {
		return err
	}

	// 2. Per-service input converter file (appended to existing service file).
	for _, p := range in.Protos {
		content := renderInputConverterFile(p, in.ModulePath)
		path := filepath.Join(dir, p.ServiceName+"_input.go")
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return err
		}
	}
	return nil
}

func commonConvertSource(modulePath string) string {
	return strings.TrimLeft(fmt.Sprintf(`
// Code generated by grpc-gen. DO NOT EDIT.
// Shared SearchInput / FilterCriteria / Pagination converters.

package convert

import (
	commonpb "%s/proto/common"
	"%s/src/server/graph/model"
)

// SearchInputToPB lifts the GraphQL SearchInput into the proto SearchRequest.
func SearchInputToPB(in *model.SearchInput) *commonpb.SearchRequest {
	if in == nil {
		return nil
	}
	out := &commonpb.SearchRequest{}
	if in.Pagination != nil {
		out.Pagination = &commonpb.Pagination{}
		if in.Pagination.Page != nil {
			out.Pagination.Page = int32(*in.Pagination.Page)
		}
		if in.Pagination.PageSize != nil {
			out.Pagination.PageSize = int32(*in.Pagination.PageSize)
		}
		if in.Pagination.SortBy != nil {
			out.Pagination.SortBy = *in.Pagination.SortBy
		}
		if in.Pagination.Descending != nil {
			out.Pagination.Descending = *in.Pagination.Descending
		}
	}
	for _, fc := range in.Filters {
		if pbfc := FilterCriteriaInputToPB(fc); pbfc != nil {
			out.Filters = append(out.Filters, pbfc)
		}
	}
	return out
}

// FilterCriteriaInputToPB converts one criteria. Recursive for groups.
func FilterCriteriaInputToPB(in *model.FilterCriteria) *commonpb.FilterCriteria {
	if in == nil {
		return nil
	}
	out := &commonpb.FilterCriteria{}
	if in.Condition != nil {
		out.Criteria = &commonpb.FilterCriteria_Condition{
			Condition: &commonpb.FilterCondition{
				Field:    in.Condition.Field,
				Operator: commonpb.FilterOperator(commonpb.FilterOperator_value[string(in.Condition.Operator)]),
				Values:   in.Condition.Values,
			},
		}
	}
	if in.Group != nil {
		grp := &commonpb.FilterGroup{
			Logic: commonpb.LogicalCondition(commonpb.LogicalCondition_value[string(in.Group.Logic)]),
		}
		for _, child := range in.Group.Filters {
			if c := FilterCriteriaInputToPB(child); c != nil {
				grp.Filters = append(grp.Filters, c)
			}
		}
		out.Criteria = &commonpb.FilterCriteria_Group{Group: grp}
	}
	return out
}

// FilterCriteriaInputSliceToPB converts a slice for batch update/delete.
func FilterCriteriaInputSliceToPB(in []*model.FilterCriteria) []*commonpb.FilterCriteria {
	out := make([]*commonpb.FilterCriteria, 0, len(in))
	for _, f := range in {
		if pbfc := FilterCriteriaInputToPB(f); pbfc != nil {
			out = append(out, pbfc)
		}
	}
	return out
}
`, modulePath, modulePath), "\n")
}

func renderInputConverterFile(p ProtoInfo, modulePath string) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "// Code generated by grpc-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// Model→PB input converters for service %q.\n\n", p.ServiceName)
	fmt.Fprintf(&sb, "package convert\n\n")

	// Compute needed imports.
	needTimestamppb := hasTimestampInputs(p)
	needStrconv := hasIDInputs(p)

	fmt.Fprintf(&sb, "import (\n")
	if needStrconv {
		fmt.Fprintf(&sb, "\t\"strconv\"\n\n")
	}
	if needTimestamppb {
		fmt.Fprintf(&sb, "\t\"google.golang.org/protobuf/types/known/timestamppb\"\n\n")
	}
	fmt.Fprintf(&sb, "\tpb \"%s/proto/%s\"\n", modulePath, p.ServiceName)
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/model\"\n", modulePath)
	fmt.Fprintf(&sb, ")\n\n")

	// Suppress "imported and not used" if a service has no IDs/timestamps.
	if !needStrconv {
		fmt.Fprintf(&sb, "// (strconv unused for this service — no ID input fields.)\n\n")
	}
	if !needTimestamppb {
		fmt.Fprintf(&sb, "// (timestamppb unused for this service — no Timestamp input fields.)\n\n")
	}

	for _, m := range sortedMessages(p.Messages) {
		if strings.HasPrefix(m.Name, "Create") && strings.HasSuffix(m.Name, "Request") {
			entity := strings.TrimSuffix(strings.TrimPrefix(m.Name, "Create"), "Request")
			renderCreateInputConverter(&sb, entity, m)
		}
		if strings.HasPrefix(m.Name, "Update") && strings.HasSuffix(m.Name, "Request") {
			entity := strings.TrimSuffix(strings.TrimPrefix(m.Name, "Update"), "Request")
			renderUpdateInputConverter(&sb, entity, m)
		}
	}

	return sb.String()
}

func hasTimestampInputs(p ProtoInfo) bool {
	for _, m := range p.Messages {
		if !strings.HasSuffix(m.Name, "Request") {
			continue
		}
		for _, f := range m.Fields {
			if f.Type == "google.protobuf.Timestamp" {
				return true
			}
		}
	}
	return false
}

func hasIDInputs(p ProtoInfo) bool {
	for _, m := range p.Messages {
		if !strings.HasSuffix(m.Name, "Request") {
			continue
		}
		for _, f := range m.Fields {
			if isIDField(f.Name) {
				return true
			}
		}
	}
	return false
}

func renderCreateInputConverter(sb *strings.Builder, entity string, msg MessageInfo) {
	fmt.Fprintf(sb, "// Create%sInputToPB converts the GraphQL input into the proto request.\n", entity)
	fmt.Fprintf(sb, "func Create%sInputToPB(in model.Create%sInput) *pb.Create%sRequest {\n", entity, entity, entity)
	fmt.Fprintf(sb, "\tout := &pb.Create%sRequest{}\n", entity)
	for _, f := range msg.Fields {
		if f.Type == "common.FilterCriteria" {
			continue
		}
		writeModelToPBField(sb, f, true /*createInputFlavor*/)
	}
	fmt.Fprintf(sb, "\treturn out\n")
	fmt.Fprintf(sb, "}\n\n")
}

func renderUpdateInputConverter(sb *strings.Builder, entity string, msg MessageInfo) {
	fmt.Fprintf(sb, "// Update%sInputToPB converts the GraphQL input + filters into the proto request.\n", entity)
	fmt.Fprintf(sb, "func Update%sInputToPB(filters []*model.FilterCriteria, in model.Update%sInput) *pb.Update%sRequest {\n", entity, entity, entity)
	fmt.Fprintf(sb, "\tout := &pb.Update%sRequest{Filters: FilterCriteriaInputSliceToPB(filters)}\n", entity)
	for _, f := range msg.Fields {
		if f.Type == "common.FilterCriteria" {
			continue
		}
		writeModelToPBField(sb, f, false /*createInputFlavor*/)
	}
	fmt.Fprintf(sb, "\treturn out\n")
	fmt.Fprintf(sb, "}\n\n")
}

// writeModelToPBField writes a single field assignment from the GraphQL input
// to the proto request. `inCreate` indicates whether we're inside CreateInput
// (where most fields are required scalars) vs UpdateInput (where everything is
// optional). The actual nullability is read from FieldInfo.IsOptional, but we
// pass the flag in case future logic needs it.
func writeModelToPBField(sb *strings.Builder, f FieldInfo, inCreate bool) {
	_ = inCreate
	pbName := pascalCaseFromSnake(f.Name)
	modName := modelFieldName(f.Name)

	// ID-ish fields (proto uint64 ↔ model string)
	if isIDField(f.Name) {
		if f.IsOptional {
			fmt.Fprintf(sb, "\tif in.%s != nil {\n", modName)
			fmt.Fprintf(sb, "\t\tif v, err := strconv.ParseUint(*in.%s, 10, 64); err == nil {\n", modName)
			fmt.Fprintf(sb, "\t\t\tout.%s = &v\n", pbName)
			fmt.Fprintf(sb, "\t\t}\n\t}\n")
		} else {
			fmt.Fprintf(sb, "\tif v, err := strconv.ParseUint(in.%s, 10, 64); err == nil { out.%s = v }\n", modName, pbName)
		}
		return
	}

	if f.IsEnum {
		if f.IsOptional {
			fmt.Fprintf(sb, "\tif in.%s != nil { v := %sToPB(*in.%s); out.%s = &v }\n", modName, f.Type, modName, pbName)
		} else {
			fmt.Fprintf(sb, "\tout.%s = %sToPB(in.%s)\n", pbName, f.Type, modName)
		}
		return
	}

	if f.Type == "google.protobuf.Timestamp" {
		if f.IsOptional {
			fmt.Fprintf(sb, "\tif in.%s != nil { out.%s = timestamppb.New(*in.%s) }\n", modName, pbName, modName)
		} else {
			fmt.Fprintf(sb, "\tout.%s = timestamppb.New(in.%s)\n", pbName, modName)
		}
		return
	}

	switch f.Type {
	case "string", "bool", "double", "float", "bytes":
		if f.IsOptional {
			fmt.Fprintf(sb, "\tout.%s = in.%s\n", pbName, modName)
		} else {
			fmt.Fprintf(sb, "\tout.%s = in.%s\n", pbName, modName)
		}
	case "int32", "int64", "uint32", "uint64", "sint32", "sint64", "fixed32", "fixed64", "sfixed32", "sfixed64":
		goType := protoIntToGoType(f.Type)
		if f.IsOptional {
			fmt.Fprintf(sb, "\tif in.%s != nil { v := %s(*in.%s); out.%s = &v }\n", modName, goType, modName, pbName)
		} else {
			fmt.Fprintf(sb, "\tout.%s = %s(in.%s)\n", pbName, goType, modName)
		}
	default:
		fmt.Fprintf(sb, "\t// TODO: convert input field %s of type %s\n", f.Name, f.Type)
	}
}

func protoIntToGoType(protoType string) string {
	switch protoType {
	case "int32", "sint32", "sfixed32":
		return "int32"
	case "int64", "sint64", "sfixed64":
		return "int64"
	case "uint32", "fixed32":
		return "uint32"
	case "uint64", "fixed64":
		return "uint64"
	}
	return protoType
}
