package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// DataLoaderGenInput drives generation of graph/dataloader/*.go.
type DataLoaderGenInput struct {
	ServerDir  string
	ModulePath string
	Protos     []ProtoInfo
}

// GenerateDataLoaders writes one Loader per entity plus a Loaders aggregator
// and per-request-context helpers.
func GenerateDataLoaders(in DataLoaderGenInput) error {
	dir := filepath.Join(in.ServerDir, "graph", "dataloader")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Collect (entity, owning service) tuples in stable order.
	var entries []entityEntry
	for _, p := range in.Protos {
		for _, m := range p.Messages {
			if IsEntityMessage(m.Name) {
				entries = append(entries, entityEntry{Entity: m.Name, Service: p.ServiceName})
			}
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Entity < entries[j].Entity })

	// Per-entity file.
	for _, e := range entries {
		content := renderLoaderFile(e.Entity, e.Service, in.ModulePath)
		path := filepath.Join(dir, snakeCase(e.Entity)+".go")
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return err
		}
	}

	// Loaders aggregator + context helpers.
	loaders := renderLoadersAggregator(entries, in.ModulePath)
	if err := os.WriteFile(filepath.Join(dir, "loaders.go"), []byte(loaders), 0644); err != nil {
		return err
	}

	return nil
}

func renderLoaderFile(entity, service, modulePath string) string {
	var sb strings.Builder
	loaderName := entity + "Loader"
	pbField := pascalCaseFromSnake(snakeCase(entity)) // proto field name in PascalCase

	fmt.Fprintf(&sb, "// Code generated by grpc-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&sb, "package dataloader\n\n")

	fmt.Fprintf(&sb, "import (\n")
	fmt.Fprintf(&sb, "\t\"context\"\n")
	fmt.Fprintf(&sb, "\t\"fmt\"\n")
	fmt.Fprintf(&sb, "\t\"strconv\"\n\n")
	fmt.Fprintf(&sb, "\t\"github.com/graph-gophers/dataloader/v7\"\n")
	fmt.Fprintf(&sb, "\t\"google.golang.org/protobuf/proto\"\n\n")
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/cache\"\n", modulePath)
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/client\"\n", modulePath)
	fmt.Fprintf(&sb, "\tcommonpb \"%s/proto/common\"\n", modulePath)
	fmt.Fprintf(&sb, "\tpb \"%s/proto/%s\"\n", modulePath, service)
	fmt.Fprintf(&sb, ")\n\n")

	fmt.Fprintf(&sb, "type %s = dataloader.Loader[string, *pb.%s]\n\n", loaderName, entity)

	// Constructor.
	fmt.Fprintf(&sb, "// New%s returns a request-scoped Loader. The batch function checks the\n", loaderName)
	fmt.Fprintf(&sb, "// shared entity cache per id first (per-viewer key), only fanning out to\n")
	fmt.Fprintf(&sb, "// gRPC for misses. Misses get written back to cache before returning.\n")
	fmt.Fprintf(&sb, "// The gRPC call bypasses the client list cache via Stub() to avoid\n")
	fmt.Fprintf(&sb, "// double-caching.\n")
	fmt.Fprintf(&sb, "func New%s(c *client.Clients) *%s {\n", loaderName, loaderName)
	fmt.Fprintf(&sb, "\tbatch := func(ctx context.Context, ids []string) []*dataloader.Result[*pb.%s] {\n", entity)
	fmt.Fprintf(&sb, "\t\tout := make([]*dataloader.Result[*pb.%s], len(ids))\n", entity)
	fmt.Fprintf(&sb, "\t\tvid := viewerID(ctx)\n")
	fmt.Fprintf(&sb, "\t\tmissIdx := make([]int, 0, len(ids))\n")
	fmt.Fprintf(&sb, "\t\tmissIDs := make([]string, 0, len(ids))\n\n")

	fmt.Fprintf(&sb, "\t\tif c.Cache != nil {\n")
	fmt.Fprintf(&sb, "\t\t\tfor i, id := range ids {\n")
	fmt.Fprintf(&sb, "\t\t\t\tkey := cache.EntityKey(%q, vid, id)\n", entity)
	fmt.Fprintf(&sb, "\t\t\t\tif b, ok, _ := c.Cache.Get(ctx, key); ok {\n")
	fmt.Fprintf(&sb, "\t\t\t\t\tvar item pb.%s\n", entity)
	fmt.Fprintf(&sb, "\t\t\t\t\tif proto.Unmarshal(b, &item) == nil {\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t\tout[i] = &dataloader.Result[*pb.%s]{Data: &item}\n", entity)
	fmt.Fprintf(&sb, "\t\t\t\t\t\tcontinue\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t}\n")
	fmt.Fprintf(&sb, "\t\t\t\t}\n")
	fmt.Fprintf(&sb, "\t\t\t\tmissIdx = append(missIdx, i)\n")
	fmt.Fprintf(&sb, "\t\t\t\tmissIDs = append(missIDs, id)\n")
	fmt.Fprintf(&sb, "\t\t\t}\n")
	fmt.Fprintf(&sb, "\t\t} else {\n")
	fmt.Fprintf(&sb, "\t\t\tfor i, id := range ids {\n")
	fmt.Fprintf(&sb, "\t\t\t\tmissIdx = append(missIdx, i)\n")
	fmt.Fprintf(&sb, "\t\t\t\tmissIDs = append(missIDs, id)\n")
	fmt.Fprintf(&sb, "\t\t\t\t_ = id\n")
	fmt.Fprintf(&sb, "\t\t\t}\n")
	fmt.Fprintf(&sb, "\t\t}\n\n")

	fmt.Fprintf(&sb, "\t\tif len(missIDs) == 0 { return out }\n\n")

	fmt.Fprintf(&sb, "\t\treq := &pb.List%sRequest{\n", entity)
	fmt.Fprintf(&sb, "\t\t\tSearch: &commonpb.SearchRequest{\n")
	fmt.Fprintf(&sb, "\t\t\t\tFilters: []*commonpb.FilterCriteria{{\n")
	fmt.Fprintf(&sb, "\t\t\t\t\tCriteria: &commonpb.FilterCriteria_Condition{\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t\tCondition: &commonpb.FilterCondition{\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t\t\tField:    \"id\",\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t\t\tOperator: commonpb.FilterOperator_IN,\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t\t\tValues:   missIDs,\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t\t},\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t},\n")
	fmt.Fprintf(&sb, "\t\t\t\t}},\n")
	fmt.Fprintf(&sb, "\t\t\t\tPagination: &commonpb.Pagination{PageSize: int32(len(missIDs))},\n")
	fmt.Fprintf(&sb, "\t\t\t},\n")
	fmt.Fprintf(&sb, "\t\t}\n")
	fmt.Fprintf(&sb, "\t\tresp, err := c.%s.Stub().List%s(ctx, req)\n", capitalize(service), entity)
	fmt.Fprintf(&sb, "\t\tif err != nil {\n")
	fmt.Fprintf(&sb, "\t\t\tfor _, i := range missIdx { out[i] = &dataloader.Result[*pb.%s]{Error: err} }\n", entity)
	fmt.Fprintf(&sb, "\t\t\treturn out\n")
	fmt.Fprintf(&sb, "\t\t}\n\n")

	fmt.Fprintf(&sb, "\t\tbyID := make(map[string]*pb.%s, len(resp.Get%s()))\n", entity, pbField)
	fmt.Fprintf(&sb, "\t\tfor _, item := range resp.Get%s() {\n", pbField)
	fmt.Fprintf(&sb, "\t\t\tbyID[strconv.FormatUint(item.GetId(), 10)] = item\n")
	fmt.Fprintf(&sb, "\t\t}\n\n")

	fmt.Fprintf(&sb, "\t\tfor k, i := range missIdx {\n")
	fmt.Fprintf(&sb, "\t\t\tid := missIDs[k]\n")
	fmt.Fprintf(&sb, "\t\t\tif item, ok := byID[id]; ok {\n")
	fmt.Fprintf(&sb, "\t\t\t\tout[i] = &dataloader.Result[*pb.%s]{Data: item}\n", entity)
	fmt.Fprintf(&sb, "\t\t\t\tif c.Cache != nil {\n")
	fmt.Fprintf(&sb, "\t\t\t\t\tif b, mErr := proto.Marshal(item); mErr == nil {\n")
	fmt.Fprintf(&sb, "\t\t\t\t\t\t_ = c.Cache.Set(ctx, cache.EntityKey(%q, vid, id), b, c.TTL)\n", entity)
	fmt.Fprintf(&sb, "\t\t\t\t\t}\n")
	fmt.Fprintf(&sb, "\t\t\t\t}\n")
	fmt.Fprintf(&sb, "\t\t\t} else {\n")
	fmt.Fprintf(&sb, "\t\t\t\tout[i] = &dataloader.Result[*pb.%s]{Error: fmt.Errorf(\"%s id %%s not found\", id)}\n", entity, entity)
	fmt.Fprintf(&sb, "\t\t\t}\n")
	fmt.Fprintf(&sb, "\t\t}\n")
	fmt.Fprintf(&sb, "\t\treturn out\n")
	fmt.Fprintf(&sb, "\t}\n")
	fmt.Fprintf(&sb, "\treturn dataloader.NewBatchedLoader(batch)\n")
	fmt.Fprintf(&sb, "}\n")
	return sb.String()
}

// entityEntry pairs an entity name with the service that owns it.
type entityEntry struct {
	Entity  string // PascalCase (e.g. "ClassInviteKey")
	Service string // proto service folder (e.g. "class")
}

func renderLoadersAggregator(entries []entityEntry, modulePath string) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by grpc-gen. DO NOT EDIT.\n")
	sb.WriteString("// Per-request DataLoader bundle. Created once per HTTP request by the\n")
	sb.WriteString("// gateway middleware so cached responses can't leak between viewers.\n\n")
	sb.WriteString("package dataloader\n\n")

	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n\n")
	sb.WriteString("\t\"github.com/graph-gophers/dataloader/v7\"\n\n")
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/auth\"\n", modulePath)
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/client\"\n", modulePath)
	sb.WriteString(")\n\n")

	// Loaders struct.
	sb.WriteString("// Loaders aggregates one DataLoader per entity.\n")
	sb.WriteString("type Loaders struct {\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "\t%s *%sLoader\n", e.Entity, e.Entity)
	}
	sb.WriteString("}\n\n")

	// Constructor.
	sb.WriteString("// New builds a fresh Loaders bundle. Call once per HTTP request.\n")
	sb.WriteString("func New(c *client.Clients) *Loaders {\n")
	sb.WriteString("\treturn &Loaders{\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "\t\t%s: New%sLoader(c),\n", e.Entity, e.Entity)
	}
	sb.WriteString("\t}\n}\n\n")

	// Context plumbing.
	sb.WriteString("type ctxKey struct{}\n\n")

	sb.WriteString("// WithContext stashes the Loaders for the current request.\n")
	sb.WriteString("func WithContext(ctx context.Context, l *Loaders) context.Context {\n")
	sb.WriteString("\treturn context.WithValue(ctx, ctxKey{}, l)\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// For retrieves the Loaders previously stored on ctx. Panics if the\n")
	sb.WriteString("// middleware hasn't run — that's a wiring bug, not a runtime one.\n")
	sb.WriteString("func For(ctx context.Context) *Loaders {\n")
	sb.WriteString("\tl, _ := ctx.Value(ctxKey{}).(*Loaders)\n")
	sb.WriteString("\tif l == nil {\n")
	sb.WriteString("\t\tpanic(\"dataloader.For called before WithContext; did you forget the middleware?\")\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn l\n")
	sb.WriteString("}\n\n")

	// viewerID helper — same job as client.viewerID but lives here so the
	// dataloader package doesn't have to reach into client's internals.
	sb.WriteString("// viewerID extracts the request's user id (or empty string for anon).\n")
	sb.WriteString("// Cache key builders treat the empty string as cache.ViewerAnon.\n")
	sb.WriteString("func viewerID(ctx context.Context) string {\n")
	sb.WriteString("\tv := auth.FromContext(ctx)\n")
	sb.WriteString("\tif v == nil { return \"\" }\n")
	sb.WriteString("\treturn v.UserID\n")
	sb.WriteString("}\n\n")

	// errResults helper.
	sb.WriteString("// errResults wraps a single batch-level error into per-key Result entries\n")
	sb.WriteString("// so dataloader callers see the failure on every requested key.\n")
	sb.WriteString("func errResults[T any](ids []string, err error) []*dataloader.Result[T] {\n")
	sb.WriteString("\tout := make([]*dataloader.Result[T], len(ids))\n")
	sb.WriteString("\tfor i := range ids {\n")
	sb.WriteString("\t\tout[i] = &dataloader.Result[T]{Error: err}\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn out\n")
	sb.WriteString("}\n")

	return sb.String()
}

// ─── helpers ───

func snakeCase(pascal string) string {
	var sb strings.Builder
	for i, r := range pascal {
		if i > 0 && r >= 'A' && r <= 'Z' {
			sb.WriteByte('_')
		}
		sb.WriteRune(r)
	}
	return strings.ToLower(sb.String())
}

func pascalCaseFromSnake(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}
