package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// DomainGenInput drives gen of graph/domain/* — the dynamic business-rule
// engine. Rules live in MongoDB; this package is the rule-agnostic machinery.
type DomainGenInput struct {
	ServerDir  string
	ModulePath string
	Protos     []ProtoInfo
}

// GenerateDomain writes the graph/domain package:
//   - store.go       — MongoDB rule loader (RuleStore)
//   - engine.go      — declarative fetch + expr-lang condition evaluator
//   - interceptor.go — gRPC client interceptor that runs rules on mutations
//   - registry.go    — per-entity List wrappers (generated from the protos)
func GenerateDomain(in DomainGenInput) error {
	dir := filepath.Join(in.ServerDir, "graph", "domain")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	// ~BT~ is a backtick placeholder — struct tags and the test file's raw
	// strings can't appear verbatim inside a backtick const.
	subst := strings.NewReplacer("MODULE_PATH", in.ModulePath, "~BT~", "`")
	files := map[string]string{
		"store.go":          subst.Replace(domainStoreGo),
		"interceptor.go":    subst.Replace(domainInterceptorGo),
		"engine.go":         subst.Replace(domainEngineGo),
		"engine_test.go":    subst.Replace(domainEngineTestGo),
		"action.go":         subst.Replace(domainActionGo),
		"system_context.go": subst.Replace(domainSystemContextGo),
		"triggers.go":       subst.Replace(domainTriggersGo),
		"registry.go":       renderDomainRegistry(in.Protos, in.ModulePath),
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(strings.TrimLeft(body, "\n")), 0644); err != nil {
			return err
		}
	}
	return nil
}

// renderDomainRegistry emits one ListFunc per entity over the gRPC clients —
// the only entity-aware file in the package.
func renderDomainRegistry(protos []ProtoInfo, modulePath string) string {
	type ent struct{ Entity, Service string }
	var ents []ent
	svcSet := map[string]bool{}
	for _, p := range protos {
		for _, m := range p.Messages {
			if IsEntityMessage(m.Name) {
				ents = append(ents, ent{m.Name, p.ServiceName})
				svcSet[p.ServiceName] = true
			}
		}
	}
	sort.Slice(ents, func(i, j int) bool { return ents[i].Entity < ents[j].Entity })
	svcs := make([]string, 0, len(svcSet))
	for s := range svcSet {
		svcs = append(svcs, s)
	}
	sort.Strings(svcs)

	var sb strings.Builder
	sb.WriteString("// Code generated by grpc-gen. DO NOT EDIT.\n\n")
	sb.WriteString("package domain\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n")
	sb.WriteString("\t\"encoding/json\"\n\n")
	sb.WriteString("\t\"google.golang.org/protobuf/encoding/protojson\"\n")
	sb.WriteString("\t\"google.golang.org/protobuf/proto\"\n\n")
	for _, s := range svcs {
		fmt.Fprintf(&sb, "\t%spb \"%s/proto/%s\"\n", s, modulePath, s)
	}
	fmt.Fprintf(&sb, "\tcommonpb \"%s/proto/common\"\n", modulePath)
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/client\"\n", modulePath)
	sb.WriteString(")\n\n")

	sb.WriteString("// ListFunc runs a filtered List for one entity and returns each row as a\n")
	sb.WriteString("// plain map[string]any so rule conditions / fetch references can read\n")
	sb.WriteString("// fields generically without per-entity Go code.\n")
	sb.WriteString("type ListFunc func(ctx context.Context, search *commonpb.SearchRequest) ([]map[string]any, error)\n\n")

	sb.WriteString("// NewRegistry wires one ListFunc per entity over the gRPC clients.\n")
	sb.WriteString("// Calls go through .Stub() — the RAW gRPC client — deliberately\n")
	sb.WriteString("// bypassing the response cache: a business rule must decide on the\n")
	sb.WriteString("// current truth, never a stale cached list.\n")
	sb.WriteString("func NewRegistry(c *client.Clients) map[string]ListFunc {\n")
	sb.WriteString("\treturn map[string]ListFunc{\n")
	for _, e := range ents {
		clientField := capitalize(e.Service)
		fmt.Fprintf(&sb, "\t\t%q: func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {\n", e.Entity)
		fmt.Fprintf(&sb, "\t\t\tr, err := c.%s.Stub().List%s(ctx, &%spb.List%sRequest{Search: s})\n", clientField, e.Entity, e.Service, e.Entity)
		fmt.Fprintf(&sb, "\t\t\tif err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n")
		fmt.Fprintf(&sb, "\t\t\treturn toMaps(r.Get%s())\n", e.Entity)
		fmt.Fprintf(&sb, "\t\t},\n")
	}
	sb.WriteString("\t}\n}\n\n")

	sb.WriteString("// toMaps converts a slice of proto messages to plain maps via protojson,\n")
	sb.WriteString("// so rule conditions can address any field by its proto (snake_case) name.\n")
	sb.WriteString("func toMaps[T proto.Message](items []T) ([]map[string]any, error) {\n")
	sb.WriteString("\tmo := protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: true}\n")
	sb.WriteString("\tout := make([]map[string]any, 0, len(items))\n")
	sb.WriteString("\tfor _, it := range items {\n")
	sb.WriteString("\t\tb, err := mo.Marshal(it)\n")
	sb.WriteString("\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
	sb.WriteString("\t\tvar m map[string]any\n")
	sb.WriteString("\t\tif err := json.Unmarshal(b, &m); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
	sb.WriteString("\t\tout = append(out, m)\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn out, nil\n}\n\n")

	// opClientField maps a mutation RPC name to the *Clients struct field
	// that owns it — the action engine's write step uses it to dispatch a
	// gRPC mutation generically (reflection on the client wrapper).
	sb.WriteString("// opClientField maps a Create/Update/Delete RPC name to the client\n")
	sb.WriteString("// wrapper field on *client.Clients that exposes it.\n")
	sb.WriteString("var opClientField = map[string]string{\n")
	type opEntry struct{ Op, Field string }
	var ops []opEntry
	for _, p := range protos {
		for _, r := range p.RPCs {
			if strings.HasPrefix(r.Name, "Create") ||
				strings.HasPrefix(r.Name, "Update") ||
				strings.HasPrefix(r.Name, "Delete") {
				ops = append(ops, opEntry{r.Name, capitalize(p.ServiceName)})
			}
		}
	}
	sort.Slice(ops, func(i, j int) bool { return ops[i].Op < ops[j].Op })
	for _, o := range ops {
		fmt.Fprintf(&sb, "\t%q: %q,\n", o.Op, o.Field)
	}
	sb.WriteString("}\n")
	return sb.String()
}

// ─── fixed-text package files ───────────────────────────────────────────

const domainStoreGo = `
// Code generated by grpc-gen. DO NOT EDIT.

// Package domain is the dynamic business-rule engine. Rules live entirely in
// MongoDB — adding / editing / disabling a rule is a data change, no
// redeploy. The only Go code is rule-agnostic machinery: the Mongo loader
// (this file), the entity registry, the engine, and the gRPC interceptor.
package domain

import (
	"context"
	"fmt"
	"sort"
	"sync"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// Criteria is one node of a rule's WHERE tree. It is EITHER a leaf condition
// (Field/Op/Value set) OR a logical group: when Logic is non-empty
// ("AND" | "OR") the node groups the nested Group criteria instead — so a
// rule can express arbitrarily nested AND/OR, exactly like the gRPC
// common.FilterCriteria it compiles down to.
//
// Value (on a leaf) is a literal or a reference resolved at eval time:
//   $req.<field>             a field of the mutation request
//   $now                     current time (RFC3339 UTC)
//   $<fetchAs>.<idx>.<field>  a field of an earlier fetch result row
type Criteria struct {
	Field string // leaf: field name
	Op    string // leaf: EQUAL | NOT_EQUAL | IN | GREATER_THAN | ...
	Value string // leaf: literal or $-reference

	Logic string     // group: "AND" | "OR" — non-empty marks this a group
	Group []Criteria // group: nested criteria
}

// FetchStep declares one data load: List<Entity> filtered by Where, exposed
// to the condition expression (and to later fetches) under the name As.
// Top-level Where entries are AND-ed (gRPC SearchRequest.Filters semantics);
// use a Logic group entry for OR / nesting.
type FetchStep struct {
	As     string
	Entity string
	Where  []Criteria

	// UseRequestFilters prepends the triggering Update/Delete request's own
	// Filters to this fetch — so a rule can load the exact row(s) the
	// mutation targets, which is what state-transition and delete-dependency
	// checks need ($current.0.status, $current.0.id, ...). No effect on
	// Create requests (they carry no Filters).
	UseRequestFilters bool ~BT~bson:"use_request_filters"~BT~
}

// Rule is one business-rule document. Condition is an expr-lang expression
// over {req, now, <each fetch As>}; when it evaluates false the guarded
// mutation is rejected with Message.
type Rule struct {
	Operation string // gRPC method, e.g. "CreateExamAttempt"
	Rule      string // human name
	Enabled   bool
	Priority  int
	Fetch     []FetchStep
	Condition string
	Message   string
}

// RuleStore loads rules from MongoDB and indexes them by operation.
type RuleStore struct {
	coll *mongo.Collection
	mu   sync.RWMutex
	byOp map[string][]Rule
}

// NewRuleStore connects to Mongo and does the initial load.
func NewRuleStore(ctx context.Context, mongoURI, db, collection string) (*RuleStore, error) {
	client, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		return nil, fmt.Errorf("mongo connect: %w", err)
	}
	pctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := client.Ping(pctx, nil); err != nil {
		return nil, fmt.Errorf("mongo ping: %w", err)
	}
	s := &RuleStore{
		coll: client.Database(db).Collection(collection),
		byOp: map[string][]Rule{},
	}
	if err := s.Reload(ctx); err != nil {
		return nil, err
	}
	return s, nil
}

// Reload re-reads every rule from Mongo. Safe to call from a ticker or a
// dashboard webhook so edits take effect without a gateway restart.
func (s *RuleStore) Reload(ctx context.Context) error {
	cur, err := s.coll.Find(ctx, bson.M{})
	if err != nil {
		return fmt.Errorf("rule find: %w", err)
	}
	var rules []Rule
	if err := cur.All(ctx, &rules); err != nil {
		return fmt.Errorf("rule decode: %w", err)
	}
	idx := map[string][]Rule{}
	for _, r := range rules {
		idx[r.Operation] = append(idx[r.Operation], r)
	}
	for op := range idx {
		ops := idx[op]
		sort.SliceStable(ops, func(i, j int) bool { return ops[i].Priority < ops[j].Priority })
	}
	s.mu.Lock()
	s.byOp = idx
	s.mu.Unlock()
	return nil
}

// ForOperation returns the enabled rules guarding the given gRPC operation,
// in priority order.
func (s *RuleStore) ForOperation(op string) []Rule {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return enabledRules(s.byOp[op])
}

// OperationCount reports how many distinct operations currently have at
// least one enabled rule — handy for a startup log line.
func (s *RuleStore) OperationCount() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	n := 0
	for op := range s.byOp {
		if len(enabledRules(s.byOp[op])) > 0 {
			n++
		}
	}
	return n
}

func enabledRules(in []Rule) []Rule {
	out := make([]Rule, 0, len(in))
	for _, r := range in {
		if r.Enabled {
			out = append(out, r)
		}
	}
	return out
}
`

const domainEngineGo = `
// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"fmt"
	"log"
	"strconv"
	"strings"
	"time"

	"github.com/expr-lang/expr"

	commonpb "MODULE_PATH/proto/common"
)

// ViewerExtractor pulls the authenticated principal out of ctx into a plain
// map that rules can reference as the ` + "`viewer`" + ` variable. Returning nil/empty is
// fine — rules just see zero-valued fields.
//
// Decoupled from any concrete auth package so domain stays generator-pure;
// main.go wires the real extractor (typically reading auth.FromContext).
type ViewerExtractor func(ctx context.Context) map[string]any

// EngineOption configures NewEngine. Add new knobs here without breaking
// existing callers.
type EngineOption func(*Engine)

// WithViewerExtractor registers the function used to populate ` + "`env.viewer`" + ` for
// every rule evaluation. Without this option, ` + "`viewer`" + ` is always the empty
// principal — rules that gate on identity will deny everything.
func WithViewerExtractor(fn ViewerExtractor) EngineOption {
	return func(e *Engine) { e.viewer = fn }
}

// Engine evaluates business rules. It holds no rules itself — every rule is
// read from the RuleStore (MongoDB) at request time.
type Engine struct {
	rules    *RuleStore
	registry map[string]ListFunc
	viewer   ViewerExtractor
	scopes   *ReadScopeStore // optional RLS read-scope store (set via WithReadScopeStore)
}

// WithReadScopeStore plugs RLS into the engine so List ops can be filtered
// per (entity, role). Without this, ScopeFiltersFor always returns nil and
// no row-level filter is injected.
func WithReadScopeStore(s *ReadScopeStore) EngineOption {
	return func(e *Engine) { e.scopes = s }
}

// ScopeStore returns the configured scope store (may be nil).
func (e *Engine) ScopeStore() *ReadScopeStore { return e.scopes }

// NewEngine binds the rule store to the entity registry.
func NewEngine(rules *RuleStore, registry map[string]ListFunc, opts ...EngineOption) *Engine {
	e := &Engine{rules: rules, registry: registry}
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// ScopeFiltersFor returns the RLS filters to AND-prepend to a List<Entity>
// call's Search.Filters. Returns nil when:
//   - no scope store / system-context / ADMIN role / no matching scope rule
//
// Each scope can have direct ` + "`filters`" + ` (with $viewer.id refs) or a multi-hop
// ` + "`chain`" + `. The chain resolves sequentially: each step's results become $prev_ids
// in the next; the last step's LocalField is the FK to inject on the target.
// Fail-closed: empty chain result → sentinel ` + "`<local_field> EQUAL 0`" + ` → no rows.
func (e *Engine) ScopeFiltersFor(ctx context.Context, entity string) []*commonpb.FilterCriteria {
	if e == nil || e.scopes == nil || IsSystemContext(ctx) {
		return nil
	}
	v := e.viewerFor(ctx)
	role, _ := v["role"].(string)
	if role == "" || role == "ADMIN" {
		return nil
	}
	scopes := e.scopes.ForEntityRole(entity, role)
	if len(scopes) == 0 {
		return nil
	}
	env := map[string]any{"viewer": v, "now": time.Now().UTC().Format(time.RFC3339)}
	out := []*commonpb.FilterCriteria{}
	for _, sc := range scopes {
		if !sc.Enabled {
			continue
		}
		for _, f := range sc.Filters {
			out = append(out, buildCriteria(f, env))
		}
		if len(sc.Chain) > 0 {
			localField, ids, err := e.resolveChain(ctx, sc.Chain, env)
			if err != nil {
				log.Printf("scope chain %s/%s: %v (fail-closed)", sc.Entity, sc.ViewerRole, err)
				ids = nil
			}
			if localField == "" {
				continue
			}
			if len(ids) == 0 {
				out = append(out, &commonpb.FilterCriteria{
					Criteria: &commonpb.FilterCriteria_Condition{
						Condition: &commonpb.FilterCondition{
							Field: localField, Operator: commonpb.FilterOperator_EQUAL, Values: []string{"0"},
						},
					},
				})
				continue
			}
			out = append(out, &commonpb.FilterCriteria{
				Criteria: &commonpb.FilterCriteria_Condition{
					Condition: &commonpb.FilterCondition{
						Field: localField, Operator: commonpb.FilterOperator_IN, Values: ids,
					},
				},
			})
		}
	}
	return out
}

// resolveChain walks scope chain steps with WithSystemContext to avoid
// scope recursion on the engine's own internal fetches.
func (e *Engine) resolveChain(ctx context.Context, chain []ChainStep, env map[string]any) (localField string, ids []string, err error) {
	sysCtx := WithSystemContext(ctx)
	for i, step := range chain {
		lf, ok := e.registry[step.ViaEntity]
		if !ok {
			return "", nil, fmt.Errorf("chain step %d: unknown entity %q", i, step.ViaEntity)
		}
		rows, err := lf(sysCtx, buildSearch(step.ViaWhere, env))
		if err != nil {
			return "", nil, fmt.Errorf("chain step %d list %q: %w", i, step.ViaEntity, err)
		}
		ids = ids[:0]
		for _, row := range rows {
			val := row[step.ViaSelect]
			if val == nil {
				continue
			}
			s := fmt.Sprint(val)
			if s == "" || s == "0" {
				continue
			}
			ids = append(ids, s)
		}
		env["prev_ids"] = strings.Join(ids, ",")
		if step.LocalField != "" {
			localField = step.LocalField
		}
	}
	return localField, ids, nil
}

// emptyViewer is the fallback when no extractor is registered or ctx has no
// principal — gives expr-lang a non-nil map to traverse so ` + "`viewer.id`" + ` etc.
// don't panic. Empty strings won't satisfy any identity-based rule.
var emptyViewer = map[string]any{"id": "", "role": "", "email": ""}

func (e *Engine) viewerFor(ctx context.Context) map[string]any {
	if e.viewer == nil {
		return emptyViewer
	}
	v := e.viewer(ctx)
	if v == nil {
		return emptyViewer
	}
	return v
}

// RuleError is returned when a rule's condition evaluates false — i.e. the
// mutation is business-invalid (vs. an infrastructure error).
type RuleError struct {
	Rule    string
	Message string
}

func (e *RuleError) Error() string { return e.Message }

// Check runs every enabled rule for operation against the request map.
// reqFilters is the triggering Update/Delete request's own Filters (nil for
// Create) — fetch steps with UseRequestFilters load exactly those rows.
// Returns nil when all pass (or no rules exist), a *RuleError on the first
// rule whose condition is false, or a plain error on infrastructure failure.
func (e *Engine) Check(ctx context.Context, operation string, reqMap map[string]any, reqFilters []*commonpb.FilterCriteria) error {
	return e.evalRules(ctx, e.rules.ForOperation(operation), reqMap, reqFilters)
}

// evalRules is the rule loop, split out so tests can drive it with a
// hand-built rule slice instead of a live Mongo-backed RuleStore.
func (e *Engine) evalRules(ctx context.Context, rules []Rule, reqMap map[string]any, reqFilters []*commonpb.FilterCriteria) error {
	if len(rules) == 0 {
		return nil
	}
	now := time.Now().UTC().Format(time.RFC3339)
	// Rule fetch bypass RLS — rule cần "raw" view, không phụ thuộc viewer scope.
	sysCtx := WithSystemContext(ctx)

	for _, r := range rules {
		// Each rule gets a fresh env: the request, the clock, and whatever
		// its own fetch steps produce.
		env := map[string]any{"req": reqMap, "now": now, "viewer": e.viewerFor(ctx)}

		for _, fs := range r.Fetch {
			lf, ok := e.registry[fs.Entity]
			if !ok {
				return fmt.Errorf("rule %q: unknown entity %q", r.Rule, fs.Entity)
			}
			search := buildSearch(fs.Where, env)
			if fs.UseRequestFilters {
				// Load the exact row(s) the Update/Delete targets — prepend
				// the request's own filters to this fetch.
				search.Filters = append(append([]*commonpb.FilterCriteria{}, reqFilters...), search.Filters...)
			}
			rows, err := lf(sysCtx, search)
			if err != nil {
				return fmt.Errorf("rule %q fetch %q: %w", r.Rule, fs.As, err)
			}
			env[fs.As] = rows
		}

		ok, err := evalCondition(r.Condition, env)
		if err != nil {
			return fmt.Errorf("rule %q condition: %w", r.Rule, err)
		}
		if !ok {
			msg := r.Message
			if msg == "" {
				msg = "business rule " + r.Rule + " denied the request"
			}
			return &RuleError{Rule: r.Rule, Message: msg}
		}
	}
	return nil
}

// minutesSinceOpt exposes minutesSince(rfc3339) to rule/action expressions —
// minutes elapsed since an RFC3339 timestamp. Lets a rule enforce a duration
// or deadline (e.g. an exam attempt's time limit) without baking time math
// into Go.
func minutesSinceOpt() expr.Option {
	return expr.Function("minutesSince", func(args ...any) (any, error) {
		if len(args) != 1 {
			return 0.0, fmt.Errorf("minutesSince(rfc3339) needs 1 arg")
		}
		s, _ := args[0].(string)
		t, err := time.Parse(time.RFC3339, s)
		if err != nil {
			return 0.0, nil
		}
		return time.Since(t).Minutes(), nil
	})
}

// evalCondition compiles + runs an expr-lang boolean expression. Empty or
// "true" always passes; "false" always fails.
func evalCondition(condition string, env map[string]any) (bool, error) {
	condition = strings.TrimSpace(condition)
	switch condition {
	case "", "true":
		return true, nil
	case "false":
		return false, nil
	}
	program, err := expr.Compile(condition, expr.AsBool(), expr.Env(env),
		expr.AllowUndefinedVariables(), minutesSinceOpt())
	if err != nil {
		return false, fmt.Errorf("compile %q: %w", condition, err)
	}
	out, err := expr.Run(program, env)
	if err != nil {
		return false, fmt.Errorf("run %q: %w", condition, err)
	}
	b, _ := out.(bool)
	return b, nil
}

// buildSearch turns a rule's declarative WHERE tree into a
// common.SearchRequest. Top-level entries are AND-ed (SearchRequest.Filters
// semantics); each entry recurses through buildCriteria so nested AND/OR
// groups round-trip into common.FilterGroup.
func buildSearch(where []Criteria, env map[string]any) *commonpb.SearchRequest {
	crits := make([]*commonpb.FilterCriteria, 0, len(where))
	for _, c := range where {
		crits = append(crits, buildCriteria(c, env))
	}
	return &commonpb.SearchRequest{Filters: crits}
}

// buildCriteria compiles one Criteria node — leaf condition or logical
// group — into a proto FilterCriteria, recursing into nested groups.
func buildCriteria(c Criteria, env map[string]any) *commonpb.FilterCriteria {
	if c.Logic != "" {
		sub := make([]*commonpb.FilterCriteria, 0, len(c.Group))
		for _, g := range c.Group {
			sub = append(sub, buildCriteria(g, env))
		}
		return &commonpb.FilterCriteria{
			Criteria: &commonpb.FilterCriteria_Group{
				Group: &commonpb.FilterGroup{
					Logic:   logicalFromString(c.Logic),
					Filters: sub,
				},
			},
		}
	}
	return &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{
			Condition: &commonpb.FilterCondition{
				Field:    c.Field,
				Operator: operatorFromString(c.Op),
				Values:   resolveValues(c.Value, env),
			},
		},
	}
}

// logicalFromString maps a group's logic string to the proto enum,
// defaulting to AND.
func logicalFromString(logic string) commonpb.LogicalCondition {
	if v, ok := commonpb.LogicalCondition_value[strings.ToUpper(strings.TrimSpace(logic))]; ok {
		return commonpb.LogicalCondition(v)
	}
	return commonpb.LogicalCondition_AND
}

// resolveValues turns a filter Value into the []string the proto expects.
// For IN / NOT_IN a comma-separated literal becomes multiple values.
func resolveValues(raw string, env map[string]any) []string {
	v := resolveRef(raw, env)
	if strings.Contains(v, ",") {
		parts := strings.Split(v, ",")
		for i := range parts {
			parts[i] = strings.TrimSpace(parts[i])
		}
		return parts
	}
	return []string{v}
}

// resolveRef resolves a filter value. A leading $ marks a reference:
//   $now                      current RFC3339 time
//   $req.<field>              request field
//   $<fetchAs>.<idx>.<field>  earlier fetch row field
// Anything else is a literal. An unresolvable reference yields "" — the
// resulting query simply matches nothing, which rules can test with len().
func resolveRef(raw string, env map[string]any) string {
	if !strings.HasPrefix(raw, "$") {
		return raw
	}
	path := strings.Split(strings.TrimPrefix(raw, "$"), ".")
	if path[0] == "now" {
		if s, ok := env["now"].(string); ok {
			return s
		}
		return ""
	}
	cur := env[path[0]]
	for _, seg := range path[1:] {
		switch c := cur.(type) {
		case map[string]any:
			cur = c[seg]
		case []map[string]any:
			i, err := strconv.Atoi(seg)
			if err != nil || i < 0 || i >= len(c) {
				return ""
			}
			cur = c[i]
		case []any:
			i, err := strconv.Atoi(seg)
			if err != nil || i < 0 || i >= len(c) {
				return ""
			}
			cur = c[i]
		default:
			return ""
		}
	}
	if cur == nil {
		return ""
	}
	return fmt.Sprint(cur)
}

// operatorFromString maps a rule's op string to the proto enum, defaulting
// to EQUAL for anything unrecognised.
func operatorFromString(op string) commonpb.FilterOperator {
	if v, ok := commonpb.FilterOperator_value[strings.ToUpper(strings.TrimSpace(op))]; ok {
		return commonpb.FilterOperator(v)
	}
	return commonpb.FilterOperator_EQUAL
}
`

const domainInterceptorGo = `
// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"encoding/json"
	"log"
	"reflect"
	"strings"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	commonpb "MODULE_PATH/proto/common"
)

// UnaryInterceptor returns a gRPC client interceptor that runs business rules
// before every Create/Update/Delete call the gateway makes.
//
// getEngine is an indirection: the engine needs the gRPC clients, the clients
// are dialed with this interceptor — so main.go builds the interceptor first
// and the closure returns the engine once it exists.
//
// Failure policy: a rule whose condition is false -> FailedPrecondition (the
// mutation is business-invalid). An engine/infra error (Mongo down, bad rule)
// -> fail OPEN with a loud log, so a broken rule store can't wedge every
// write. That is the opposite of the authz enforcer, which fails closed:
// authz protects data exposure, business rules protect data integrity, and a
// dead rule engine blocking all writes is worse than the alternative here.
func UnaryInterceptor(getEngine func() *Engine) grpc.UnaryClientInterceptor {
	return func(
		ctx context.Context, method string, req, reply any,
		cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption,
	) error {
		op := method[strings.LastIndex(method, "/")+1:]
		// List op: AND-prepend RLS scope filters via ScopeFiltersFor.
		if strings.HasPrefix(op, "List") {
			if eng := getEngine(); eng != nil {
				entity := strings.TrimPrefix(op, "List")
				if extra := eng.ScopeFiltersFor(ctx, entity); len(extra) > 0 {
					injectScopeFilters(req, extra)
				}
			}
			return invoker(ctx, method, req, reply, cc, opts...)
		}
		if !isMutation(op) {
			return invoker(ctx, method, req, reply, cc, opts...)
		}
		eng := getEngine()
		if eng == nil {
			return invoker(ctx, method, req, reply, cc, opts...)
		}
		switch err := eng.Check(ctx, op, messageToMap(req), extractFilters(req)).(type) {
		case nil:
			return invoker(ctx, method, req, reply, cc, opts...)
		case *RuleError:
			return status.Error(codes.FailedPrecondition, err.Message)
		default:
			log.Printf("business-rule engine error on %s: %v (allowing call)", op, err)
			return invoker(ctx, method, req, reply, cc, opts...)
		}
	}
}

// injectScopeFilters AND-prepends RLS filters into a List request's
// Search.Filters via reflection. Works on any auto-generated
// ListXxxRequest{ Search *SearchRequest }.
func injectScopeFilters(req any, extra []*commonpb.FilterCriteria) {
	rv := reflect.ValueOf(req)
	for rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return
		}
		rv = rv.Elem()
	}
	if rv.Kind() != reflect.Struct {
		return
	}
	sf := rv.FieldByName("Search")
	if !sf.IsValid() {
		return
	}
	if sf.Kind() == reflect.Pointer && sf.IsNil() {
		if !sf.CanSet() {
			return
		}
		sf.Set(reflect.New(sf.Type().Elem()))
	}
	sr, ok := sf.Interface().(*commonpb.SearchRequest)
	if !ok || sr == nil {
		return
	}
	sr.Filters = append(append([]*commonpb.FilterCriteria{}, extra...), sr.Filters...)
}

// extractFilters pulls the Filters field off an Update/Delete request via
// reflection — those requests are filter-based, so their Filters identify
// the exact rows the mutation targets. Create requests have no Filters and
// yield nil.
func extractFilters(req any) []*commonpb.FilterCriteria {
	rv := reflect.ValueOf(req)
	for rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return nil
		}
		rv = rv.Elem()
	}
	if rv.Kind() != reflect.Struct {
		return nil
	}
	f := rv.FieldByName("Filters")
	if !f.IsValid() {
		return nil
	}
	if fc, ok := f.Interface().([]*commonpb.FilterCriteria); ok {
		return fc
	}
	return nil
}

// isMutation reports whether the gRPC method is a write the rules guard.
func isMutation(op string) bool {
	return strings.HasPrefix(op, "Create") ||
		strings.HasPrefix(op, "Update") ||
		strings.HasPrefix(op, "Delete")
}

// messageToMap renders a proto request as a map keyed by proto field names,
// so rule filter references ($req.exam_id) resolve.
func messageToMap(req any) map[string]any {
	m, ok := req.(proto.Message)
	if !ok {
		return map[string]any{}
	}
	b, err := protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: true}.Marshal(m)
	if err != nil {
		return map[string]any{}
	}
	var out map[string]any
	if json.Unmarshal(b, &out) != nil {
		return map[string]any{}
	}
	return out
}
`

// domainEngineTestGo: ~BT~ is replaced with a backtick by GenerateDomain.
const domainEngineTestGo = `
// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"testing"

	commonpb "MODULE_PATH/proto/common"
)

func TestResolveRef(t *testing.T) {
	env := map[string]any{
		"req":        map[string]any{"exam_id": "1", "student_id": "3"},
		"now":        "2026-05-21T10:00:00Z",
		"assignment": []map[string]any{{"class_id": "3", "max_attempts": float64(2)}},
	}
	cases := []struct{ in, want string }{
		{"$req.exam_id", "1"},
		{"$req.student_id", "3"},
		{"$now", "2026-05-21T10:00:00Z"},
		{"$assignment.0.class_id", "3"},
		{"$assignment.0.max_attempts", "2"},
		{"$assignment.5.class_id", ""},
		{"$missing.0.x", ""},
		{"$req.nope", ""},
		{"literal", "literal"},
		{"42", "42"},
	}
	for _, c := range cases {
		if got := resolveRef(c.in, env); got != c.want {
			t.Errorf("resolveRef(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestOperatorFromString(t *testing.T) {
	cases := map[string]commonpb.FilterOperator{
		"EQUAL":        commonpb.FilterOperator_EQUAL,
		"equal":        commonpb.FilterOperator_EQUAL,
		" IN ":         commonpb.FilterOperator_IN,
		"GREATER_THAN": commonpb.FilterOperator_GREATER_THAN,
		"bogus":        commonpb.FilterOperator_EQUAL,
	}
	for in, want := range cases {
		if got := operatorFromString(in); got != want {
			t.Errorf("operatorFromString(%q) = %v, want %v", in, got, want)
		}
	}
}

func TestEvalCondition(t *testing.T) {
	env := map[string]any{
		"enroll": []map[string]any{{"id": "1"}},
		"empty":  []map[string]any{},
		"now":    "2026-05-21T10:00:00Z",
		"max":    float64(2),
	}
	cases := []struct {
		cond string
		want bool
	}{
		{"", true},
		{"true", true},
		{"false", false},
		{"len(enroll) > 0", true},
		{"len(empty) > 0", false},
		{"len(empty) == 0", true},
		{"len(empty) < int(max)", true},
		{~BT~now >= "2026-01-01T00:00:00Z"~BT~, true},
		{~BT~now <= "2026-01-01T00:00:00Z"~BT~, false},
		{~BT~len(enroll) > 0 && now <= "2026-12-31T00:00:00Z"~BT~, true},
	}
	for _, c := range cases {
		got, err := evalCondition(c.cond, env)
		if err != nil {
			t.Errorf("evalCondition(%q) error: %v", c.cond, err)
			continue
		}
		if got != c.want {
			t.Errorf("evalCondition(%q) = %v, want %v", c.cond, got, c.want)
		}
	}
}

func TestEvalConditionBadExpr(t *testing.T) {
	if _, err := evalCondition("len(", map[string]any{}); err == nil {
		t.Error("expected a compile error for a malformed expression")
	}
}

func TestBuildSearch(t *testing.T) {
	env := map[string]any{
		"req":        map[string]any{"exam_id": "7", "status": "ACTIVE"},
		"assignment": []map[string]any{{"class_id": "9"}},
	}
	where := []Criteria{
		{Field: "exam_id", Op: "EQUAL", Value: "$req.exam_id"},
		{Logic: "OR", Group: []Criteria{
			{Field: "class_id", Op: "EQUAL", Value: "$assignment.0.class_id"},
			{Field: "status", Op: "EQUAL", Value: "$req.status"},
		}},
	}
	s := buildSearch(where, env)
	if len(s.GetFilters()) != 2 {
		t.Fatalf("want 2 top-level filters, got %d", len(s.GetFilters()))
	}
	// leaf condition
	c0 := s.GetFilters()[0].GetCondition()
	if c0.GetField() != "exam_id" || c0.GetValues()[0] != "7" {
		t.Errorf("filter0 = %q / %v", c0.GetField(), c0.GetValues())
	}
	// nested OR group
	g := s.GetFilters()[1].GetGroup()
	if g == nil {
		t.Fatal("filter1 should be a group, not a condition")
	}
	if g.GetLogic() != commonpb.LogicalCondition_OR {
		t.Errorf("group logic = %v, want OR", g.GetLogic())
	}
	if len(g.GetFilters()) != 2 {
		t.Fatalf("group should have 2 filters, got %d", len(g.GetFilters()))
	}
	if g.GetFilters()[0].GetCondition().GetValues()[0] != "9" {
		t.Errorf("group filter0 value = %v, want [9] (resolved $assignment.0.class_id)",
			g.GetFilters()[0].GetCondition().GetValues())
	}
}

// TestEvalRules drives the rule loop with a fake registry — no Mongo, no gRPC.
func TestEvalRules(t *testing.T) {
	reg := map[string]ListFunc{
		"ExamAssignment": func(_ context.Context, _ *commonpb.SearchRequest) ([]map[string]any, error) {
			return []map[string]any{{"class_id": "3", "max_attempts": float64(2)}}, nil
		},
		"Enrollment": func(_ context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			vals := map[string]string{}
			for _, f := range s.GetFilters() {
				c := f.GetCondition()
				if len(c.GetValues()) > 0 {
					vals[c.GetField()] = c.GetValues()[0]
				}
			}
			if vals["student_id"] == "3" && vals["class_id"] == "3" {
				return []map[string]any{{"id": "1"}}, nil
			}
			return nil, nil
		},
	}
	eng := &Engine{registry: reg}

	mustEnrolled := []Rule{{
		Operation: "CreateExamAttempt", Rule: "must_be_enrolled", Enabled: true,
		Fetch: []FetchStep{
			{As: "assignment", Entity: "ExamAssignment",
				Where: []Criteria{{Field: "exam_id", Op: "EQUAL", Value: "$req.exam_id"}}},
			{As: "enroll", Entity: "Enrollment", Where: []Criteria{
				{Field: "student_id", Op: "EQUAL", Value: "$req.student_id"},
				{Field: "class_id", Op: "EQUAL", Value: "$assignment.0.class_id"},
			}},
		},
		Condition: "len(enroll) > 0",
		Message:   "not enrolled",
	}}

	if err := eng.evalRules(context.Background(), mustEnrolled,
		map[string]any{"exam_id": "1", "student_id": "3"}, nil); err != nil {
		t.Errorf("enrolled student should pass, got %v", err)
	}

	err := eng.evalRules(context.Background(), mustEnrolled,
		map[string]any{"exam_id": "1", "student_id": "9"}, nil)
	re, ok := err.(*RuleError)
	if !ok || re.Message != "not enrolled" {
		t.Errorf("non-enrolled should be *RuleError 'not enrolled', got %v (%T)", err, err)
	}

	if err := eng.evalRules(context.Background(), nil, nil, nil); err != nil {
		t.Errorf("no rules should pass, got %v", err)
	}

	bad := []Rule{{
		Rule: "x", Enabled: true,
		Fetch:     []FetchStep{{As: "z", Entity: "DoesNotExist"}},
		Condition: "true",
	}}
	err = eng.evalRules(context.Background(), bad, map[string]any{}, nil)
	if err == nil {
		t.Fatal("unknown entity should error")
	}
	if _, isRule := err.(*RuleError); isRule {
		t.Error("unknown entity must be an infra error, not a *RuleError")
	}
}

// TestEvalRulesUseRequestFilters proves a fetch step with UseRequestFilters
// receives the triggering request's own filters — the basis for Update /
// Delete (state-transition, delete-dependency) rules.
func TestEvalRulesUseRequestFilters(t *testing.T) {
	var got *commonpb.SearchRequest
	reg := map[string]ListFunc{
		"ExamAttempt": func(_ context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			got = s
			return []map[string]any{{"status": "IN_PROGRESS"}}, nil
		},
	}
	eng := &Engine{registry: reg}
	rule := []Rule{{
		Rule: "state", Enabled: true,
		Fetch:     []FetchStep{{As: "current", Entity: "ExamAttempt", UseRequestFilters: true}},
		Condition: ~BT~current[0].status == "IN_PROGRESS"~BT~,
	}}
	reqFilters := []*commonpb.FilterCriteria{{
		Criteria: &commonpb.FilterCriteria_Condition{
			Condition: &commonpb.FilterCondition{
				Field: "id", Operator: commonpb.FilterOperator_EQUAL, Values: []string{"5"},
			},
		},
	}}
	if err := eng.evalRules(context.Background(), rule, map[string]any{}, reqFilters); err != nil {
		t.Errorf("rule should pass, got %v", err)
	}
	if got == nil || len(got.GetFilters()) != 1 {
		t.Fatalf("fetch should receive the request's 1 filter, got %v", got)
	}
	if got.GetFilters()[0].GetCondition().GetValues()[0] != "5" {
		t.Errorf("request filter not forwarded into the fetch: %v", got.GetFilters())
	}
}
`

const domainActionGo = `
// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"
	"sync"
	"time"

	"github.com/expr-lang/expr"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"golang.org/x/crypto/bcrypt"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	"MODULE_PATH/src/server/graph/client"
)

// Step is one step of an Action. Kind selects the behaviour:
//   fetch   — load rows of Entity filtered by Where, bind to env[As]
//   compute — evaluate Expr (expr-lang), bind the result to env[As]
//   write   — call mutation Op; Where = filters (Update/Delete), Set = fields
type Step struct {
	Kind   string
	As     string
	Entity string
	Where  []Criteria
	Expr   string
	Op     string
	Set    map[string]string
}

// Action is a custom multi-step operation stored in MongoDB. Output is an
// optional expr-lang expression producing the result map.
//
// Triggers: when non-empty, action auto-runs AFTER each listed mutation op
// succeeds (via TriggerInterceptor). Triggering request's protojson becomes
// $input.* in the action env.
type Action struct {
	Name     string
	Triggers []string
	Steps    []Step
	Output   string
}

// ActionsForTrigger returns every action whose Triggers list contains op.
// Used by TriggerInterceptor to auto-run actions after a matching write.
func (s *ActionStore) ActionsForTrigger(op string) []Action {
	s.mu.RLock()
	defer s.mu.RUnlock()
	var out []Action
	for _, a := range s.byName {
		for _, t := range a.Triggers {
			if t == op {
				out = append(out, a)
				break
			}
		}
	}
	return out
}

// Store exposes the underlying ActionStore so callers (interceptor) can look
// up triggered actions.
func (a *ActionEngine) Store() *ActionStore { return a.store }

// ActionStore loads actions from MongoDB.
type ActionStore struct {
	coll   *mongo.Collection
	mu     sync.RWMutex
	byName map[string]Action
}

// NewActionStore connects to Mongo and does the initial load.
func NewActionStore(ctx context.Context, mongoURI, db, collection string) (*ActionStore, error) {
	cl, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		return nil, fmt.Errorf("mongo connect: %w", err)
	}
	pctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := cl.Ping(pctx, nil); err != nil {
		return nil, fmt.Errorf("mongo ping: %w", err)
	}
	s := &ActionStore{coll: cl.Database(db).Collection(collection), byName: map[string]Action{}}
	if err := s.Reload(ctx); err != nil {
		return nil, err
	}
	return s, nil
}

// Reload re-reads every action from Mongo.
func (s *ActionStore) Reload(ctx context.Context) error {
	cur, err := s.coll.Find(ctx, bson.M{})
	if err != nil {
		return fmt.Errorf("action find: %w", err)
	}
	var acts []Action
	if err := cur.All(ctx, &acts); err != nil {
		return fmt.Errorf("action decode: %w", err)
	}
	idx := map[string]Action{}
	for _, a := range acts {
		idx[a.Name] = a
	}
	s.mu.Lock()
	s.byName = idx
	s.mu.Unlock()
	return nil
}

// Get returns the named action.
func (s *ActionStore) Get(name string) (Action, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	a, ok := s.byName[name]
	return a, ok
}

// Count is the number of loaded actions.
func (s *ActionStore) Count() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.byName)
}

// ActionEngine runs Actions — a declarative fetch/compute/write pipeline.
// Everything an action does is data (the Action document); this is the
// generic interpreter.
type ActionEngine struct {
	store    *ActionStore
	registry map[string]ListFunc
	clients  *client.Clients
}

// NewActionEngine binds the action store to the entity registry + clients.
func NewActionEngine(store *ActionStore, registry map[string]ListFunc, clients *client.Clients) *ActionEngine {
	return &ActionEngine{store: store, registry: registry, clients: clients}
}

// Run executes the named action. input is the caller-supplied argument map,
// referenced in steps as $input.<key>. Returns the action's Output map (or
// {ok:true} when no Output expr is set).
func (a *ActionEngine) Run(ctx context.Context, name string, input map[string]any) (map[string]any, error) {
	act, ok := a.store.Get(name)
	if !ok {
		return nil, fmt.Errorf("unknown action %q", name)
	}
	env := map[string]any{"input": input, "now": time.Now().UTC().Format(time.RFC3339)}

	for i, st := range act.Steps {
		switch st.Kind {
		case "fetch":
			lf, ok := a.registry[st.Entity]
			if !ok {
				return nil, fmt.Errorf("action %q step %d: unknown entity %q", name, i, st.Entity)
			}
			// Action fetch bypass RLS — action runs as system, not as viewer.
			rows, err := lf(WithSystemContext(ctx), buildSearch(st.Where, env))
			if err != nil {
				return nil, fmt.Errorf("action %q step %d fetch: %w", name, i, err)
			}
			env[st.As] = rows
		case "compute":
			v, err := evalExpr(st.Expr, env)
			if err != nil {
				return nil, fmt.Errorf("action %q step %d compute: %w", name, i, err)
			}
			env[st.As] = v
		case "write":
			reqJSON, err := buildWriteJSON(st, env)
			if err != nil {
				return nil, fmt.Errorf("action %q step %d write: %w", name, i, err)
			}
			resp, err := mutate(ctx, a.clients, st.Op, reqJSON)
			if err != nil {
				return nil, fmt.Errorf("action %q step %d %s: %w", name, i, st.Op, err)
			}
			if st.As != "" {
				env[st.As] = resp
			}
		default:
			return nil, fmt.Errorf("action %q step %d: unknown kind %q", name, i, st.Kind)
		}
	}

	if act.Output != "" {
		out, err := evalExpr(act.Output, env)
		if err != nil {
			return nil, fmt.Errorf("action %q output: %w", name, err)
		}
		if m, ok := out.(map[string]any); ok {
			return m, nil
		}
		return map[string]any{"result": out}, nil
	}
	return map[string]any{"ok": true}, nil
}

// evalExpr runs an expr-lang expression returning any value. verifyPassword
// is exposed as a primitive so login-style actions can check a bcrypt hash
// without baking crypto into a document.
func evalExpr(code string, env map[string]any) (any, error) {
	program, err := expr.Compile(code, expr.Env(env), expr.AllowUndefinedVariables(),
		expr.Function("verifyPassword", func(args ...any) (any, error) {
			if len(args) != 2 {
				return false, fmt.Errorf("verifyPassword(hash, plain) needs 2 args")
			}
			hash, _ := args[0].(string)
			plain, _ := args[1].(string)
			return bcrypt.CompareHashAndPassword([]byte(hash), []byte(plain)) == nil, nil
		}),
		minutesSinceOpt())
	if err != nil {
		return nil, fmt.Errorf("compile %q: %w", code, err)
	}
	return expr.Run(program, env)
}

// buildWriteJSON assembles the protojson body of a write step: Where becomes
// the request's "filters", Set becomes the field values (refs resolved,
// types preserved).
func buildWriteJSON(st Step, env map[string]any) ([]byte, error) {
	obj := map[string]any{}
	if len(st.Where) > 0 {
		raws := make([]json.RawMessage, 0, len(st.Where))
		for _, c := range st.Where {
			b, err := protojson.Marshal(buildCriteria(c, env))
			if err != nil {
				return nil, err
			}
			raws = append(raws, b)
		}
		obj["filters"] = raws
	}
	for field, ref := range st.Set {
		obj[field] = resolveAny(ref, env)
	}
	return json.Marshal(obj)
}

// resolveAny is resolveRef but type-preserving — a computed number stays a
// number in the write payload instead of being stringified.
func resolveAny(raw string, env map[string]any) any {
	if len(raw) == 0 || raw[0] != '$' {
		return raw
	}
	parts := splitDots(raw[1:])
	if parts[0] == "now" {
		return env["now"]
	}
	var cur any = env[parts[0]]
	for _, seg := range parts[1:] {
		switch c := cur.(type) {
		case map[string]any:
			cur = c[seg]
		case []map[string]any:
			idx := atoiSafe(seg)
			if idx < 0 || idx >= len(c) {
				return nil
			}
			cur = c[idx]
		case []any:
			idx := atoiSafe(seg)
			if idx < 0 || idx >= len(c) {
				return nil
			}
			cur = c[idx]
		default:
			return nil
		}
	}
	return cur
}

// mutate dispatches a gRPC mutation by RPC name via reflection on the client
// wrappers — so the action engine can call any Create/Update/Delete without
// per-operation Go code. The reqJSON is protojson-unmarshalled into the
// correct request type.
func mutate(ctx context.Context, c *client.Clients, op string, reqJSON []byte) (map[string]any, error) {
	field, ok := opClientField[op]
	if !ok {
		return nil, fmt.Errorf("unknown mutation %q", op)
	}
	cv := reflect.ValueOf(c).Elem().FieldByName(field)
	if !cv.IsValid() || cv.IsNil() {
		return nil, fmt.Errorf("client %q not available", field)
	}
	m := cv.MethodByName(op)
	if !m.IsValid() {
		return nil, fmt.Errorf("%q has no method %q", field, op)
	}
	inT := m.Type().In(1) // *pb.<Op>Request
	reqMsg, ok := reflect.New(inT.Elem()).Interface().(proto.Message)
	if !ok {
		return nil, fmt.Errorf("%s: request type is not a proto.Message", op)
	}
	if err := protojson.Unmarshal(reqJSON, reqMsg); err != nil {
		return nil, fmt.Errorf("build %s request: %w", op, err)
	}
	rets := m.Call([]reflect.Value{reflect.ValueOf(ctx), reflect.ValueOf(reqMsg)})
	if e := rets[1]; !e.IsNil() {
		return nil, e.Interface().(error)
	}
	out := map[string]any{}
	if respMsg, ok := rets[0].Interface().(proto.Message); ok && respMsg != nil {
		if b, err := (protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: true}).Marshal(respMsg); err == nil {
			_ = json.Unmarshal(b, &out)
		}
	}
	return out, nil
}

func splitDots(s string) []string {
	out := []string{}
	cur := ""
	for _, r := range s {
		if r == '.' {
			out = append(out, cur)
			cur = ""
		} else {
			cur += string(r)
		}
	}
	return append(out, cur)
}

func atoiSafe(s string) int {
	n := 0
	for _, r := range s {
		if r < '0' || r > '9' {
			return -1
		}
		n = n*10 + int(r-'0')
	}
	if s == "" {
		return -1
	}
	return n
}
`

// domainSystemContextGo — marker để wrap ctx khi engine làm internal fetch
// (rule, action, scope chain), bypass RLS để tránh recursion + false-deny.
const domainSystemContextGo = `
// Code generated by grpc-gen. DO NOT EDIT.

package domain

import "context"

type systemCtxKey struct{}

// WithSystemContext returns a child context flagged as engine-internal.
func WithSystemContext(ctx context.Context) context.Context {
	return context.WithValue(ctx, systemCtxKey{}, true)
}

// IsSystemContext reports whether ctx came from an engine-internal call.
func IsSystemContext(ctx context.Context) bool {
	v, _ := ctx.Value(systemCtxKey{}).(bool)
	return v
}
`

// domainTriggersGo — interceptor cuối chain, sau khi mutation success thì
// fan-out các action có Triggers chứa op name. Failure log loud, không
// propagate (mutation đã commit downstream).
const domainTriggersGo = `
// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"log"
	"strings"

	"google.golang.org/grpc"
)

// TriggerInterceptor runs actions registered with Triggers: [<op>] after a
// matching write succeeds. getActionEngine is closure-deferred for the same
// reason as UnaryInterceptor — the engine needs clients that themselves
// route through this interceptor.
func TriggerInterceptor(getActionEngine func() *ActionEngine) grpc.UnaryClientInterceptor {
	return func(
		ctx context.Context, method string, req, reply any,
		cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption,
	) error {
		err := invoker(ctx, method, req, reply, cc, opts...)
		if err != nil {
			return err
		}
		op := method[strings.LastIndex(method, "/")+1:]
		if !isMutation(op) {
			return nil
		}
		ae := getActionEngine()
		if ae == nil {
			return nil
		}
		acts := ae.Store().ActionsForTrigger(op)
		if len(acts) == 0 {
			return nil
		}
		input := mergeTriggerInput(messageToMap(req), messageToMap(reply))
		sysCtx := WithSystemContext(ctx)
		for _, a := range acts {
			if _, runErr := ae.Run(sysCtx, a.Name, input); runErr != nil {
				log.Printf("trigger %q on %s: %v (mutation already committed)", a.Name, op, runErr)
			}
		}
		return nil
	}
}

// mergeTriggerInput collapses request + response. Request fields take
// precedence; response fields fall through so output IDs are referenceable.
func mergeTriggerInput(req, resp map[string]any) map[string]any {
	out := map[string]any{}
	for k, v := range resp {
		out[k] = v
	}
	for k, v := range req {
		out[k] = v
	}
	return out
}
`
