package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// GqlgenGenInput holds parameters for writing gqlgen.yml.
type GqlgenGenInput struct {
	ServerDir  string // e.g. "src/server"
	ModulePath string // user go module, e.g. "github.com/thaily/lms"
}

// GenerateGqlgenConfig writes src/server/gqlgen.yml + a stub Resolver struct
// + tools.go pinning gqlgen as a tool dependency. After this, running
// `go run github.com/99designs/gqlgen generate` inside ServerDir produces the
// generated.go + models_gen.go.
func GenerateGqlgenConfig(in GqlgenGenInput) error {
	if err := os.MkdirAll(in.ServerDir, 0755); err != nil {
		return err
	}

	// 1. gqlgen.yml
	yml := strings.TrimLeft(`
# Code generated by grpc-gen. Regenerated each "add-gateway" run.
# Schema source-of-truth: graph/schema/*.graphqls (DO NOT EDIT — see grpc-gen).
schema:
  - graph/schema/*.graphqls

exec:
  filename: graph/generated/generated.go
  package: generated

model:
  filename: graph/model/models_gen.go
  package: model

resolver:
  layout: follow-schema
  dir: graph/resolver
  package: resolver
  filename_template: "{name}.resolvers.go"

autobind:
  - "`+in.ModulePath+`/src/server/graph/model"

# @goField is purely a code-gen hint (forceResolver); the runners @auth and
# @policy are handled at runtime so they need no entry here.
directives:
  goField:
    skip_runtime: true

# GraphQL → Go type bindings. ID covers all integer id fields from our protos.
models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int32
      - github.com/99designs/gqlgen/graphql.Int64
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int
      - github.com/99designs/gqlgen/graphql.Int32
      - github.com/99designs/gqlgen/graphql.Int64
  Time:
    model:
      - github.com/99designs/gqlgen/graphql.Time
  JSON:
    model:
      - github.com/99designs/gqlgen/graphql.Map
`, "\n")
	if err := os.WriteFile(filepath.Join(in.ServerDir, "gqlgen.yml"), []byte(yml), 0644); err != nil {
		return err
	}

	// 2. tools.go — pins gqlgen as a tool dep so `go mod tidy` doesn't remove it.
	tools := `//go:build tools

// Pin the gqlgen build tool so that ` + "`go mod tidy`" + ` keeps it as a dep.
// Run ` + "`go run github.com/99designs/gqlgen generate`" + ` from this dir to
// (re)generate graph/generated and graph/model after editing the schema.

package tools

import (
	_ "github.com/99designs/gqlgen"
	_ "github.com/99designs/gqlgen/graphql/introspection"
)
`
	if err := os.WriteFile(filepath.Join(in.ServerDir, "tools.go"), []byte(tools), 0644); err != nil {
		return err
	}

	// 3. resolver.go — minimal scaffold so gqlgen can compile during its first
	// generate pass. Phase 6 (`grpc-gen add-gateway`) overwrites this file
	// with the full Resolver + entity sub-resolver wiring once gqlgen has
	// produced the generated.<Entity>Resolver interfaces.
	// resolver.go owns ONLY the Resolver struct. Everything else
	// (Mutation/Query methods, the matching resolver types, Empty stubs, and
	// per-entity sub-resolver wiring) belongs to schema-matching files —
	// gqlgen generates them in common.resolvers.go + <service>.resolvers.go,
	// and Phase 6 of grpc-gen overwrites them with real bodies.
	stub := strings.TrimLeft(fmt.Sprintf(`
// Code generated by grpc-gen. DO NOT EDIT.
package resolver

import (
	"%[1]s/src/server/graph/client"
	"%[1]s/src/server/graph/domain"
)

// Resolver is the dependency holder injected into every gqlgen resolver.
// main.go wires Clients + Actions.
type Resolver struct {
	Clients *client.Clients
	Actions *domain.ActionEngine
}
`, in.ModulePath), "\n")

	resolverDir := filepath.Join(in.ServerDir, "graph", "resolver")
	if err := os.MkdirAll(resolverDir, 0755); err != nil {
		return err
	}
	// resolver.go is pure generated wiring (the dependency holder) — always
	// regenerate so new injected deps land.
	if err := os.WriteFile(filepath.Join(resolverDir, "resolver.go"), []byte(stub), 0644); err != nil {
		return err
	}

	// 4. Ensure model + generated dirs exist with a placeholder Go file so
	// gqlgen can resolve the import path before populating them.
	for _, sub := range []string{"graph/model", "graph/generated"} {
		dir := filepath.Join(in.ServerDir, sub)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
		pkgName := filepath.Base(sub) // model | generated
		placeholderPath := filepath.Join(dir, "doc.go")
		if _, err := os.Stat(placeholderPath); os.IsNotExist(err) {
			placeholder := fmt.Sprintf("// Package %s is populated by gqlgen.\npackage %s\n", pkgName, pkgName)
			if err := os.WriteFile(placeholderPath, []byte(placeholder), 0644); err != nil {
				return err
			}
		}
	}

	return nil
}

// PrintGqlgenNextSteps tells the caller how to actually run gqlgen.
func PrintGqlgenNextSteps(serverDir string) {
	fmt.Println()
	fmt.Println("📋 Next: run gqlgen to produce generated.go + models_gen.go")
	fmt.Println()
	fmt.Printf("   cd %s\n", serverDir)
	fmt.Println("   go get github.com/99designs/gqlgen@latest")
	fmt.Println("   go run github.com/99designs/gqlgen generate")
	fmt.Println()
	fmt.Println("   (or let `grpc-gen add-gateway --run-gqlgen` do it for you in the next phase)")
}
