package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// MainGenInput drives gen of src/server/main.go.
type MainGenInput struct {
	ServerDir  string
	ModulePath string
	Port       int
	Protos     []ProtoInfo
}

// GenerateMain writes src/server/main.go: wires the gqlgen server, HTTP
// middleware (recover, JWT → viewer, DataLoader, directive bindings),
// TLS dial options for gRPC clients, and the env-driven endpoint config.
// It also writes go.mod additions implicitly via `go mod tidy` (the caller
// runs that step).
func GenerateMain(in MainGenInput) error {
	if err := os.MkdirAll(in.ServerDir, 0755); err != nil {
		return err
	}

	// Stable list of services for endpoint env + dial loop.
	svcs := make([]string, 0, len(in.Protos))
	for _, p := range in.Protos {
		svcs = append(svcs, p.ServiceName)
	}
	sort.Strings(svcs)

	// Build per-service env name (USER_SERVICE_ADDR, CLASS_SERVICE_ADDR, ...).
	envFor := func(svc string) string {
		return strings.ToUpper(svc) + "_SERVICE_ADDR"
	}

	var endpointsBlock strings.Builder
	for _, s := range svcs {
		fmt.Fprintf(&endpointsBlock, "\t\t%s: env(%q, %q),\n",
			capitalize(s), envFor(s), "localhost:50051")
	}

	body := strings.TrimLeft(fmt.Sprintf(`
// Code generated by grpc-gen. Edit freely — re-running add-gateway WON'T
// clobber this file (it skips if already present). Treat as the project's
// own bootstrap; the generator just lays down a reasonable starting point.

package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/golang-jwt/jwt/v5"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"

	"%[1]s/src/server/graph/auth"
	"%[1]s/src/server/graph/cache"
	"%[1]s/src/server/graph/client"
	"%[1]s/src/server/graph/dataloader"
	"%[1]s/src/server/graph/directive"
	"%[1]s/src/server/graph/domain"
	"%[1]s/src/server/graph/generated"
	"%[1]s/src/server/graph/policy"
	"%[1]s/src/server/graph/resolver"
)

func main() {
	dialOpts, err := buildDialOpts()
	if err != nil {
		log.Fatalf("dial opts: %%v", err)
	}

	// Business-rule engine. The interceptor is appended to dialOpts BEFORE
	// the clients are dialed; the engine itself (which needs the clients) is
	// built afterwards and handed to the interceptor via the closure.
	ruleStore := buildRuleStore()
	actionStore := buildActionStore()
	var ruleEngine *domain.Engine
	if ruleStore != nil {
		dialOpts = append(dialOpts, grpc.WithChainUnaryInterceptor(
			domain.UnaryInterceptor(func() *domain.Engine { return ruleEngine })))
	}

	cacheBackend, cacheTTL := buildCache()
	clients, err := client.NewClients(client.Endpoints{
%[2]s	}, cacheBackend, cacheTTL, dialOpts...)
	if err != nil {
		log.Fatalf("client.NewClients: %%v", err)
	}
	defer clients.Close()

	registry := domain.NewRegistry(clients)
	if ruleStore != nil {
		ruleEngine = domain.NewEngine(ruleStore, registry)
		log.Printf("business rules: %%d operation(s) guarded", ruleStore.OperationCount())
	}
	var actionEngine *domain.ActionEngine
	if actionStore != nil {
		actionEngine = domain.NewActionEngine(actionStore, registry, clients)
		log.Printf("actions: %%d loaded", actionStore.Count())
	}

	// Enforcer: replace policy.DenyAll{} with a Casbin-backed impl wired to
	// the policy-engine MongoDB. DenyAll keeps the gateway safe-by-default
	// until that wiring is done.
	enforcer := policy.Enforcer(policy.DenyAll{})

	gqlCfg := generated.Config{
		Resolvers: &resolver.Resolver{Clients: clients, Actions: actionEngine},
		Directives: generated.DirectiveRoot{
			Auth:   directive.Auth,
			Policy: directive.Policy,
		},
	}

	// NewDefaultServer wires the standard POST/GET/multipart/websocket
	// transports — fine for production until we need something custom.
	srv := handler.NewDefaultServer(generated.NewExecutableSchema(gqlCfg))

	bindings := &directive.Bindings{Enforcer: enforcer}

	mux := http.NewServeMux()
	mux.Handle("/", playground.Handler("GraphQL playground", "/query"))
	mux.Handle("/query", chain(srv,
		recoverMW,
		viewerMW,
		dataloaderMW(clients),
		bindingsMW(bindings),
	))

	addr := env("GATEWAY_LISTEN", ":%[3]d")
	log.Printf("graphql gateway listening on %%s (playground at /)", addr)
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("listen: %%v", err)
	}
}

// ─── HTTP middleware ────────────────────────────────────────────────────

type middleware func(http.Handler) http.Handler

func chain(h http.Handler, mws ...middleware) http.Handler {
	for i := len(mws) - 1; i >= 0; i-- {
		h = mws[i](h)
	}
	return h
}

func recoverMW(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if rec := recover(); rec != nil {
				log.Printf("panic in handler: %%v", rec)
				http.Error(w, "internal error", http.StatusInternalServerError)
			}
		}()
		next.ServeHTTP(w, r)
	})
}

// viewerMW decodes an Authorization: Bearer JWT into auth.Viewer and stuffs
// it onto ctx. Anonymous requests pass through with no viewer; the @auth
// directive is what rejects them later if the field requires a role.
func viewerMW(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		if v, err := decodeJWT(r); err == nil && v != nil {
			ctx = auth.WithViewer(ctx, v)
		}
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func dataloaderMW(clients *client.Clients) middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := dataloader.WithContext(r.Context(), dataloader.New(clients))
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

func bindingsMW(b *directive.Bindings) middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := directive.WithBindings(r.Context(), b)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

// ─── JWT decode ─────────────────────────────────────────────────────────

// decodeJWT extracts a Bearer token, verifies it with HMAC against
// JWT_HMAC_SECRET, and maps the "sub" + "role" claims onto auth.Viewer.
// Returns (nil, nil) for anonymous requests; (nil, err) for malformed tokens.
func decodeJWT(r *http.Request) (*auth.Viewer, error) {
	hdr := r.Header.Get("Authorization")
	if hdr == "" {
		return nil, nil
	}
	parts := strings.SplitN(hdr, " ", 2)
	if len(parts) != 2 || !strings.EqualFold(parts[0], "Bearer") {
		return nil, errors.New("malformed Authorization header")
	}
	secret := os.Getenv("JWT_HMAC_SECRET")
	if secret == "" {
		return nil, errors.New("JWT_HMAC_SECRET not set")
	}
	tok, err := jwt.Parse(parts[1], func(t *jwt.Token) (any, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %%v", t.Header["alg"])
		}
		return []byte(secret), nil
	})
	if err != nil || !tok.Valid {
		return nil, err
	}
	claims, ok := tok.Claims.(jwt.MapClaims)
	if !ok {
		return nil, errors.New("non-map claims")
	}
	sub, _ := claims["sub"].(string)
	role, _ := claims["role"].(string)
	return &auth.Viewer{UserID: sub, Role: role}, nil
}

// ─── Cache backend ──────────────────────────────────────────────────────

// buildCache returns the configured cache backend + the per-entry TTL. When
// CACHE_REDIS_ADDR is unset, returns cache.Noop{} so the gateway runs with
// no caching (handy for local dev). TTL falls back to 5 minutes.
func buildCache() (cache.Cache, time.Duration) {
	ttl := 5 * time.Minute
	if s := os.Getenv("CACHE_TTL_SECONDS"); s != "" {
		if n, err := strconv.Atoi(s); err == nil && n > 0 {
			ttl = time.Duration(n) * time.Second
		}
	}
	addr := os.Getenv("CACHE_REDIS_ADDR")
	if addr == "" {
		log.Printf("⚠  CACHE_REDIS_ADDR unset — running without cache (Noop)")
		return cache.Noop{}, ttl
	}
	password := os.Getenv("CACHE_REDIS_PASSWORD")
	db := 0
	if s := os.Getenv("CACHE_REDIS_DB"); s != "" {
		if n, err := strconv.Atoi(s); err == nil {
			db = n
		}
	}
	rc, err := cache.NewRedis(addr, password, db)
	if err != nil {
		log.Printf("⚠  redis dial failed (%%v) — falling back to Noop cache", err)
		return cache.Noop{}, ttl
	}
	log.Printf("✅ cache: Redis %%s db=%%d ttl=%%s", addr, db, ttl)
	return rc, ttl
}

// ─── Business-rule store ────────────────────────────────────────────────

// buildRuleStore loads the dynamic business rules from MongoDB. The URI
// comes from POLICY_MONGO_URI; db / collection default to lms_policy /
// business_rule. Returns nil (rules disabled — mutations pass straight
// through) when the URI is unset or Mongo is unreachable, so a missing rule
// store never wedges the gateway.
func buildRuleStore() *domain.RuleStore {
	uri := os.Getenv("POLICY_MONGO_URI")
	if uri == "" {
		log.Printf("⚠  POLICY_MONGO_URI unset — business rules disabled")
		return nil
	}
	db := env("POLICY_MONGO_DB", "lms_policy")
	coll := env("RULE_MONGO_COLLECTION", "business_rule")
	rs, err := domain.NewRuleStore(context.Background(), uri, db, coll)
	if err != nil {
		log.Printf("⚠  business-rule store init failed (%%v) — rules disabled", err)
		return nil
	}
	return rs
}

// buildActionStore loads dynamic actions (the fetch/compute/write pipelines
// behind the runAction mutation) from MongoDB. Same fallback policy as the
// rule store: nil (runAction disabled) when unset / unreachable.
func buildActionStore() *domain.ActionStore {
	uri := os.Getenv("POLICY_MONGO_URI")
	if uri == "" {
		return nil
	}
	db := env("POLICY_MONGO_DB", "lms_policy")
	coll := env("ACTION_MONGO_COLLECTION", "action")
	as, err := domain.NewActionStore(context.Background(), uri, db, coll)
	if err != nil {
		log.Printf("⚠  action store init failed (%%v) — runAction disabled", err)
		return nil
	}
	return as
}

// ─── gRPC dial options ──────────────────────────────────────────────────

// buildDialOpts assembles options shared by every backend dial. mTLS kicks
// in when TLS_CERT_FILE / TLS_KEY_FILE / TLS_CA_FILE are all set; otherwise
// the gateway uses an insecure transport (suitable for local development).
func buildDialOpts() ([]grpc.DialOption, error) {
	certPath := os.Getenv("TLS_CERT_FILE")
	keyPath := os.Getenv("TLS_KEY_FILE")
	caPath := os.Getenv("TLS_CA_FILE")

	opts := []grpc.DialOption{
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(64 * 1024 * 1024)),
	}

	if certPath == "" || keyPath == "" || caPath == "" {
		log.Printf("⚠  TLS env vars unset — dialing backends with insecure transport")
		opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
		return opts, nil
	}

	cert, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		return nil, fmt.Errorf("load cert: %%w", err)
	}
	caPEM, err := os.ReadFile(caPath)
	if err != nil {
		return nil, fmt.Errorf("read ca: %%w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, errors.New("failed to parse CA pem")
	}
	tlsCfg := &tls.Config{
		Certificates: []tls.Certificate{cert},
		RootCAs:      pool,
		MinVersion:   tls.VersionTLS12,
	}
	opts = append(opts, grpc.WithTransportCredentials(credentials.NewTLS(tlsCfg)))
	return opts, nil
}

// env returns os.Getenv(key) or def when unset.
func env(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
`, in.ModulePath, endpointsBlock.String(), in.Port), "\n")

	mainPath := filepath.Join(in.ServerDir, "main.go")
	// Idempotent: skip if user has already edited main.go.
	if _, err := os.Stat(mainPath); err == nil {
		return nil
	}
	return os.WriteFile(mainPath, []byte(body), 0644)
}
