package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ResolverGenInput drives gen of graph/resolver/*.go.
type ResolverGenInput struct {
	ServerDir  string
	ModulePath string
	Protos     []ProtoInfo
	Config     GatewayConfig
}

// GenerateResolvers overwrites per-service *.resolvers.go with real CRUD +
// relation impls. resolver.go is left alone — Phase 2 already wrote the
// minimal `type Resolver struct{ Clients *client.Clients }` and nothing
// else belongs there. common.resolvers.go is left to gqlgen (it owns the
// Mutation/Query wiring + mutationResolver/queryResolver types + the
// `_empty` stubs that match common.graphqls).
func GenerateResolvers(in ResolverGenInput) error {
	dir := filepath.Join(in.ServerDir, "graph", "resolver")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	// Index entity → owning service for cross-service relation resolution.
	entityService := map[string]string{}
	for _, p := range in.Protos {
		for _, m := range p.Messages {
			if IsEntityMessage(m.Name) {
				entityService[m.Name] = p.ServiceName
			}
		}
	}

	// Per-service files.
	for _, p := range in.Protos {
		content := renderServiceResolverFile(p, in.Config, entityService, in.ModulePath)
		path := filepath.Join(dir, p.ServiceName+".resolvers.go")
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return err
		}
	}

	// action.resolvers.go — the runAction mutation (matches action.graphqls),
	// dispatching to the dynamic action engine.
	action := strings.TrimLeft(`
// Code generated by grpc-gen. DO NOT EDIT.
package resolver

import (
	"context"
	"fmt"
)

// RunAction runs a named dynamic action (fetch / compute / write pipeline
// defined in MongoDB) via the action engine wired in main.go.
func (r *mutationResolver) RunAction(ctx context.Context, name string, input map[string]any) (map[string]any, error) {
	if r.Actions == nil {
		return nil, fmt.Errorf("action engine not configured (POLICY_MONGO_URI unset?)")
	}
	if input == nil {
		input = map[string]any{}
	}
	return r.Actions.Run(ctx, name, input)
}
`, "\n")
	if err := os.WriteFile(filepath.Join(dir, "action.resolvers.go"), []byte(action), 0644); err != nil {
		return err
	}

	return nil
}

func renderServiceResolverFile(p ProtoInfo, cfg GatewayConfig, entityService map[string]string, modulePath string) string {
	var sb strings.Builder
	svc := capitalize(p.ServiceName)

	// Collect every service whose pb package we need: ourselves + the owner
	// service of every relation target on entities defined here.
	pbSvcs := map[string]bool{p.ServiceName: true}
	for _, msg := range p.Messages {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		ent, ok := cfg.Entities[msg.Name]
		if !ok {
			continue
		}
		for _, rel := range ent.Relations {
			if targetSvc, ok := entityService[rel.Target]; ok {
				pbSvcs[targetSvc] = true
			}
		}
	}
	pbSvcList := make([]string, 0, len(pbSvcs))
	for s := range pbSvcs {
		pbSvcList = append(pbSvcList, s)
	}
	sort.Strings(pbSvcList)

	sb.WriteString("// Code generated by grpc-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// Resolver bodies for service %q.\n\n", p.ServiceName)
	sb.WriteString("package resolver\n\n")

	// Entities in this service that need a field resolver (i.e. have any
	// relations declared in gateway-config). For each one we emit the
	// `type xResolver struct{ *Resolver }` plus the `func (r *Resolver) X()
	// generated.XResolver { ... }` wiring further down.
	relationEntities := make([]string, 0)
	for _, msg := range p.Messages {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		if ent, ok := cfg.Entities[msg.Name]; ok && len(ent.Relations) > 0 {
			relationEntities = append(relationEntities, msg.Name)
		}
	}
	sort.Strings(relationEntities)

	sb.WriteString("import (\n")
	sb.WriteString("\t\"context\"\n\n")
	fmt.Fprintf(&sb, "\tcommonpb \"%s/proto/common\"\n", modulePath)
	for _, s := range pbSvcList {
		if s == p.ServiceName {
			fmt.Fprintf(&sb, "\tpb \"%s/proto/%s\"\n", modulePath, s)
		} else {
			fmt.Fprintf(&sb, "\t%spb \"%s/proto/%s\"\n", s, modulePath, s)
		}
	}
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/convert\"\n", modulePath)
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/dataloader\"\n", modulePath)
	if len(relationEntities) > 0 {
		fmt.Fprintf(&sb, "\t\"%s/src/server/graph/generated\"\n", modulePath)
	}
	fmt.Fprintf(&sb, "\t\"%s/src/server/graph/model\"\n", modulePath)
	sb.WriteString(")\n\n")

	// Belt-and-suspenders so a service that happens not to exercise one of
	// the imported packages still has every import touched. Avoids unused-
	// import errors when, e.g., a service has belongsTo (DataLoader path)
	// but no hasOne/hasMany (which is where the cross-service pb is used).
	sb.WriteString("var _ = context.Background\n")
	sb.WriteString("var _ = commonpb.FilterOperator(0)\n")
	for _, s := range pbSvcList {
		alias := "pb"
		if s != p.ServiceName {
			alias = s + "pb"
		}
		fmt.Fprintf(&sb, "var _ = %s.File_proto_%s_%s_proto\n", alias, s, s)
	}
	sb.WriteString("var _ = model.SearchInput{}\n")
	sb.WriteString("var _ = convert.SearchInputToPB\n")
	sb.WriteString("var _ = dataloader.For\n\n")

	// Entity sub-resolver wiring: gqlgen's common.resolvers.go owns the
	// Mutation()/Query() wrappers; per-entity Resolver wrappers live next
	// to the entity's own schema, i.e. here in the service file.
	for _, e := range relationEntities {
		fmt.Fprintf(&sb, "func (r *Resolver) %s() generated.%sResolver { return &%sResolver{r} }\n", e, e, lowerFirst(e))
	}
	for _, e := range relationEntities {
		fmt.Fprintf(&sb, "type %sResolver struct{ *Resolver }\n", lowerFirst(e))
	}
	if len(relationEntities) > 0 {
		sb.WriteString("\n")
	}

	// Mutations + Queries: one block per entity that has matching RPCs.
	rpcs := map[string]bool{}
	for _, r := range p.RPCs {
		rpcs[r.Name] = true
	}

	for _, msg := range sortedMessages(p.Messages) {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		entity := msg.Name
		camel := lowerFirst(entity)

		// listEntity
		if rpcs["List"+entity] {
			fmt.Fprintf(&sb, "// List%s — gRPC list with optional search filter.\n", entity)
			fmt.Fprintf(&sb, "func (r *queryResolver) List%s(ctx context.Context, search *model.SearchInput) (*model.%sListResult, error) {\n", entity, entity)
			fmt.Fprintf(&sb, "\tresp, err := r.Clients.%s.List%s(ctx, &pb.List%sRequest{Search: convert.SearchInputToPB(search)})\n", svc, entity, entity)
			fmt.Fprintf(&sb, "\tif err != nil { return nil, err }\n")
			fmt.Fprintf(&sb, "\treturn &model.%sListResult{\n", entity)
			fmt.Fprintf(&sb, "\t\tItems:    convert.PBTo%sSlice(resp.Get%s()),\n", entity, pascalCaseFromSnake(snakeCase(entity)))
			fmt.Fprintf(&sb, "\t\tTotal:    int(resp.GetTotal()),\n")
			fmt.Fprintf(&sb, "\t\tPage:     int(resp.GetPage()),\n")
			fmt.Fprintf(&sb, "\t\tPageSize: int(resp.GetPageSize()),\n")
			fmt.Fprintf(&sb, "\t}, nil\n")
			fmt.Fprintf(&sb, "}\n\n")

			// single-fetch via DataLoader
			fmt.Fprintf(&sb, "// %s — single-fetch by id (uses DataLoader).\n", camel)
			fmt.Fprintf(&sb, "func (r *queryResolver) %s(ctx context.Context, id string) (*model.%s, error) {\n", entity, entity)
			fmt.Fprintf(&sb, "\titem, err := dataloader.For(ctx).%s.Load(ctx, id)()\n", entity)
			fmt.Fprintf(&sb, "\tif err != nil { return nil, nil } // treat not-found as null\n")
			fmt.Fprintf(&sb, "\treturn convert.PBTo%s(item), nil\n", entity)
			fmt.Fprintf(&sb, "}\n\n")
		}

		// Create
		if rpcs["Create"+entity] {
			fmt.Fprintf(&sb, "func (r *mutationResolver) Create%s(ctx context.Context, input model.Create%sInput) (*model.%s, error) {\n", entity, entity, entity)
			fmt.Fprintf(&sb, "\tresp, err := r.Clients.%s.Create%s(ctx, convert.Create%sInputToPB(input))\n", svc, entity, entity)
			fmt.Fprintf(&sb, "\tif err != nil { return nil, err }\n")
			fmt.Fprintf(&sb, "\treturn convert.PBTo%s(resp.Get%s()), nil\n", entity, pascalCaseFromSnake(snakeCase(entity)))
			fmt.Fprintf(&sb, "}\n\n")
		}
		// Update
		if rpcs["Update"+entity] {
			fmt.Fprintf(&sb, "func (r *mutationResolver) Update%s(ctx context.Context, filters []*model.FilterCriteria, input model.Update%sInput) (*model.%sBatchResult, error) {\n", entity, entity, entity)
			fmt.Fprintf(&sb, "\tresp, err := r.Clients.%s.Update%s(ctx, convert.Update%sInputToPB(filters, input))\n", svc, entity, entity)
			fmt.Fprintf(&sb, "\tif err != nil { return nil, err }\n")
			fmt.Fprintf(&sb, "\treturn &model.%sBatchResult{\n", entity)
			fmt.Fprintf(&sb, "\t\tItems:         convert.PBTo%sSlice(resp.Get%s()),\n", entity, pascalCaseFromSnake(snakeCase(entity)))
			fmt.Fprintf(&sb, "\t\tAffectedCount: int(resp.GetAffectedCount()),\n")
			fmt.Fprintf(&sb, "\t}, nil\n")
			fmt.Fprintf(&sb, "}\n\n")
		}
		// Delete
		if rpcs["Delete"+entity] {
			fmt.Fprintf(&sb, "func (r *mutationResolver) Delete%s(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {\n", entity)
			fmt.Fprintf(&sb, "\tresp, err := r.Clients.%s.Delete%s(ctx, &pb.Delete%sRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})\n", svc, entity, entity)
			fmt.Fprintf(&sb, "\tif err != nil { return nil, err }\n")
			fmt.Fprintf(&sb, "\treturn &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil\n")
			fmt.Fprintf(&sb, "}\n\n")
		}
	}

	// Field resolvers for relations defined on entities of this service.
	for _, msg := range sortedMessages(p.Messages) {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		ent, ok := cfg.Entities[msg.Name]
		if !ok || len(ent.Relations) == 0 {
			continue
		}
		relNames := make([]string, 0, len(ent.Relations))
		for n := range ent.Relations {
			relNames = append(relNames, n)
		}
		sort.Strings(relNames)

		for _, relName := range relNames {
			rel := ent.Relations[relName]
			renderRelationResolver(&sb, msg.Name, relName, rel, entityService, p.ServiceName)
		}
	}

	return sb.String()
}

func renderRelationResolver(sb *strings.Builder, entity, relName string, rel RelationConfig, entityService map[string]string, currentService string) {
	targetSvc, ok := entityService[rel.Target]
	if !ok {
		return // target not in our project
	}

	receiver := lowerFirst(entity) + "Resolver"
	method := pascalCaseFromSnake(relName)

	// pb alias: "pb" if target lives in the same service file, else "<svc>pb".
	pbAlias := "pb"
	if targetSvc != currentService {
		pbAlias = targetSvc + "pb"
	}

	switch rel.Kind {
	case "belongsTo":
		localGoName := modelFieldName(rel.LocalKey)
		fmt.Fprintf(sb, "func (r *%s) %s(ctx context.Context, obj *model.%s) (*model.%s, error) {\n", receiver, method, entity, rel.Target)
		fmt.Fprintf(sb, "\tif obj.%s == \"\" { return nil, nil }\n", localGoName)
		fmt.Fprintf(sb, "\titem, err := dataloader.For(ctx).%s.Load(ctx, obj.%s)()\n", rel.Target, localGoName)
		fmt.Fprintf(sb, "\tif err != nil { return nil, nil }\n")
		fmt.Fprintf(sb, "\treturn convert.PBTo%s(item), nil\n", rel.Target)
		fmt.Fprintf(sb, "}\n\n")

	case "hasOne":
		// fetch via ListX on target with filter foreign_key == obj.ID; take first.
		fmt.Fprintf(sb, "func (r *%s) %s(ctx context.Context, obj *model.%s) (*model.%s, error) {\n", receiver, method, entity, rel.Target)
		fmt.Fprintf(sb, "\tresp, err := r.Clients.%s.List%s(ctx, &%s.List%sRequest{\n", capitalize(targetSvc), rel.Target, pbAlias, rel.Target)
		fmt.Fprintf(sb, "\t\tSearch: &commonpb.SearchRequest{\n")
		fmt.Fprintf(sb, "\t\t\tFilters: []*commonpb.FilterCriteria{{\n")
		fmt.Fprintf(sb, "\t\t\t\tCriteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{\n")
		fmt.Fprintf(sb, "\t\t\t\t\tField:    %q,\n", rel.ForeignKey)
		fmt.Fprintf(sb, "\t\t\t\t\tOperator: commonpb.FilterOperator_EQUAL,\n")
		fmt.Fprintf(sb, "\t\t\t\t\tValues:   []string{obj.ID},\n")
		fmt.Fprintf(sb, "\t\t\t\t}},\n")
		fmt.Fprintf(sb, "\t\t\t}},\n")
		fmt.Fprintf(sb, "\t\t\tPagination: &commonpb.Pagination{PageSize: 1},\n")
		fmt.Fprintf(sb, "\t\t},\n")
		fmt.Fprintf(sb, "\t})\n")
		fmt.Fprintf(sb, "\tif err != nil || len(resp.Get%s()) == 0 { return nil, nil }\n", pascalCaseFromSnake(snakeCase(rel.Target)))
		fmt.Fprintf(sb, "\treturn convert.PBTo%s(resp.Get%s()[0]), nil\n", rel.Target, pascalCaseFromSnake(snakeCase(rel.Target)))
		fmt.Fprintf(sb, "}\n\n")

	case "hasMany":
		fmt.Fprintf(sb, "func (r *%s) %s(ctx context.Context, obj *model.%s, search *model.SearchInput) ([]*model.%s, error) {\n", receiver, method, entity, rel.Target)
		fmt.Fprintf(sb, "\tpbSearch := convert.SearchInputToPB(search)\n")
		fmt.Fprintf(sb, "\tif pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }\n")
		fmt.Fprintf(sb, "\tpbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{\n")
		fmt.Fprintf(sb, "\t\tCriteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{\n")
		fmt.Fprintf(sb, "\t\t\tField:    %q,\n", rel.ForeignKey)
		fmt.Fprintf(sb, "\t\t\tOperator: commonpb.FilterOperator_EQUAL,\n")
		fmt.Fprintf(sb, "\t\t\tValues:   []string{obj.ID},\n")
		fmt.Fprintf(sb, "\t\t}},\n")
		fmt.Fprintf(sb, "\t})\n")
		fmt.Fprintf(sb, "\tresp, err := r.Clients.%s.List%s(ctx, &%s.List%sRequest{Search: pbSearch})\n", capitalize(targetSvc), rel.Target, pbAlias, rel.Target)
		fmt.Fprintf(sb, "\tif err != nil { return nil, err }\n")
		fmt.Fprintf(sb, "\treturn convert.PBTo%sSlice(resp.Get%s()), nil\n", rel.Target, pascalCaseFromSnake(snakeCase(rel.Target)))
		fmt.Fprintf(sb, "}\n\n")
	}
}
