package gateway

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// SchemaGenInput bundles everything schema gen needs.
type SchemaGenInput struct {
	OutDir string                // e.g. src/server/graph/schema
	Protos []ProtoInfo
	Config GatewayConfig
}

// GenerateSchemas writes one .graphqls per service plus a `common.graphqls`
// with shared scalars/inputs.
func GenerateSchemas(in SchemaGenInput) error {
	if err := os.MkdirAll(in.OutDir, 0755); err != nil {
		return err
	}

	if err := writeCommonSchema(in.OutDir); err != nil {
		return err
	}
	if err := writeActionSchema(in.OutDir, in.Config.ActionAuth); err != nil {
		return err
	}

	// Index entities so cross-service relation rendering can resolve type names.
	entityIndex := map[string]ProtoInfo{} // entity name → owning proto
	for _, p := range in.Protos {
		for _, m := range p.Messages {
			if IsEntityMessage(m.Name) {
				entityIndex[m.Name] = p
			}
		}
	}

	for _, p := range in.Protos {
		path := filepath.Join(in.OutDir, p.ServiceName+".graphqls")
		content := renderServiceSchema(p, in.Config, entityIndex)
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func writeCommonSchema(outDir string) error {
	// Shared scalar + filter input types.
	body := `# Code generated by grpc-gen. EDIT proto/gateway-config; rerun to refresh.
# Shared scalars and filter inputs reused by every service schema.

# @goField(forceResolver: true) flips a GraphQL field from "read from struct"
# to "call a Go resolver". We use it on every cross-entity relation so the
# gateway resolves via gRPC + DataLoader instead of expecting pre-populated
# data on the model. The directive is recognised by gqlgen out of the box.
directive @goField(
  forceResolver: Boolean
  name: String
  omittable: Boolean
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

# @auth restricts a field to viewers carrying a specific role. The directive
# runner is generated in graph/directive/directive.go; the actual role
# check is delegated to a policy.Enforcer wired in main.go.
directive @auth(role: String!) on FIELD_DEFINITION

# @policy runs a named expression against the viewer + object scope.
# Example: @policy(rule: "viewer.role == 'TEACHER' && obj.teacher_id == viewer.id").
# Rules are stored in policy-engine MongoDB; the runner asks the enforcer
# to evaluate the rule string with the current request's bindings.
directive @policy(rule: String!) on FIELD_DEFINITION

scalar Time
scalar JSON

enum FilterOperator {
  EQUAL
  NOT_EQUAL
  GREATER_THAN
  GREATER_THAN_EQUAL
  LESS_THAN
  LESS_THAN_EQUAL
  LIKE
  IN
  NOT_IN
  IS_NULL
  IS_NOT_NULL
  BETWEEN
}

enum LogicalCondition { AND OR }

input FilterCondition {
  field: String!
  operator: FilterOperator!
  values: [String!]!
}

input FilterGroup {
  logic: LogicalCondition!
  filters: [FilterCriteria!]!
}

input FilterCriteria {
  condition: FilterCondition
  group: FilterGroup
}

input Pagination {
  page: Int
  page_size: Int
  sort_by: String
  descending: Boolean
}

input SearchInput {
  pagination: Pagination
  filters: [FilterCriteria!]
}

# Returned by every deleteX mutation across services.
type DeleteResult {
  affected_count: Int!
}

type Query { _empty: String }
type Mutation { _empty: String }
`
	// Filename `common.graphqls` (no leading underscore) — Go ignores files
	// whose name starts with `_`, so the matching gqlgen-generated
	// `common.resolvers.go` would silently disappear from the build.
	return os.WriteFile(filepath.Join(outDir, "common.graphqls"), []byte(body), 0644)
}

// opAuthSuffix returns ` @auth(role: "X")` when gateway-config declares an
// op_auth role for the entity's operation (create|update|delete|list|get),
// else "". Gates the generated Query/Mutation field.
func opAuthSuffix(cfg GatewayConfig, entity, op string) string {
	ent, ok := cfg.Entities[entity]
	if !ok {
		return ""
	}
	if role, ok := ent.OpAuth[op]; ok && role != "" {
		return fmt.Sprintf(" @auth(role: %q)", role)
	}
	return ""
}

// writeActionSchema declares the generic runAction mutation — the entry
// point to the dynamic action engine (lms_policy.action documents). Its own
// schema file so gqlgen emits a matching action.resolvers.go that grpc-gen's
// resolver phase fills in. actionAuth (gateway-config action_auth) gates it.
func writeActionSchema(outDir, actionAuth string) error {
	gate := ""
	if actionAuth != "" {
		gate = fmt.Sprintf(" @auth(role: %q)", actionAuth)
	}
	body := fmt.Sprintf(`# Code generated by grpc-gen. DO NOT EDIT.
# Entry point to the dynamic action engine: a custom multi-step operation
# (fetch / compute / write) defined as a document, invoked by name.

extend type Mutation {
  runAction(name: String!, input: JSON): JSON!%s
}
`, gate)
	return os.WriteFile(filepath.Join(outDir, "action.graphqls"), []byte(body), 0644)
}

func renderServiceSchema(p ProtoInfo, cfg GatewayConfig, idx map[string]ProtoInfo) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Code generated by grpc-gen for service %q. DO NOT EDIT.\n\n", p.ServiceName)

	// Enums first (used by entity fields).
	for _, en := range sortedEnums(p.Enums) {
		fmt.Fprintf(&sb, "enum %s {\n", en.Name)
		for _, v := range en.Values {
			fmt.Fprintf(&sb, "  %s\n", v)
		}
		sb.WriteString("}\n\n")
	}

	// Entity types.
	for _, msg := range sortedMessages(p.Messages) {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		renderEntityType(&sb, msg, cfg, idx)
	}

	// CRUD inputs + Query/Mutation extensions for each entity that has matching RPCs.
	rpcByName := map[string]bool{}
	for _, r := range p.RPCs {
		rpcByName[r.Name] = true
	}
	for _, msg := range sortedMessages(p.Messages) {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		entity := msg.Name
		if rpcByName["Create"+entity] {
			renderInputType(&sb, "Create"+entity+"Input", findMsg(p, "Create"+entity+"Request"))
		}
		if rpcByName["Update"+entity] {
			renderInputType(&sb, "Update"+entity+"Input", findMsg(p, "Update"+entity+"Request"))
		}
	}

	// Query + Mutation extensions.
	sb.WriteString("\nextend type Query {\n")
	for _, msg := range sortedMessages(p.Messages) {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		entity := msg.Name
		camel := lowerFirst(entity)
		if rpcByName["List"+entity] {
			// `listClass(search): ClassListResult!` — name mirrors the proto
			// RPC so we sidestep the "Class → ClassS / Category → Categorys"
			// pluralization trap.
			fmt.Fprintf(&sb, "  list%s(search: SearchInput): %sListResult!%s\n", entity, entity, opAuthSuffix(cfg, entity, "list"))
			// Single-fetch convenience: `class(id: ID!): Class` (nullable when
			// the id doesn't exist).
			fmt.Fprintf(&sb, "  %s(id: ID!): %s%s\n", camel, entity, opAuthSuffix(cfg, entity, "get"))
		}
	}
	sb.WriteString("}\n\n")

	sb.WriteString("extend type Mutation {\n")
	for _, msg := range sortedMessages(p.Messages) {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		entity := msg.Name
		if rpcByName["Create"+entity] {
			fmt.Fprintf(&sb, "  create%s(input: Create%sInput!): %s!%s\n", entity, entity, entity, opAuthSuffix(cfg, entity, "create"))
		}
		if rpcByName["Update"+entity] {
			fmt.Fprintf(&sb, "  update%s(filters: [FilterCriteria!]!, input: Update%sInput!): %sBatchResult!%s\n", entity, entity, entity, opAuthSuffix(cfg, entity, "update"))
		}
		if rpcByName["Delete"+entity] {
			fmt.Fprintf(&sb, "  delete%s(filters: [FilterCriteria!]!): DeleteResult!%s\n", entity, opAuthSuffix(cfg, entity, "delete"))
		}
	}
	sb.WriteString("}\n\n")

	// Batch result + list result types per entity.
	for _, msg := range sortedMessages(p.Messages) {
		if !IsEntityMessage(msg.Name) {
			continue
		}
		entity := msg.Name
		if rpcByName["List"+entity] {
			fmt.Fprintf(&sb, "type %sListResult {\n  items: [%s!]!\n  total: Int!\n  page: Int!\n  page_size: Int!\n}\n\n", entity, entity)
		}
		if rpcByName["Update"+entity] {
			fmt.Fprintf(&sb, "type %sBatchResult {\n  items: [%s!]!\n  affected_count: Int!\n}\n\n", entity, entity)
		}
	}

	// DeleteResult lives in _common.graphqls — shared across services.

	return sb.String()
}

func renderEntityType(sb *strings.Builder, msg MessageInfo, cfg GatewayConfig, idx map[string]ProtoInfo) {
	fmt.Fprintf(sb, "type %s {\n", msg.Name)

	ent, hasEnt := cfg.Entities[msg.Name]
	for _, f := range msg.Fields {
		gqlType := mapType(f, true)
		// Append field-level @auth / @policy declared in gateway-config.
		// The field is already ModelNullable (ApplyFieldDirectives) so the
		// type rendered above has no trailing `!` — a denied directive can
		// resolve it to null without erroring the parent object.
		var dir string
		if hasEnt {
			if role, ok := ent.FieldAuth[f.Name]; ok {
				dir += fmt.Sprintf(" @auth(role: %q)", role)
			}
			if rule, ok := ent.FieldPolicy[f.Name]; ok {
				dir += fmt.Sprintf(" @policy(rule: %q)", rule)
			}
		}
		fmt.Fprintf(sb, "  %s: %s%s\n", f.Name, gqlType, dir)
	}

	// Append relations declared in gateway-config for this entity.
	if hasEnt {
		relNames := make([]string, 0, len(ent.Relations))
		for n := range ent.Relations {
			relNames = append(relNames, n)
		}
		sort.Strings(relNames)

		if len(relNames) > 0 {
			sb.WriteString("\n  # === Relations (gateway-config.yaml) ===\n")
		}
		// @goField(forceResolver: true) tells gqlgen NOT to inline the
		// relation as a Go struct field on the model. Without it, gqlgen
		// would expect the data to already be populated; with it, gqlgen
		// emits a Resolver interface and our hand-rolled resolver fetches
		// the data lazily through DataLoader / gRPC.
		for _, n := range relNames {
			rel := ent.Relations[n]
			target := rel.Target
			if _, ok := idx[target]; !ok {
				fmt.Fprintf(sb, "  # SKIP %s: unknown target %s\n", n, target)
				continue
			}
			switch rel.Kind {
			case "belongsTo":
				fmt.Fprintf(sb, "  %s: %s @goField(forceResolver: true)\n", n, target)
			case "hasOne":
				fmt.Fprintf(sb, "  %s: %s @goField(forceResolver: true)\n", n, target)
			case "hasMany":
				fmt.Fprintf(sb, "  %s(search: SearchInput): [%s!]! @goField(forceResolver: true)\n", n, target)
			}
		}
	}
	sb.WriteString("}\n\n")
}

func renderInputType(sb *strings.Builder, name string, msg *MessageInfo) {
	if msg == nil {
		return
	}
	fmt.Fprintf(sb, "input %s {\n", name)
	for _, f := range msg.Fields {
		// Skip the FilterCriteria filters field — handled by the mutation
		// signature's `filters` arg, not the input type body.
		if f.Type == "common.FilterCriteria" {
			continue
		}
		// Honour the proto's optional/required: required proto fields become
		// non-null GraphQL inputs so converter code can assign without nil
		// dereferencing.
		gqlType := mapType(f, true)
		fmt.Fprintf(sb, "  %s: %s\n", f.Name, gqlType)
	}
	sb.WriteString("}\n\n")
}

// mapType converts a proto type to a GraphQL type. `required` toggles whether
// the result is nullable: true on entity output (proto3 fields generally have
// defaults so they're non-null) and false on inputs (everything is opt-in).
func mapType(f FieldInfo, required bool) string {
	var base string
	switch f.Type {
	case "string":
		base = "String"
	case "bool":
		base = "Boolean"
	case "int32", "int64", "uint32", "uint64", "sint32", "sint64", "fixed32", "fixed64", "sfixed32", "sfixed64":
		if f.Name == "id" || strings.HasSuffix(f.Name, "_id") {
			base = "ID"
		} else {
			base = "Int"
		}
	case "float", "double":
		base = "Float"
	case "bytes":
		base = "String"
	case "google.protobuf.Timestamp":
		base = "Time"
	default:
		// Enum or message type — use bare name.
		base = lastSegment(f.Type)
	}

	if f.IsRepeated {
		return "[" + base + "!]!"
	}
	// ModelNullable (field-level @auth/@policy guard) forces nullability so a
	// denied directive can resolve to null instead of erroring the object.
	if required && !f.IsOptional && !f.ModelNullable {
		return base + "!"
	}
	return base
}

// ─── helpers ───

func findMsg(p ProtoInfo, name string) *MessageInfo {
	for i := range p.Messages {
		if p.Messages[i].Name == name {
			return &p.Messages[i]
		}
	}
	return nil
}

func sortedMessages(in []MessageInfo) []MessageInfo {
	out := make([]MessageInfo, len(in))
	copy(out, in)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func sortedEnums(in []EnumInfo) []EnumInfo {
	out := make([]EnumInfo, len(in))
	copy(out, in)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func lastSegment(typ string) string {
	if idx := strings.LastIndex(typ, "."); idx >= 0 {
		return typ[idx+1:]
	}
	return typ
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
