version: '3.8'

services:
  material:
    build:
      context: ../../..
      dockerfile: src/service/material/Dockerfile
    image: github.com/thaily/lms/material:latest
    container_name: material_service
    env_file:
      - material.env
    ports:
      - "50054:50054"
    volumes:
      - .:/app/service:ro
      - ../../../logs:/app/logs
    networks:
      - material_network
    restart: unless-stopped

networks:
  material_network:
    driver: bridge
