// Code generated by grpc-gen. DO NOT EDIT.
package resolver

import (
	"context"
	"fmt"
)

// RunAction runs a named dynamic action (fetch / compute / write pipeline
// defined in MongoDB) via the action engine wired in main.go.
func (r *mutationResolver) RunAction(ctx context.Context, name string, input map[string]any) (map[string]any, error) {
	if r.Actions == nil {
		return nil, fmt.Errorf("action engine not configured (POLICY_MONGO_URI unset?)")
	}
	if input == nil {
		input = map[string]any{}
	}
	return r.Actions.Run(ctx, name, input)
}
