// Code generated by grpc-gen. DO NOT EDIT.
// Resolver bodies for service "exam".

package resolver

import (
	"context"

	commonpb "github.com/thaily/lms/proto/common"
	classpb "github.com/thaily/lms/proto/class"
	pb "github.com/thaily/lms/proto/exam"
	userpb "github.com/thaily/lms/proto/user"
	"github.com/thaily/lms/src/server/graph/convert"
	"github.com/thaily/lms/src/server/graph/dataloader"
	"github.com/thaily/lms/src/server/graph/generated"
	"github.com/thaily/lms/src/server/graph/model"
)

var _ = context.Background
var _ = commonpb.FilterOperator(0)
var _ = classpb.File_proto_class_class_proto
var _ = pb.File_proto_exam_exam_proto
var _ = userpb.File_proto_user_user_proto
var _ = model.SearchInput{}
var _ = convert.SearchInputToPB
var _ = dataloader.For

func (r *Resolver) Exam() generated.ExamResolver { return &examResolver{r} }
func (r *Resolver) ExamAssignment() generated.ExamAssignmentResolver { return &examAssignmentResolver{r} }
func (r *Resolver) Question() generated.QuestionResolver { return &questionResolver{r} }
func (r *Resolver) QuestionAnswer() generated.QuestionAnswerResolver { return &questionAnswerResolver{r} }
func (r *Resolver) QuestionChoice() generated.QuestionChoiceResolver { return &questionChoiceResolver{r} }
type examResolver struct{ *Resolver }
type examAssignmentResolver struct{ *Resolver }
type questionResolver struct{ *Resolver }
type questionAnswerResolver struct{ *Resolver }
type questionChoiceResolver struct{ *Resolver }

// ListExam — gRPC list with optional search filter.
func (r *queryResolver) ListExam(ctx context.Context, search *model.SearchInput) (*model.ExamListResult, error) {
	resp, err := r.Clients.Exam.ListExam(ctx, &pb.ListExamRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.ExamListResult{
		Items:    convert.PBToExamSlice(resp.GetExam()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// exam — single-fetch by id (uses DataLoader).
func (r *queryResolver) Exam(ctx context.Context, id string) (*model.Exam, error) {
	item, err := dataloader.For(ctx).Exam.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToExam(item), nil
}

func (r *mutationResolver) CreateExam(ctx context.Context, input model.CreateExamInput) (*model.Exam, error) {
	resp, err := r.Clients.Exam.CreateExam(ctx, convert.CreateExamInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToExam(resp.GetExam()), nil
}

func (r *mutationResolver) UpdateExam(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateExamInput) (*model.ExamBatchResult, error) {
	resp, err := r.Clients.Exam.UpdateExam(ctx, convert.UpdateExamInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.ExamBatchResult{
		Items:         convert.PBToExamSlice(resp.GetExam()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteExam(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Exam.DeleteExam(ctx, &pb.DeleteExamRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListExamAssignment — gRPC list with optional search filter.
func (r *queryResolver) ListExamAssignment(ctx context.Context, search *model.SearchInput) (*model.ExamAssignmentListResult, error) {
	resp, err := r.Clients.Exam.ListExamAssignment(ctx, &pb.ListExamAssignmentRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.ExamAssignmentListResult{
		Items:    convert.PBToExamAssignmentSlice(resp.GetExamAssignment()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// examAssignment — single-fetch by id (uses DataLoader).
func (r *queryResolver) ExamAssignment(ctx context.Context, id string) (*model.ExamAssignment, error) {
	item, err := dataloader.For(ctx).ExamAssignment.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToExamAssignment(item), nil
}

func (r *mutationResolver) CreateExamAssignment(ctx context.Context, input model.CreateExamAssignmentInput) (*model.ExamAssignment, error) {
	resp, err := r.Clients.Exam.CreateExamAssignment(ctx, convert.CreateExamAssignmentInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToExamAssignment(resp.GetExamAssignment()), nil
}

func (r *mutationResolver) UpdateExamAssignment(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateExamAssignmentInput) (*model.ExamAssignmentBatchResult, error) {
	resp, err := r.Clients.Exam.UpdateExamAssignment(ctx, convert.UpdateExamAssignmentInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.ExamAssignmentBatchResult{
		Items:         convert.PBToExamAssignmentSlice(resp.GetExamAssignment()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteExamAssignment(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Exam.DeleteExamAssignment(ctx, &pb.DeleteExamAssignmentRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListQuestion — gRPC list with optional search filter.
func (r *queryResolver) ListQuestion(ctx context.Context, search *model.SearchInput) (*model.QuestionListResult, error) {
	resp, err := r.Clients.Exam.ListQuestion(ctx, &pb.ListQuestionRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.QuestionListResult{
		Items:    convert.PBToQuestionSlice(resp.GetQuestion()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// question — single-fetch by id (uses DataLoader).
func (r *queryResolver) Question(ctx context.Context, id string) (*model.Question, error) {
	item, err := dataloader.For(ctx).Question.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToQuestion(item), nil
}

func (r *mutationResolver) CreateQuestion(ctx context.Context, input model.CreateQuestionInput) (*model.Question, error) {
	resp, err := r.Clients.Exam.CreateQuestion(ctx, convert.CreateQuestionInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToQuestion(resp.GetQuestion()), nil
}

func (r *mutationResolver) UpdateQuestion(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateQuestionInput) (*model.QuestionBatchResult, error) {
	resp, err := r.Clients.Exam.UpdateQuestion(ctx, convert.UpdateQuestionInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.QuestionBatchResult{
		Items:         convert.PBToQuestionSlice(resp.GetQuestion()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteQuestion(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Exam.DeleteQuestion(ctx, &pb.DeleteQuestionRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListQuestionAnswer — gRPC list with optional search filter.
func (r *queryResolver) ListQuestionAnswer(ctx context.Context, search *model.SearchInput) (*model.QuestionAnswerListResult, error) {
	resp, err := r.Clients.Exam.ListQuestionAnswer(ctx, &pb.ListQuestionAnswerRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.QuestionAnswerListResult{
		Items:    convert.PBToQuestionAnswerSlice(resp.GetQuestionAnswer()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// questionAnswer — single-fetch by id (uses DataLoader).
func (r *queryResolver) QuestionAnswer(ctx context.Context, id string) (*model.QuestionAnswer, error) {
	item, err := dataloader.For(ctx).QuestionAnswer.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToQuestionAnswer(item), nil
}

func (r *mutationResolver) CreateQuestionAnswer(ctx context.Context, input model.CreateQuestionAnswerInput) (*model.QuestionAnswer, error) {
	resp, err := r.Clients.Exam.CreateQuestionAnswer(ctx, convert.CreateQuestionAnswerInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToQuestionAnswer(resp.GetQuestionAnswer()), nil
}

func (r *mutationResolver) UpdateQuestionAnswer(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateQuestionAnswerInput) (*model.QuestionAnswerBatchResult, error) {
	resp, err := r.Clients.Exam.UpdateQuestionAnswer(ctx, convert.UpdateQuestionAnswerInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.QuestionAnswerBatchResult{
		Items:         convert.PBToQuestionAnswerSlice(resp.GetQuestionAnswer()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteQuestionAnswer(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Exam.DeleteQuestionAnswer(ctx, &pb.DeleteQuestionAnswerRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListQuestionChoice — gRPC list with optional search filter.
func (r *queryResolver) ListQuestionChoice(ctx context.Context, search *model.SearchInput) (*model.QuestionChoiceListResult, error) {
	resp, err := r.Clients.Exam.ListQuestionChoice(ctx, &pb.ListQuestionChoiceRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.QuestionChoiceListResult{
		Items:    convert.PBToQuestionChoiceSlice(resp.GetQuestionChoice()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// questionChoice — single-fetch by id (uses DataLoader).
func (r *queryResolver) QuestionChoice(ctx context.Context, id string) (*model.QuestionChoice, error) {
	item, err := dataloader.For(ctx).QuestionChoice.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToQuestionChoice(item), nil
}

func (r *mutationResolver) CreateQuestionChoice(ctx context.Context, input model.CreateQuestionChoiceInput) (*model.QuestionChoice, error) {
	resp, err := r.Clients.Exam.CreateQuestionChoice(ctx, convert.CreateQuestionChoiceInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToQuestionChoice(resp.GetQuestionChoice()), nil
}

func (r *mutationResolver) UpdateQuestionChoice(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateQuestionChoiceInput) (*model.QuestionChoiceBatchResult, error) {
	resp, err := r.Clients.Exam.UpdateQuestionChoice(ctx, convert.UpdateQuestionChoiceInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.QuestionChoiceBatchResult{
		Items:         convert.PBToQuestionChoiceSlice(resp.GetQuestionChoice()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteQuestionChoice(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Exam.DeleteQuestionChoice(ctx, &pb.DeleteQuestionChoiceRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

func (r *examResolver) Owner(ctx context.Context, obj *model.Exam) (*model.User, error) {
	if obj.OwnerTeacherID == "" { return nil, nil }
	item, err := dataloader.For(ctx).User.Load(ctx, obj.OwnerTeacherID)()
	if err != nil { return nil, nil }
	return convert.PBToUser(item), nil
}

func (r *examResolver) Questions(ctx context.Context, obj *model.Exam, search *model.SearchInput) ([]*model.Question, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "exam_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Exam.ListQuestion(ctx, &pb.ListQuestionRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToQuestionSlice(resp.GetQuestion()), nil
}

func (r *examAssignmentResolver) Class(ctx context.Context, obj *model.ExamAssignment) (*model.Class, error) {
	if obj.ClassID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Class.Load(ctx, obj.ClassID)()
	if err != nil { return nil, nil }
	return convert.PBToClass(item), nil
}

func (r *examAssignmentResolver) Exam(ctx context.Context, obj *model.ExamAssignment) (*model.Exam, error) {
	if obj.ExamID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Exam.Load(ctx, obj.ExamID)()
	if err != nil { return nil, nil }
	return convert.PBToExam(item), nil
}

func (r *questionResolver) Answers(ctx context.Context, obj *model.Question, search *model.SearchInput) ([]*model.QuestionAnswer, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "question_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Exam.ListQuestionAnswer(ctx, &pb.ListQuestionAnswerRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToQuestionAnswerSlice(resp.GetQuestionAnswer()), nil
}

func (r *questionResolver) Choices(ctx context.Context, obj *model.Question, search *model.SearchInput) ([]*model.QuestionChoice, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "question_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Exam.ListQuestionChoice(ctx, &pb.ListQuestionChoiceRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToQuestionChoiceSlice(resp.GetQuestionChoice()), nil
}

func (r *questionResolver) Exam(ctx context.Context, obj *model.Question) (*model.Exam, error) {
	if obj.ExamID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Exam.Load(ctx, obj.ExamID)()
	if err != nil { return nil, nil }
	return convert.PBToExam(item), nil
}

func (r *questionAnswerResolver) Question(ctx context.Context, obj *model.QuestionAnswer) (*model.Question, error) {
	if obj.QuestionID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Question.Load(ctx, obj.QuestionID)()
	if err != nil { return nil, nil }
	return convert.PBToQuestion(item), nil
}

func (r *questionChoiceResolver) Question(ctx context.Context, obj *model.QuestionChoice) (*model.Question, error) {
	if obj.QuestionID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Question.Load(ctx, obj.QuestionID)()
	if err != nil { return nil, nil }
	return convert.PBToQuestion(item), nil
}

