// Code generated by grpc-gen. DO NOT EDIT.
// Resolver bodies for service "lesson".

package resolver

import (
	"context"

	commonpb "github.com/thaily/lms/proto/common"
	classpb "github.com/thaily/lms/proto/class"
	pb "github.com/thaily/lms/proto/lesson"
	userpb "github.com/thaily/lms/proto/user"
	"github.com/thaily/lms/src/server/graph/convert"
	"github.com/thaily/lms/src/server/graph/dataloader"
	"github.com/thaily/lms/src/server/graph/generated"
	"github.com/thaily/lms/src/server/graph/model"
)

var _ = context.Background
var _ = commonpb.FilterOperator(0)
var _ = classpb.File_proto_class_class_proto
var _ = pb.File_proto_lesson_lesson_proto
var _ = userpb.File_proto_user_user_proto
var _ = model.SearchInput{}
var _ = convert.SearchInputToPB
var _ = dataloader.For

func (r *Resolver) Lesson() generated.LessonResolver { return &lessonResolver{r} }
func (r *Resolver) LessonAttendance() generated.LessonAttendanceResolver { return &lessonAttendanceResolver{r} }
func (r *Resolver) LessonVideo() generated.LessonVideoResolver { return &lessonVideoResolver{r} }
type lessonResolver struct{ *Resolver }
type lessonAttendanceResolver struct{ *Resolver }
type lessonVideoResolver struct{ *Resolver }

// ListLesson — gRPC list with optional search filter.
func (r *queryResolver) ListLesson(ctx context.Context, search *model.SearchInput) (*model.LessonListResult, error) {
	resp, err := r.Clients.Lesson.ListLesson(ctx, &pb.ListLessonRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.LessonListResult{
		Items:    convert.PBToLessonSlice(resp.GetLesson()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// lesson — single-fetch by id (uses DataLoader).
func (r *queryResolver) Lesson(ctx context.Context, id string) (*model.Lesson, error) {
	item, err := dataloader.For(ctx).Lesson.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToLesson(item), nil
}

func (r *mutationResolver) CreateLesson(ctx context.Context, input model.CreateLessonInput) (*model.Lesson, error) {
	resp, err := r.Clients.Lesson.CreateLesson(ctx, convert.CreateLessonInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToLesson(resp.GetLesson()), nil
}

func (r *mutationResolver) UpdateLesson(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateLessonInput) (*model.LessonBatchResult, error) {
	resp, err := r.Clients.Lesson.UpdateLesson(ctx, convert.UpdateLessonInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.LessonBatchResult{
		Items:         convert.PBToLessonSlice(resp.GetLesson()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteLesson(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Lesson.DeleteLesson(ctx, &pb.DeleteLessonRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListLessonAttendance — gRPC list with optional search filter.
func (r *queryResolver) ListLessonAttendance(ctx context.Context, search *model.SearchInput) (*model.LessonAttendanceListResult, error) {
	resp, err := r.Clients.Lesson.ListLessonAttendance(ctx, &pb.ListLessonAttendanceRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.LessonAttendanceListResult{
		Items:    convert.PBToLessonAttendanceSlice(resp.GetLessonAttendance()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// lessonAttendance — single-fetch by id (uses DataLoader).
func (r *queryResolver) LessonAttendance(ctx context.Context, id string) (*model.LessonAttendance, error) {
	item, err := dataloader.For(ctx).LessonAttendance.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToLessonAttendance(item), nil
}

func (r *mutationResolver) CreateLessonAttendance(ctx context.Context, input model.CreateLessonAttendanceInput) (*model.LessonAttendance, error) {
	resp, err := r.Clients.Lesson.CreateLessonAttendance(ctx, convert.CreateLessonAttendanceInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToLessonAttendance(resp.GetLessonAttendance()), nil
}

func (r *mutationResolver) UpdateLessonAttendance(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateLessonAttendanceInput) (*model.LessonAttendanceBatchResult, error) {
	resp, err := r.Clients.Lesson.UpdateLessonAttendance(ctx, convert.UpdateLessonAttendanceInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.LessonAttendanceBatchResult{
		Items:         convert.PBToLessonAttendanceSlice(resp.GetLessonAttendance()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteLessonAttendance(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Lesson.DeleteLessonAttendance(ctx, &pb.DeleteLessonAttendanceRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListLessonVideo — gRPC list with optional search filter.
func (r *queryResolver) ListLessonVideo(ctx context.Context, search *model.SearchInput) (*model.LessonVideoListResult, error) {
	resp, err := r.Clients.Lesson.ListLessonVideo(ctx, &pb.ListLessonVideoRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.LessonVideoListResult{
		Items:    convert.PBToLessonVideoSlice(resp.GetLessonVideo()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// lessonVideo — single-fetch by id (uses DataLoader).
func (r *queryResolver) LessonVideo(ctx context.Context, id string) (*model.LessonVideo, error) {
	item, err := dataloader.For(ctx).LessonVideo.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToLessonVideo(item), nil
}

func (r *mutationResolver) CreateLessonVideo(ctx context.Context, input model.CreateLessonVideoInput) (*model.LessonVideo, error) {
	resp, err := r.Clients.Lesson.CreateLessonVideo(ctx, convert.CreateLessonVideoInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToLessonVideo(resp.GetLessonVideo()), nil
}

func (r *mutationResolver) UpdateLessonVideo(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateLessonVideoInput) (*model.LessonVideoBatchResult, error) {
	resp, err := r.Clients.Lesson.UpdateLessonVideo(ctx, convert.UpdateLessonVideoInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.LessonVideoBatchResult{
		Items:         convert.PBToLessonVideoSlice(resp.GetLessonVideo()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteLessonVideo(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Lesson.DeleteLessonVideo(ctx, &pb.DeleteLessonVideoRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

func (r *lessonResolver) Attendance(ctx context.Context, obj *model.Lesson, search *model.SearchInput) ([]*model.LessonAttendance, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "lesson_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Lesson.ListLessonAttendance(ctx, &pb.ListLessonAttendanceRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToLessonAttendanceSlice(resp.GetLessonAttendance()), nil
}

func (r *lessonResolver) Class(ctx context.Context, obj *model.Lesson) (*model.Class, error) {
	if obj.ClassID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Class.Load(ctx, obj.ClassID)()
	if err != nil { return nil, nil }
	return convert.PBToClass(item), nil
}

func (r *lessonResolver) Videos(ctx context.Context, obj *model.Lesson, search *model.SearchInput) ([]*model.LessonVideo, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "lesson_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Lesson.ListLessonVideo(ctx, &pb.ListLessonVideoRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToLessonVideoSlice(resp.GetLessonVideo()), nil
}

func (r *lessonAttendanceResolver) Lesson(ctx context.Context, obj *model.LessonAttendance) (*model.Lesson, error) {
	if obj.LessonID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Lesson.Load(ctx, obj.LessonID)()
	if err != nil { return nil, nil }
	return convert.PBToLesson(item), nil
}

func (r *lessonAttendanceResolver) Student(ctx context.Context, obj *model.LessonAttendance) (*model.User, error) {
	if obj.StudentID == "" { return nil, nil }
	item, err := dataloader.For(ctx).User.Load(ctx, obj.StudentID)()
	if err != nil { return nil, nil }
	return convert.PBToUser(item), nil
}

func (r *lessonVideoResolver) Lesson(ctx context.Context, obj *model.LessonVideo) (*model.Lesson, error) {
	if obj.LessonID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Lesson.Load(ctx, obj.LessonID)()
	if err != nil { return nil, nil }
	return convert.PBToLesson(item), nil
}

