// Code generated by grpc-gen. DO NOT EDIT.
// Resolver bodies for service "notification".

package resolver

import (
	"context"

	commonpb "github.com/thaily/lms/proto/common"
	pb "github.com/thaily/lms/proto/notification"
	userpb "github.com/thaily/lms/proto/user"
	"github.com/thaily/lms/src/server/graph/convert"
	"github.com/thaily/lms/src/server/graph/dataloader"
	"github.com/thaily/lms/src/server/graph/generated"
	"github.com/thaily/lms/src/server/graph/model"
)

var _ = context.Background
var _ = commonpb.FilterOperator(0)
var _ = pb.File_proto_notification_notification_proto
var _ = userpb.File_proto_user_user_proto
var _ = model.SearchInput{}
var _ = convert.SearchInputToPB
var _ = dataloader.For

func (r *Resolver) CommunityReport() generated.CommunityReportResolver { return &communityReportResolver{r} }
func (r *Resolver) Notification() generated.NotificationResolver { return &notificationResolver{r} }
type communityReportResolver struct{ *Resolver }
type notificationResolver struct{ *Resolver }

// ListCommunityReport — gRPC list with optional search filter.
func (r *queryResolver) ListCommunityReport(ctx context.Context, search *model.SearchInput) (*model.CommunityReportListResult, error) {
	resp, err := r.Clients.Notification.ListCommunityReport(ctx, &pb.ListCommunityReportRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.CommunityReportListResult{
		Items:    convert.PBToCommunityReportSlice(resp.GetCommunityReport()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// communityReport — single-fetch by id (uses DataLoader).
func (r *queryResolver) CommunityReport(ctx context.Context, id string) (*model.CommunityReport, error) {
	item, err := dataloader.For(ctx).CommunityReport.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToCommunityReport(item), nil
}

func (r *mutationResolver) CreateCommunityReport(ctx context.Context, input model.CreateCommunityReportInput) (*model.CommunityReport, error) {
	resp, err := r.Clients.Notification.CreateCommunityReport(ctx, convert.CreateCommunityReportInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToCommunityReport(resp.GetCommunityReport()), nil
}

func (r *mutationResolver) UpdateCommunityReport(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateCommunityReportInput) (*model.CommunityReportBatchResult, error) {
	resp, err := r.Clients.Notification.UpdateCommunityReport(ctx, convert.UpdateCommunityReportInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.CommunityReportBatchResult{
		Items:         convert.PBToCommunityReportSlice(resp.GetCommunityReport()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteCommunityReport(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Notification.DeleteCommunityReport(ctx, &pb.DeleteCommunityReportRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListNotification — gRPC list with optional search filter.
func (r *queryResolver) ListNotification(ctx context.Context, search *model.SearchInput) (*model.NotificationListResult, error) {
	resp, err := r.Clients.Notification.ListNotification(ctx, &pb.ListNotificationRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.NotificationListResult{
		Items:    convert.PBToNotificationSlice(resp.GetNotification()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// notification — single-fetch by id (uses DataLoader).
func (r *queryResolver) Notification(ctx context.Context, id string) (*model.Notification, error) {
	item, err := dataloader.For(ctx).Notification.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToNotification(item), nil
}

func (r *mutationResolver) CreateNotification(ctx context.Context, input model.CreateNotificationInput) (*model.Notification, error) {
	resp, err := r.Clients.Notification.CreateNotification(ctx, convert.CreateNotificationInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToNotification(resp.GetNotification()), nil
}

func (r *mutationResolver) UpdateNotification(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateNotificationInput) (*model.NotificationBatchResult, error) {
	resp, err := r.Clients.Notification.UpdateNotification(ctx, convert.UpdateNotificationInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.NotificationBatchResult{
		Items:         convert.PBToNotificationSlice(resp.GetNotification()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteNotification(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Notification.DeleteNotification(ctx, &pb.DeleteNotificationRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

func (r *communityReportResolver) Reporter(ctx context.Context, obj *model.CommunityReport) (*model.User, error) {
	if obj.ReporterUserID == "" { return nil, nil }
	item, err := dataloader.For(ctx).User.Load(ctx, obj.ReporterUserID)()
	if err != nil { return nil, nil }
	return convert.PBToUser(item), nil
}

func (r *notificationResolver) User(ctx context.Context, obj *model.Notification) (*model.User, error) {
	if obj.UserID == "" { return nil, nil }
	item, err := dataloader.For(ctx).User.Load(ctx, obj.UserID)()
	if err != nil { return nil, nil }
	return convert.PBToUser(item), nil
}

