// Code generated by grpc-gen. DO NOT EDIT.
package resolver

import (
	"github.com/thaily/lms/src/server/graph/client"
	"github.com/thaily/lms/src/server/graph/domain"
)

// Resolver is the dependency holder injected into every gqlgen resolver.
// main.go wires Clients + Actions.
type Resolver struct {
	Clients *client.Clients
	Actions *domain.ActionEngine
}
