// Code generated by grpc-gen. DO NOT EDIT.
// Resolver bodies for service "submission".

package resolver

import (
	"context"

	commonpb "github.com/thaily/lms/proto/common"
	exampb "github.com/thaily/lms/proto/exam"
	pb "github.com/thaily/lms/proto/submission"
	userpb "github.com/thaily/lms/proto/user"
	"github.com/thaily/lms/src/server/graph/convert"
	"github.com/thaily/lms/src/server/graph/dataloader"
	"github.com/thaily/lms/src/server/graph/generated"
	"github.com/thaily/lms/src/server/graph/model"
)

var _ = context.Background
var _ = commonpb.FilterOperator(0)
var _ = exampb.File_proto_exam_exam_proto
var _ = pb.File_proto_submission_submission_proto
var _ = userpb.File_proto_user_user_proto
var _ = model.SearchInput{}
var _ = convert.SearchInputToPB
var _ = dataloader.For

func (r *Resolver) AttemptAnswer() generated.AttemptAnswerResolver { return &attemptAnswerResolver{r} }
func (r *Resolver) ExamAttempt() generated.ExamAttemptResolver { return &examAttemptResolver{r} }
type attemptAnswerResolver struct{ *Resolver }
type examAttemptResolver struct{ *Resolver }

// ListAttemptAnswer — gRPC list with optional search filter.
func (r *queryResolver) ListAttemptAnswer(ctx context.Context, search *model.SearchInput) (*model.AttemptAnswerListResult, error) {
	resp, err := r.Clients.Submission.ListAttemptAnswer(ctx, &pb.ListAttemptAnswerRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.AttemptAnswerListResult{
		Items:    convert.PBToAttemptAnswerSlice(resp.GetAttemptAnswer()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// attemptAnswer — single-fetch by id (uses DataLoader).
func (r *queryResolver) AttemptAnswer(ctx context.Context, id string) (*model.AttemptAnswer, error) {
	item, err := dataloader.For(ctx).AttemptAnswer.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToAttemptAnswer(item), nil
}

func (r *mutationResolver) CreateAttemptAnswer(ctx context.Context, input model.CreateAttemptAnswerInput) (*model.AttemptAnswer, error) {
	resp, err := r.Clients.Submission.CreateAttemptAnswer(ctx, convert.CreateAttemptAnswerInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToAttemptAnswer(resp.GetAttemptAnswer()), nil
}

func (r *mutationResolver) UpdateAttemptAnswer(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateAttemptAnswerInput) (*model.AttemptAnswerBatchResult, error) {
	resp, err := r.Clients.Submission.UpdateAttemptAnswer(ctx, convert.UpdateAttemptAnswerInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.AttemptAnswerBatchResult{
		Items:         convert.PBToAttemptAnswerSlice(resp.GetAttemptAnswer()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteAttemptAnswer(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Submission.DeleteAttemptAnswer(ctx, &pb.DeleteAttemptAnswerRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListExamAttempt — gRPC list with optional search filter.
func (r *queryResolver) ListExamAttempt(ctx context.Context, search *model.SearchInput) (*model.ExamAttemptListResult, error) {
	resp, err := r.Clients.Submission.ListExamAttempt(ctx, &pb.ListExamAttemptRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.ExamAttemptListResult{
		Items:    convert.PBToExamAttemptSlice(resp.GetExamAttempt()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// examAttempt — single-fetch by id (uses DataLoader).
func (r *queryResolver) ExamAttempt(ctx context.Context, id string) (*model.ExamAttempt, error) {
	item, err := dataloader.For(ctx).ExamAttempt.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToExamAttempt(item), nil
}

func (r *mutationResolver) CreateExamAttempt(ctx context.Context, input model.CreateExamAttemptInput) (*model.ExamAttempt, error) {
	resp, err := r.Clients.Submission.CreateExamAttempt(ctx, convert.CreateExamAttemptInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToExamAttempt(resp.GetExamAttempt()), nil
}

func (r *mutationResolver) UpdateExamAttempt(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateExamAttemptInput) (*model.ExamAttemptBatchResult, error) {
	resp, err := r.Clients.Submission.UpdateExamAttempt(ctx, convert.UpdateExamAttemptInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.ExamAttemptBatchResult{
		Items:         convert.PBToExamAttemptSlice(resp.GetExamAttempt()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteExamAttempt(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.Submission.DeleteExamAttempt(ctx, &pb.DeleteExamAttemptRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

func (r *attemptAnswerResolver) Attempt(ctx context.Context, obj *model.AttemptAnswer) (*model.ExamAttempt, error) {
	if obj.AttemptID == "" { return nil, nil }
	item, err := dataloader.For(ctx).ExamAttempt.Load(ctx, obj.AttemptID)()
	if err != nil { return nil, nil }
	return convert.PBToExamAttempt(item), nil
}

func (r *attemptAnswerResolver) Question(ctx context.Context, obj *model.AttemptAnswer) (*model.Question, error) {
	if obj.QuestionID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Question.Load(ctx, obj.QuestionID)()
	if err != nil { return nil, nil }
	return convert.PBToQuestion(item), nil
}

func (r *examAttemptResolver) Answers(ctx context.Context, obj *model.ExamAttempt, search *model.SearchInput) ([]*model.AttemptAnswer, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "attempt_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Submission.ListAttemptAnswer(ctx, &pb.ListAttemptAnswerRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToAttemptAnswerSlice(resp.GetAttemptAnswer()), nil
}

func (r *examAttemptResolver) Exam(ctx context.Context, obj *model.ExamAttempt) (*model.Exam, error) {
	if obj.ExamID == "" { return nil, nil }
	item, err := dataloader.For(ctx).Exam.Load(ctx, obj.ExamID)()
	if err != nil { return nil, nil }
	return convert.PBToExam(item), nil
}

func (r *examAttemptResolver) Student(ctx context.Context, obj *model.ExamAttempt) (*model.User, error) {
	if obj.StudentID == "" { return nil, nil }
	item, err := dataloader.For(ctx).User.Load(ctx, obj.StudentID)()
	if err != nil { return nil, nil }
	return convert.PBToUser(item), nil
}

