// Code generated by grpc-gen. DO NOT EDIT.
// Resolver bodies for service "user".

package resolver

import (
	"context"

	commonpb "github.com/thaily/lms/proto/common"
	classpb "github.com/thaily/lms/proto/class"
	pb "github.com/thaily/lms/proto/user"
	"github.com/thaily/lms/src/server/graph/convert"
	"github.com/thaily/lms/src/server/graph/dataloader"
	"github.com/thaily/lms/src/server/graph/generated"
	"github.com/thaily/lms/src/server/graph/model"
)

var _ = context.Background
var _ = commonpb.FilterOperator(0)
var _ = classpb.File_proto_class_class_proto
var _ = pb.File_proto_user_user_proto
var _ = model.SearchInput{}
var _ = convert.SearchInputToPB
var _ = dataloader.For

func (r *Resolver) StudentProfile() generated.StudentProfileResolver { return &studentProfileResolver{r} }
func (r *Resolver) TeacherProfile() generated.TeacherProfileResolver { return &teacherProfileResolver{r} }
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }
type studentProfileResolver struct{ *Resolver }
type teacherProfileResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// ListPasswordReset — gRPC list with optional search filter.
func (r *queryResolver) ListPasswordReset(ctx context.Context, search *model.SearchInput) (*model.PasswordResetListResult, error) {
	resp, err := r.Clients.User.ListPasswordReset(ctx, &pb.ListPasswordResetRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.PasswordResetListResult{
		Items:    convert.PBToPasswordResetSlice(resp.GetPasswordReset()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// passwordReset — single-fetch by id (uses DataLoader).
func (r *queryResolver) PasswordReset(ctx context.Context, id string) (*model.PasswordReset, error) {
	item, err := dataloader.For(ctx).PasswordReset.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToPasswordReset(item), nil
}

func (r *mutationResolver) CreatePasswordReset(ctx context.Context, input model.CreatePasswordResetInput) (*model.PasswordReset, error) {
	resp, err := r.Clients.User.CreatePasswordReset(ctx, convert.CreatePasswordResetInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToPasswordReset(resp.GetPasswordReset()), nil
}

func (r *mutationResolver) UpdatePasswordReset(ctx context.Context, filters []*model.FilterCriteria, input model.UpdatePasswordResetInput) (*model.PasswordResetBatchResult, error) {
	resp, err := r.Clients.User.UpdatePasswordReset(ctx, convert.UpdatePasswordResetInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.PasswordResetBatchResult{
		Items:         convert.PBToPasswordResetSlice(resp.GetPasswordReset()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeletePasswordReset(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.User.DeletePasswordReset(ctx, &pb.DeletePasswordResetRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListRefreshToken — gRPC list with optional search filter.
func (r *queryResolver) ListRefreshToken(ctx context.Context, search *model.SearchInput) (*model.RefreshTokenListResult, error) {
	resp, err := r.Clients.User.ListRefreshToken(ctx, &pb.ListRefreshTokenRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.RefreshTokenListResult{
		Items:    convert.PBToRefreshTokenSlice(resp.GetRefreshToken()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// refreshToken — single-fetch by id (uses DataLoader).
func (r *queryResolver) RefreshToken(ctx context.Context, id string) (*model.RefreshToken, error) {
	item, err := dataloader.For(ctx).RefreshToken.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToRefreshToken(item), nil
}

func (r *mutationResolver) CreateRefreshToken(ctx context.Context, input model.CreateRefreshTokenInput) (*model.RefreshToken, error) {
	resp, err := r.Clients.User.CreateRefreshToken(ctx, convert.CreateRefreshTokenInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToRefreshToken(resp.GetRefreshToken()), nil
}

func (r *mutationResolver) UpdateRefreshToken(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateRefreshTokenInput) (*model.RefreshTokenBatchResult, error) {
	resp, err := r.Clients.User.UpdateRefreshToken(ctx, convert.UpdateRefreshTokenInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.RefreshTokenBatchResult{
		Items:         convert.PBToRefreshTokenSlice(resp.GetRefreshToken()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteRefreshToken(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.User.DeleteRefreshToken(ctx, &pb.DeleteRefreshTokenRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListStudentProfile — gRPC list with optional search filter.
func (r *queryResolver) ListStudentProfile(ctx context.Context, search *model.SearchInput) (*model.StudentProfileListResult, error) {
	resp, err := r.Clients.User.ListStudentProfile(ctx, &pb.ListStudentProfileRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.StudentProfileListResult{
		Items:    convert.PBToStudentProfileSlice(resp.GetStudentProfile()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// studentProfile — single-fetch by id (uses DataLoader).
func (r *queryResolver) StudentProfile(ctx context.Context, id string) (*model.StudentProfile, error) {
	item, err := dataloader.For(ctx).StudentProfile.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToStudentProfile(item), nil
}

func (r *mutationResolver) CreateStudentProfile(ctx context.Context, input model.CreateStudentProfileInput) (*model.StudentProfile, error) {
	resp, err := r.Clients.User.CreateStudentProfile(ctx, convert.CreateStudentProfileInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToStudentProfile(resp.GetStudentProfile()), nil
}

func (r *mutationResolver) UpdateStudentProfile(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateStudentProfileInput) (*model.StudentProfileBatchResult, error) {
	resp, err := r.Clients.User.UpdateStudentProfile(ctx, convert.UpdateStudentProfileInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.StudentProfileBatchResult{
		Items:         convert.PBToStudentProfileSlice(resp.GetStudentProfile()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteStudentProfile(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.User.DeleteStudentProfile(ctx, &pb.DeleteStudentProfileRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListTeacherProfile — gRPC list with optional search filter.
func (r *queryResolver) ListTeacherProfile(ctx context.Context, search *model.SearchInput) (*model.TeacherProfileListResult, error) {
	resp, err := r.Clients.User.ListTeacherProfile(ctx, &pb.ListTeacherProfileRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.TeacherProfileListResult{
		Items:    convert.PBToTeacherProfileSlice(resp.GetTeacherProfile()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// teacherProfile — single-fetch by id (uses DataLoader).
func (r *queryResolver) TeacherProfile(ctx context.Context, id string) (*model.TeacherProfile, error) {
	item, err := dataloader.For(ctx).TeacherProfile.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToTeacherProfile(item), nil
}

func (r *mutationResolver) CreateTeacherProfile(ctx context.Context, input model.CreateTeacherProfileInput) (*model.TeacherProfile, error) {
	resp, err := r.Clients.User.CreateTeacherProfile(ctx, convert.CreateTeacherProfileInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToTeacherProfile(resp.GetTeacherProfile()), nil
}

func (r *mutationResolver) UpdateTeacherProfile(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateTeacherProfileInput) (*model.TeacherProfileBatchResult, error) {
	resp, err := r.Clients.User.UpdateTeacherProfile(ctx, convert.UpdateTeacherProfileInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.TeacherProfileBatchResult{
		Items:         convert.PBToTeacherProfileSlice(resp.GetTeacherProfile()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteTeacherProfile(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.User.DeleteTeacherProfile(ctx, &pb.DeleteTeacherProfileRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

// ListUser — gRPC list with optional search filter.
func (r *queryResolver) ListUser(ctx context.Context, search *model.SearchInput) (*model.UserListResult, error) {
	resp, err := r.Clients.User.ListUser(ctx, &pb.ListUserRequest{Search: convert.SearchInputToPB(search)})
	if err != nil { return nil, err }
	return &model.UserListResult{
		Items:    convert.PBToUserSlice(resp.GetUser()),
		Total:    int(resp.GetTotal()),
		Page:     int(resp.GetPage()),
		PageSize: int(resp.GetPageSize()),
	}, nil
}

// user — single-fetch by id (uses DataLoader).
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	item, err := dataloader.For(ctx).User.Load(ctx, id)()
	if err != nil { return nil, nil } // treat not-found as null
	return convert.PBToUser(item), nil
}

func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	resp, err := r.Clients.User.CreateUser(ctx, convert.CreateUserInputToPB(input))
	if err != nil { return nil, err }
	return convert.PBToUser(resp.GetUser()), nil
}

func (r *mutationResolver) UpdateUser(ctx context.Context, filters []*model.FilterCriteria, input model.UpdateUserInput) (*model.UserBatchResult, error) {
	resp, err := r.Clients.User.UpdateUser(ctx, convert.UpdateUserInputToPB(filters, input))
	if err != nil { return nil, err }
	return &model.UserBatchResult{
		Items:         convert.PBToUserSlice(resp.GetUser()),
		AffectedCount: int(resp.GetAffectedCount()),
	}, nil
}

func (r *mutationResolver) DeleteUser(ctx context.Context, filters []*model.FilterCriteria) (*model.DeleteResult, error) {
	resp, err := r.Clients.User.DeleteUser(ctx, &pb.DeleteUserRequest{Filters: convert.FilterCriteriaInputSliceToPB(filters)})
	if err != nil { return nil, err }
	return &model.DeleteResult{AffectedCount: int(resp.GetAffectedCount())}, nil
}

func (r *studentProfileResolver) User(ctx context.Context, obj *model.StudentProfile) (*model.User, error) {
	if obj.UserID == "" { return nil, nil }
	item, err := dataloader.For(ctx).User.Load(ctx, obj.UserID)()
	if err != nil { return nil, nil }
	return convert.PBToUser(item), nil
}

func (r *teacherProfileResolver) User(ctx context.Context, obj *model.TeacherProfile) (*model.User, error) {
	if obj.UserID == "" { return nil, nil }
	item, err := dataloader.For(ctx).User.Load(ctx, obj.UserID)()
	if err != nil { return nil, nil }
	return convert.PBToUser(item), nil
}

func (r *userResolver) Enrollments(ctx context.Context, obj *model.User, search *model.SearchInput) ([]*model.Enrollment, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "student_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Class.ListEnrollment(ctx, &classpb.ListEnrollmentRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToEnrollmentSlice(resp.GetEnrollment()), nil
}

func (r *userResolver) StudentProfile(ctx context.Context, obj *model.User) (*model.StudentProfile, error) {
	resp, err := r.Clients.User.ListStudentProfile(ctx, &pb.ListStudentProfileRequest{
		Search: &commonpb.SearchRequest{
			Filters: []*commonpb.FilterCriteria{{
				Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
					Field:    "user_id",
					Operator: commonpb.FilterOperator_EQUAL,
					Values:   []string{obj.ID},
				}},
			}},
			Pagination: &commonpb.Pagination{PageSize: 1},
		},
	})
	if err != nil || len(resp.GetStudentProfile()) == 0 { return nil, nil }
	return convert.PBToStudentProfile(resp.GetStudentProfile()[0]), nil
}

func (r *userResolver) TaughtClasses(ctx context.Context, obj *model.User, search *model.SearchInput) ([]*model.Class, error) {
	pbSearch := convert.SearchInputToPB(search)
	if pbSearch == nil { pbSearch = &commonpb.SearchRequest{} }
	pbSearch.Filters = append(pbSearch.Filters, &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
			Field:    "teacher_id",
			Operator: commonpb.FilterOperator_EQUAL,
			Values:   []string{obj.ID},
		}},
	})
	resp, err := r.Clients.Class.ListClass(ctx, &classpb.ListClassRequest{Search: pbSearch})
	if err != nil { return nil, err }
	return convert.PBToClassSlice(resp.GetClass()), nil
}

func (r *userResolver) TeacherProfile(ctx context.Context, obj *model.User) (*model.TeacherProfile, error) {
	resp, err := r.Clients.User.ListTeacherProfile(ctx, &pb.ListTeacherProfileRequest{
		Search: &commonpb.SearchRequest{
			Filters: []*commonpb.FilterCriteria{{
				Criteria: &commonpb.FilterCriteria_Condition{Condition: &commonpb.FilterCondition{
					Field:    "user_id",
					Operator: commonpb.FilterOperator_EQUAL,
					Values:   []string{obj.ID},
				}},
			}},
			Pagination: &commonpb.Pagination{PageSize: 1},
		},
	})
	if err != nil || len(resp.GetTeacherProfile()) == 0 { return nil, nil }
	return convert.PBToTeacherProfile(resp.GetTeacherProfile()[0]), nil
}

