// Code generated by grpc-gen. DO NOT EDIT.
// Two-layer cache shared by graph/client (gRPC response cache) and
// graph/dataloader (per-id cache). Scope is per-viewer; invalidation is
// pattern-based on mutation. See keys.go for the key layout.

package cache

import (
	"context"
	"time"
)

// Cache is the minimal interface the gateway uses. Implementations must be
// safe for concurrent use. Get returns (nil, false, nil) on a clean miss.
type Cache interface {
	Get(ctx context.Context, key string) ([]byte, bool, error)
	Set(ctx context.Context, key string, val []byte, ttl time.Duration) error
	Del(ctx context.Context, keys ...string) error
	// DelByPattern removes every key matching the glob pattern (Redis SCAN
	// semantics). Used by mutation invalidation to wipe all viewers' entries
	// for an affected entity.
	DelByPattern(ctx context.Context, pattern string) error
}
