// Code generated by grpc-gen. DO NOT EDIT.
// Key layout:
//   entity load:   e:<Type>:v:<ViewerID>:id:<id>
//   list result:   e:<Type>:v:<ViewerID>:list:<hash>
// Invalidation patterns (cross-viewer):
//   single id:     e:<Type>:v:*:id:<id>
//   any list:      e:<Type>:v:*:list:*

package cache

import (
	"crypto/sha1"
	"encoding/hex"
)

// ViewerAnon is the key segment used for unauthenticated requests so an
// empty UserID can't accidentally collide with a real viewer.
const ViewerAnon = "anon"

func EntityKey(typ, viewerID, id string) string {
	if viewerID == "" {
		viewerID = ViewerAnon
	}
	return "e:" + typ + ":v:" + viewerID + ":id:" + id
}

func ListKey(typ, viewerID, hash string) string {
	if viewerID == "" {
		viewerID = ViewerAnon
	}
	return "e:" + typ + ":v:" + viewerID + ":list:" + hash
}

func EntityPattern(typ, id string) string {
	return "e:" + typ + ":v:*:id:" + id
}

func ListPattern(typ string) string {
	return "e:" + typ + ":v:*:list:*"
}

// HashBytes turns a marshalled proto request into a stable cache key
// fragment. SHA-1 truncated to 16 chars is enough collision resistance
// for cache keys (cardinality bounded by distinct queries per viewer).
func HashBytes(b []byte) string {
	sum := sha1.Sum(b)
	return hex.EncodeToString(sum[:])[:16]
}
