// Code generated by grpc-gen. DO NOT EDIT.
// Noop is the zero-impact Cache: every Get is a miss, every Set/Del is a
// no-op. Use it when CACHE_REDIS_ADDR is unset so the gateway still works
// (just without caching).

package cache

import (
	"context"
	"time"
)

type Noop struct{}

func (Noop) Get(context.Context, string) ([]byte, bool, error)         { return nil, false, nil }
func (Noop) Set(context.Context, string, []byte, time.Duration) error  { return nil }
func (Noop) Del(context.Context, ...string) error                      { return nil }
func (Noop) DelByPattern(context.Context, string) error                { return nil }
