// Code generated by grpc-gen. DO NOT EDIT.

package cache

import (
	"context"
	"errors"
	"time"

	"github.com/redis/go-redis/v9"
)

// RedisCache implements Cache against a single go-redis client. SCAN is
// used for pattern delete to avoid the production-killer that is KEYS.
type RedisCache struct {
	rdb *redis.Client
}

// NewRedis dials Redis at addr (e.g. "localhost:6379") with the given
// password (empty for none) and selects the given DB number.
func NewRedis(addr, password string, db int) (*RedisCache, error) {
	rdb := redis.NewClient(&redis.Options{Addr: addr, Password: password, DB: db})
	if err := rdb.Ping(context.Background()).Err(); err != nil {
		return nil, err
	}
	return &RedisCache{rdb: rdb}, nil
}

func (r *RedisCache) Get(ctx context.Context, key string) ([]byte, bool, error) {
	b, err := r.rdb.Get(ctx, key).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return b, true, nil
}

func (r *RedisCache) Set(ctx context.Context, key string, val []byte, ttl time.Duration) error {
	return r.rdb.Set(ctx, key, val, ttl).Err()
}

func (r *RedisCache) Del(ctx context.Context, keys ...string) error {
	if len(keys) == 0 {
		return nil
	}
	return r.rdb.Del(ctx, keys...).Err()
}

// DelByPattern uses SCAN+DEL in batches of 500. Slow but safe vs. KEYS.
// For small-ish caches (< 1M keys) this is acceptable; switch to event-
// driven invalidation if the pattern volume grows.
func (r *RedisCache) DelByPattern(ctx context.Context, pattern string) error {
	iter := r.rdb.Scan(ctx, 0, pattern, 500).Iterator()
	batch := make([]string, 0, 500)
	flush := func() error {
		if len(batch) == 0 {
			return nil
		}
		err := r.rdb.Del(ctx, batch...).Err()
		batch = batch[:0]
		return err
	}
	for iter.Next(ctx) {
		batch = append(batch, iter.Val())
		if len(batch) >= 500 {
			if err := flush(); err != nil {
				return err
			}
		}
	}
	if err := iter.Err(); err != nil {
		return err
	}
	return flush()
}

func (r *RedisCache) Close() error { return r.rdb.Close() }
