// Code generated by grpc-gen. DO NOT EDIT.
// Source of truth: proto entity fields.
// Default: every entity field is filterable. To block a field, add
// `[(common.filterable) = false]` to it in the .proto and regen.

package handler

// CommunityReportFilterableFields is the runtime whitelist for filter conditions.
// When FILTER_STRICT is on (default), denied fields used in filters cause the
// server to return InvalidArgument listing the rejected field names.
var CommunityReportFilterableFields = map[string]bool{
	"id":                   true,
	"created_at":           true,
	"updated_at":           true,
	"created_by":           true,
	"updated_by":           true,
	"reporter_user_id":     true,
	"target_type":          true,
	"target_id":            true,
	"reason":               true,
	"note":                 true,
	"status":               true,
	"resolved_by_admin_id": true,
	"resolved_at":          true,
}
