// Code generated by grpc-gen. DO NOT EDIT.
// Runners that gqlgen invokes for the @auth and @policy schema directives.
// gqlgen.yml binds the generated DirectiveRoot.Auth / DirectiveRoot.Policy
// fields to NewAuth / NewPolicy on this package.

package directive

import (
	"context"

	"github.com/99designs/gqlgen/graphql"

	"github.com/thaily/lms/src/server/graph/auth"
	"github.com/thaily/lms/src/server/graph/policy"
)

// Bindings is the runtime config the runners read each request. main.go
// constructs it once and stuffs it into ctx (or passes it via closure).
type Bindings struct {
	Enforcer policy.Enforcer
}

type bindingsCtxKey struct{}

// WithBindings stores b on ctx for the directives to read. main.go's HTTP
// handler calls this before passing ctx to gqlgen.
func WithBindings(ctx context.Context, b *Bindings) context.Context {
	return context.WithValue(ctx, bindingsCtxKey{}, b)
}

func bindingsFromCtx(ctx context.Context) *Bindings {
	b, _ := ctx.Value(bindingsCtxKey{}).(*Bindings)
	return b
}

// Auth implements @auth(role: String!). Returns ErrUnauthenticated when there
// is no viewer, ErrForbidden when the viewer lacks the required role.
func Auth(ctx context.Context, _ any, next graphql.Resolver, role string) (any, error) {
	v := auth.FromContext(ctx)
	if v == nil {
		return nil, policy.ErrUnauthenticated
	}
	b := bindingsFromCtx(ctx)
	if b == nil || b.Enforcer == nil {
		// Fail closed when the gateway hasn't wired an enforcer.
		return nil, policy.ErrForbidden
	}
	if !b.Enforcer.HasRole(ctx, v, role) {
		return nil, policy.ErrForbidden
	}
	return next(ctx)
}

// Policy implements @policy(rule: String!). The rule string is the key the
// enforcer uses to look up a stored expression in MongoDB and evaluate it
// against the request's bindings.
func Policy(ctx context.Context, obj any, next graphql.Resolver, rule string) (any, error) {
	v := auth.FromContext(ctx)
	b := bindingsFromCtx(ctx)
	if b == nil || b.Enforcer == nil {
		return nil, policy.ErrForbidden
	}
	ok, err := b.Enforcer.EvalRule(ctx, rule, v, obj)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, policy.ErrForbidden
	}
	return next(ctx)
}
