version: '3.8'

services:
  class:
    build:
      context: ../../..
      dockerfile: src/service/class/Dockerfile
    image: github.com/thaily/lms/class:latest
    container_name: class_service
    env_file:
      - class.env
    ports:
      - "50052:50052"
    volumes:
      - .:/app/service:ro
      - ../../../logs:/app/logs
    networks:
      - class_network
    restart: unless-stopped

networks:
  class_network:
    driver: bridge
