// Code generated by grpc-gen. DO NOT EDIT.

package dataloader

import (
	"context"
	"fmt"
	"strconv"

	"github.com/graph-gophers/dataloader/v7"
	"google.golang.org/protobuf/proto"

	"github.com/thaily/lms/src/server/graph/cache"
	"github.com/thaily/lms/src/server/graph/client"
	commonpb "github.com/thaily/lms/proto/common"
	pb "github.com/thaily/lms/proto/exam"
)

type ExamAssignmentLoader = dataloader.Loader[string, *pb.ExamAssignment]

// NewExamAssignmentLoader returns a request-scoped Loader. The batch function checks the
// shared entity cache per id first (per-viewer key), only fanning out to
// gRPC for misses. Misses get written back to cache before returning.
// The gRPC call bypasses the client list cache via Stub() to avoid
// double-caching.
func NewExamAssignmentLoader(c *client.Clients) *ExamAssignmentLoader {
	batch := func(ctx context.Context, ids []string) []*dataloader.Result[*pb.ExamAssignment] {
		out := make([]*dataloader.Result[*pb.ExamAssignment], len(ids))
		vid := viewerID(ctx)
		missIdx := make([]int, 0, len(ids))
		missIDs := make([]string, 0, len(ids))

		if c.Cache != nil {
			for i, id := range ids {
				key := cache.EntityKey("ExamAssignment", vid, id)
				if b, ok, _ := c.Cache.Get(ctx, key); ok {
					var item pb.ExamAssignment
					if proto.Unmarshal(b, &item) == nil {
						out[i] = &dataloader.Result[*pb.ExamAssignment]{Data: &item}
						continue
					}
				}
				missIdx = append(missIdx, i)
				missIDs = append(missIDs, id)
			}
		} else {
			for i, id := range ids {
				missIdx = append(missIdx, i)
				missIDs = append(missIDs, id)
				_ = id
			}
		}

		if len(missIDs) == 0 { return out }

		req := &pb.ListExamAssignmentRequest{
			Search: &commonpb.SearchRequest{
				Filters: []*commonpb.FilterCriteria{{
					Criteria: &commonpb.FilterCriteria_Condition{
						Condition: &commonpb.FilterCondition{
							Field:    "id",
							Operator: commonpb.FilterOperator_IN,
							Values:   missIDs,
						},
					},
				}},
				Pagination: &commonpb.Pagination{PageSize: int32(len(missIDs))},
			},
		}
		resp, err := c.Exam.Stub().ListExamAssignment(ctx, req)
		if err != nil {
			for _, i := range missIdx { out[i] = &dataloader.Result[*pb.ExamAssignment]{Error: err} }
			return out
		}

		byID := make(map[string]*pb.ExamAssignment, len(resp.GetExamAssignment()))
		for _, item := range resp.GetExamAssignment() {
			byID[strconv.FormatUint(item.GetId(), 10)] = item
		}

		for k, i := range missIdx {
			id := missIDs[k]
			if item, ok := byID[id]; ok {
				out[i] = &dataloader.Result[*pb.ExamAssignment]{Data: item}
				if c.Cache != nil {
					if b, mErr := proto.Marshal(item); mErr == nil {
						_ = c.Cache.Set(ctx, cache.EntityKey("ExamAssignment", vid, id), b, c.TTL)
					}
				}
			} else {
				out[i] = &dataloader.Result[*pb.ExamAssignment]{Error: fmt.Errorf("ExamAssignment id %s not found", id)}
			}
		}
		return out
	}
	return dataloader.NewBatchedLoader(batch)
}
