// Code generated by grpc-gen. DO NOT EDIT.
// Per-request DataLoader bundle. Created once per HTTP request by the
// gateway middleware so cached responses can't leak between viewers.

package dataloader

import (
	"context"

	"github.com/graph-gophers/dataloader/v7"

	"github.com/thaily/lms/src/server/graph/auth"
	"github.com/thaily/lms/src/server/graph/client"
)

// Loaders aggregates one DataLoader per entity.
type Loaders struct {
	AttemptAnswer *AttemptAnswerLoader
	AuditLog *AuditLogLoader
	Class *ClassLoader
	ClassInviteKey *ClassInviteKeyLoader
	CommunityReport *CommunityReportLoader
	Enrollment *EnrollmentLoader
	Exam *ExamLoader
	ExamAssignment *ExamAssignmentLoader
	ExamAttempt *ExamAttemptLoader
	Lesson *LessonLoader
	LessonAttendance *LessonAttendanceLoader
	LessonVideo *LessonVideoLoader
	Material *MaterialLoader
	MaterialClass *MaterialClassLoader
	MaterialTag *MaterialTagLoader
	Notification *NotificationLoader
	PasswordReset *PasswordResetLoader
	Question *QuestionLoader
	QuestionAnswer *QuestionAnswerLoader
	QuestionChoice *QuestionChoiceLoader
	RefreshToken *RefreshTokenLoader
	StudentProfile *StudentProfileLoader
	TeacherProfile *TeacherProfileLoader
	User *UserLoader
}

// New builds a fresh Loaders bundle. Call once per HTTP request.
func New(c *client.Clients) *Loaders {
	return &Loaders{
		AttemptAnswer: NewAttemptAnswerLoader(c),
		AuditLog: NewAuditLogLoader(c),
		Class: NewClassLoader(c),
		ClassInviteKey: NewClassInviteKeyLoader(c),
		CommunityReport: NewCommunityReportLoader(c),
		Enrollment: NewEnrollmentLoader(c),
		Exam: NewExamLoader(c),
		ExamAssignment: NewExamAssignmentLoader(c),
		ExamAttempt: NewExamAttemptLoader(c),
		Lesson: NewLessonLoader(c),
		LessonAttendance: NewLessonAttendanceLoader(c),
		LessonVideo: NewLessonVideoLoader(c),
		Material: NewMaterialLoader(c),
		MaterialClass: NewMaterialClassLoader(c),
		MaterialTag: NewMaterialTagLoader(c),
		Notification: NewNotificationLoader(c),
		PasswordReset: NewPasswordResetLoader(c),
		Question: NewQuestionLoader(c),
		QuestionAnswer: NewQuestionAnswerLoader(c),
		QuestionChoice: NewQuestionChoiceLoader(c),
		RefreshToken: NewRefreshTokenLoader(c),
		StudentProfile: NewStudentProfileLoader(c),
		TeacherProfile: NewTeacherProfileLoader(c),
		User: NewUserLoader(c),
	}
}

type ctxKey struct{}

// WithContext stashes the Loaders for the current request.
func WithContext(ctx context.Context, l *Loaders) context.Context {
	return context.WithValue(ctx, ctxKey{}, l)
}

// For retrieves the Loaders previously stored on ctx. Panics if the
// middleware hasn't run — that's a wiring bug, not a runtime one.
func For(ctx context.Context) *Loaders {
	l, _ := ctx.Value(ctxKey{}).(*Loaders)
	if l == nil {
		panic("dataloader.For called before WithContext; did you forget the middleware?")
	}
	return l
}

// viewerID extracts the request's user id (or empty string for anon).
// Cache key builders treat the empty string as cache.ViewerAnon.
func viewerID(ctx context.Context) string {
	v := auth.FromContext(ctx)
	if v == nil { return "" }
	return v.UserID
}

// errResults wraps a single batch-level error into per-key Result entries
// so dataloader callers see the failure on every requested key.
func errResults[T any](ids []string, err error) []*dataloader.Result[T] {
	out := make([]*dataloader.Result[T], len(ids))
	for i := range ids {
		out[i] = &dataloader.Result[T]{Error: err}
	}
	return out
}
