version: '3.8'

services:
  submission:
    build:
      context: ../../..
      dockerfile: src/service/submission/Dockerfile
    image: github.com/thaily/lms/submission:latest
    container_name: submission_service
    env_file:
      - submission.env
    ports:
      - "50056:50056"
    volumes:
      - .:/app/service:ro
      - ../../../logs:/app/logs
    networks:
      - submission_network
    restart: unless-stopped

networks:
  submission_network:
    driver: bridge
