// Code generated by grpc-gen. DO NOT EDIT.
// Source of truth: proto entity fields.
// Default: every entity field is filterable. To block a field, add
// `[(common.filterable) = false]` to it in the .proto and regen.

package handler

// ExamFilterableFields is the runtime whitelist for filter conditions.
// When FILTER_STRICT is on (default), denied fields used in filters cause the
// server to return InvalidArgument listing the rejected field names.
var ExamFilterableFields = map[string]bool{
	"id":                true,
	"created_at":        true,
	"updated_at":        true,
	"created_by":        true,
	"updated_by":        true,
	"owner_teacher_id":  true,
	"title":             true,
	"description":       true,
	"subject":           true,
	"duration_min":      true,
	"total_points":      true,
	"visibility":        true,
	"community_status":  true,
	"reject_reason":     true,
	"shuffle_questions": true,
	"shuffle_choices":   true,
	"show_result_mode":  true,
}
