// Code generated by grpc-gen. DO NOT EDIT.
// Source of truth: proto entity fields.
// Default: every entity field is filterable. To block a field, add
// `[(common.filterable) = false]` to it in the .proto and regen.

package handler

// QuestionAnswerFilterableFields is the runtime whitelist for filter conditions.
// When FILTER_STRICT is on (default), denied fields used in filters cause the
// server to return InvalidArgument listing the rejected field names.
var QuestionAnswerFilterableFields = map[string]bool{
	"id":              true,
	"created_at":      true,
	"updated_at":      true,
	"created_by":      true,
	"updated_by":      true,
	"question_id":     true,
	"accepted_answer": true,
	"case_sensitive":  true,
}
