// Code generated by grpc-gen. Edit freely — re-running add-gateway WON'T
// clobber this file (it skips if already present). Treat as the project's
// own bootstrap; the generator just lays down a reasonable starting point.

package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/golang-jwt/jwt/v5"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"

	"github.com/thaily/lms/src/server/graph/auth"
	"github.com/thaily/lms/src/server/graph/cache"
	"github.com/thaily/lms/src/server/graph/client"
	"github.com/thaily/lms/src/server/graph/dataloader"
	"github.com/thaily/lms/src/server/graph/directive"
	"github.com/thaily/lms/src/server/graph/domain"
	"github.com/thaily/lms/src/server/graph/generated"
	"github.com/thaily/lms/src/server/graph/policy"
	"github.com/thaily/lms/src/server/graph/resolver"
)

func main() {
	dialOpts, err := buildDialOpts()
	if err != nil {
		log.Fatalf("dial opts: %v", err)
	}

	// Business-rule engine. The interceptor is appended to dialOpts BEFORE
	// the clients are dialed; the engine itself (which needs the clients) is
	// built afterwards and handed to the interceptor via the closure.
	ruleStore := buildRuleStore()
	actionStore := buildActionStore()
	var ruleEngine *domain.Engine
	if ruleStore != nil {
		dialOpts = append(dialOpts, grpc.WithChainUnaryInterceptor(
			domain.UnaryInterceptor(func() *domain.Engine { return ruleEngine })))
	}

	cacheBackend, cacheTTL := buildCache()
	clients, err := client.NewClients(client.Endpoints{
		Audit: env("AUDIT_SERVICE_ADDR", "localhost:50051"),
		Class: env("CLASS_SERVICE_ADDR", "localhost:50051"),
		Exam: env("EXAM_SERVICE_ADDR", "localhost:50051"),
		Lesson: env("LESSON_SERVICE_ADDR", "localhost:50051"),
		Material: env("MATERIAL_SERVICE_ADDR", "localhost:50051"),
		Notification: env("NOTIFICATION_SERVICE_ADDR", "localhost:50051"),
		Submission: env("SUBMISSION_SERVICE_ADDR", "localhost:50051"),
		User: env("USER_SERVICE_ADDR", "localhost:50051"),
	}, cacheBackend, cacheTTL, dialOpts...)
	if err != nil {
		log.Fatalf("client.NewClients: %v", err)
	}
	defer clients.Close()

	registry := domain.NewRegistry(clients)
	if ruleStore != nil {
		ruleEngine = domain.NewEngine(ruleStore, registry)
		log.Printf("✅ business rules: %d operation(s) guarded", ruleStore.OperationCount())
	}
	var actionEngine *domain.ActionEngine
	if actionStore != nil {
		actionEngine = domain.NewActionEngine(actionStore, registry, clients)
		log.Printf("✅ actions: %d loaded", actionStore.Count())
	}

	// Enforcer: Casbin reading policies from the policy-engine MongoDB.
	// Falls back to DenyAll (fail-closed) if Mongo is unreachable — that
	// only affects fields actually carrying an @auth/@policy directive.
	enforcer := buildEnforcer()

	gqlCfg := generated.Config{
		Resolvers: &resolver.Resolver{Clients: clients, Actions: actionEngine},
		Directives: generated.DirectiveRoot{
			Auth:   directive.Auth,
			Policy: directive.Policy,
		},
	}

	// NewDefaultServer wires the standard POST/GET/multipart/websocket
	// transports — fine for production until we need something custom.
	srv := handler.NewDefaultServer(generated.NewExecutableSchema(gqlCfg))

	bindings := &directive.Bindings{Enforcer: enforcer}

	mux := http.NewServeMux()
	mux.Handle("/", playground.Handler("GraphQL playground", "/query"))
	mux.Handle("/query", chain(srv,
		recoverMW,
		viewerMW,
		dataloaderMW(clients),
		bindingsMW(bindings),
	))

	addr := env("GATEWAY_LISTEN", ":8080")
	log.Printf("graphql gateway listening on %s (playground at /)", addr)
	if err := http.ListenAndServe(addr, mux); err != nil {
		log.Fatalf("listen: %v", err)
	}
}

// ─── HTTP middleware ────────────────────────────────────────────────────

type middleware func(http.Handler) http.Handler

func chain(h http.Handler, mws ...middleware) http.Handler {
	for i := len(mws) - 1; i >= 0; i-- {
		h = mws[i](h)
	}
	return h
}

func recoverMW(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if rec := recover(); rec != nil {
				log.Printf("panic in handler: %v", rec)
				http.Error(w, "internal error", http.StatusInternalServerError)
			}
		}()
		next.ServeHTTP(w, r)
	})
}

// viewerMW decodes an Authorization: Bearer JWT into auth.Viewer and stuffs
// it onto ctx. Anonymous requests pass through with no viewer; the @auth
// directive is what rejects them later if the field requires a role.
func viewerMW(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		if v, err := decodeJWT(r); err == nil && v != nil {
			ctx = auth.WithViewer(ctx, v)
		}
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

func dataloaderMW(clients *client.Clients) middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := dataloader.WithContext(r.Context(), dataloader.New(clients))
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

func bindingsMW(b *directive.Bindings) middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx := directive.WithBindings(r.Context(), b)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

// ─── JWT decode ─────────────────────────────────────────────────────────

// decodeJWT extracts a Bearer token, verifies it with HMAC against
// JWT_HMAC_SECRET, and maps the "sub" + "role" claims onto auth.Viewer.
// Returns (nil, nil) for anonymous requests; (nil, err) for malformed tokens.
func decodeJWT(r *http.Request) (*auth.Viewer, error) {
	hdr := r.Header.Get("Authorization")
	if hdr == "" {
		return nil, nil
	}
	parts := strings.SplitN(hdr, " ", 2)
	if len(parts) != 2 || !strings.EqualFold(parts[0], "Bearer") {
		return nil, errors.New("malformed Authorization header")
	}
	secret := os.Getenv("JWT_HMAC_SECRET")
	if secret == "" {
		return nil, errors.New("JWT_HMAC_SECRET not set")
	}
	tok, err := jwt.Parse(parts[1], func(t *jwt.Token) (any, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		return []byte(secret), nil
	})
	if err != nil || !tok.Valid {
		return nil, err
	}
	claims, ok := tok.Claims.(jwt.MapClaims)
	if !ok {
		return nil, errors.New("non-map claims")
	}
	sub, _ := claims["sub"].(string)
	role, _ := claims["role"].(string)
	return &auth.Viewer{UserID: sub, Role: role}, nil
}

// ─── Cache backend ──────────────────────────────────────────────────────

// buildCache returns the configured cache backend + the per-entry TTL. When
// CACHE_REDIS_ADDR is unset, returns cache.Noop{} so the gateway runs with
// no caching (handy for local dev). TTL falls back to 5 minutes.
func buildCache() (cache.Cache, time.Duration) {
	ttl := 5 * time.Minute
	if s := os.Getenv("CACHE_TTL_SECONDS"); s != "" {
		if n, err := strconv.Atoi(s); err == nil && n > 0 {
			ttl = time.Duration(n) * time.Second
		}
	}
	addr := os.Getenv("CACHE_REDIS_ADDR")
	if addr == "" {
		log.Printf("⚠  CACHE_REDIS_ADDR unset — running without cache (Noop)")
		return cache.Noop{}, ttl
	}
	password := os.Getenv("CACHE_REDIS_PASSWORD")
	db := 0
	if s := os.Getenv("CACHE_REDIS_DB"); s != "" {
		if n, err := strconv.Atoi(s); err == nil {
			db = n
		}
	}
	rc, err := cache.NewRedis(addr, password, db)
	if err != nil {
		log.Printf("⚠  redis dial failed (%v) — falling back to Noop cache", err)
		return cache.Noop{}, ttl
	}
	log.Printf("✅ cache: Redis %s db=%d ttl=%s", addr, db, ttl)
	return rc, ttl
}

// ─── Policy enforcer ────────────────────────────────────────────────────

// buildEnforcer wires the Casbin enforcer against the policy-engine MongoDB.
// POLICY_MONGO_URI unset, or any connection failure, falls back to DenyAll
// (fail-closed) — which only matters for fields carrying @auth/@policy.
func buildEnforcer() policy.Enforcer {
	uri := os.Getenv("POLICY_MONGO_URI")
	if uri == "" {
		log.Printf("⚠  POLICY_MONGO_URI unset — directive-guarded fields will be DENIED (DenyAll)")
		return policy.DenyAll{}
	}
	db := env("POLICY_MONGO_DB", "lms_policy")
	coll := env("POLICY_MONGO_COLLECTION", "casbin_rule")
	ce, err := policy.NewCasbin(context.Background(), uri, db, coll)
	if err != nil {
		log.Printf("⚠  casbin enforcer init failed (%v) — falling back to DenyAll", err)
		return policy.DenyAll{}
	}
	log.Printf("✅ policy: Casbin enforcer on Mongo %s.%s", db, coll)
	return ce
}

// ─── Business-rule store ────────────────────────────────────────────────

// buildRuleStore loads the dynamic business rules from MongoDB. Reuses
// POLICY_MONGO_URI; the collection defaults to "business_rule". Returns nil
// (rules disabled — mutations pass through) when the URI is unset or Mongo
// is unreachable, so a missing rule store never wedges the gateway.
func buildRuleStore() *domain.RuleStore {
	uri := os.Getenv("POLICY_MONGO_URI")
	if uri == "" {
		log.Printf("⚠  POLICY_MONGO_URI unset — business rules disabled")
		return nil
	}
	db := env("POLICY_MONGO_DB", "lms_policy")
	coll := env("RULE_MONGO_COLLECTION", "business_rule")
	rs, err := domain.NewRuleStore(context.Background(), uri, db, coll)
	if err != nil {
		log.Printf("⚠  business-rule store init failed (%v) — rules disabled", err)
		return nil
	}
	return rs
}

// buildActionStore loads dynamic actions (fetch/compute/write pipelines
// behind the runAction mutation) from MongoDB. nil → runAction disabled.
func buildActionStore() *domain.ActionStore {
	uri := os.Getenv("POLICY_MONGO_URI")
	if uri == "" {
		return nil
	}
	db := env("POLICY_MONGO_DB", "lms_policy")
	coll := env("ACTION_MONGO_COLLECTION", "action")
	as, err := domain.NewActionStore(context.Background(), uri, db, coll)
	if err != nil {
		log.Printf("⚠  action store init failed (%v) — runAction disabled", err)
		return nil
	}
	return as
}

// ─── gRPC dial options ──────────────────────────────────────────────────

// buildDialOpts assembles options shared by every backend dial. mTLS kicks
// in when TLS_CERT_FILE / TLS_KEY_FILE / TLS_CA_FILE are all set; otherwise
// the gateway uses an insecure transport (suitable for local development).
func buildDialOpts() ([]grpc.DialOption, error) {
	certPath := os.Getenv("TLS_CERT_FILE")
	keyPath := os.Getenv("TLS_KEY_FILE")
	caPath := os.Getenv("TLS_CA_FILE")

	opts := []grpc.DialOption{
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(64 * 1024 * 1024)),
	}

	if certPath == "" || keyPath == "" || caPath == "" {
		log.Printf("⚠  TLS env vars unset — dialing backends with insecure transport")
		opts = append(opts, grpc.WithTransportCredentials(insecure.NewCredentials()))
		return opts, nil
	}

	cert, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		return nil, fmt.Errorf("load cert: %w", err)
	}
	caPEM, err := os.ReadFile(caPath)
	if err != nil {
		return nil, fmt.Errorf("read ca: %w", err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		return nil, errors.New("failed to parse CA pem")
	}
	tlsCfg := &tls.Config{
		Certificates: []tls.Certificate{cert},
		RootCAs:      pool,
		MinVersion:   tls.VersionTLS12,
	}
	opts = append(opts, grpc.WithTransportCredentials(credentials.NewTLS(tlsCfg)))
	return opts, nil
}

// env returns os.Getenv(key) or def when unset.
func env(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
