// Code generated by grpc-gen. DO NOT EDIT.
// proto ↔ gqlgen-model converters for service "audit".

package convert

import (
	"strconv"

	pb "github.com/thaily/lms/proto/audit"
	"github.com/thaily/lms/src/server/graph/model"
)

// PBToAuditLog converts a proto AuditLog into the GraphQL model. Returns nil when in is nil.
func PBToAuditLog(in *pb.AuditLog) *model.AuditLog {
	if in == nil {
		return nil
	}
	out := &model.AuditLog{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.ActorID = strconv.FormatUint(in.GetActorId(), 10)
	out.Action = in.GetAction()
	out.TargetType = in.TargetType
	if in.TargetId != nil { s := strconv.FormatUint(*in.TargetId, 10); out.TargetID = &s }
	out.Meta = in.Meta
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToAuditLogSlice converts a slice of proto AuditLog into models.
func PBToAuditLogSlice(in []*pb.AuditLog) []*model.AuditLog {
	out := make([]*model.AuditLog, 0, len(in))
	for _, x := range in {
		out = append(out, PBToAuditLog(x))
	}
	return out
}

