// Code generated by grpc-gen. DO NOT EDIT.
// proto ↔ gqlgen-model converters for service "exam".

package convert

import (
	"strconv"

	pb "github.com/thaily/lms/proto/exam"
	"github.com/thaily/lms/src/server/graph/model"
)

// ExamCommunityStatusFromPB maps the proto ExamCommunityStatus value to the GraphQL enum string.
func ExamCommunityStatusFromPB(v pb.ExamCommunityStatus) model.ExamCommunityStatus {
	return model.ExamCommunityStatus(v.String())
}

// ExamCommunityStatusToPB maps the GraphQL enum back to its proto value.
func ExamCommunityStatusToPB(v model.ExamCommunityStatus) pb.ExamCommunityStatus {
	return pb.ExamCommunityStatus(pb.ExamCommunityStatus_value[string(v)])
}

// ExamVisibilityFromPB maps the proto ExamVisibility value to the GraphQL enum string.
func ExamVisibilityFromPB(v pb.ExamVisibility) model.ExamVisibility {
	return model.ExamVisibility(v.String())
}

// ExamVisibilityToPB maps the GraphQL enum back to its proto value.
func ExamVisibilityToPB(v model.ExamVisibility) pb.ExamVisibility {
	return pb.ExamVisibility(pb.ExamVisibility_value[string(v)])
}

// QuestionTypeFromPB maps the proto QuestionType value to the GraphQL enum string.
func QuestionTypeFromPB(v pb.QuestionType) model.QuestionType {
	return model.QuestionType(v.String())
}

// QuestionTypeToPB maps the GraphQL enum back to its proto value.
func QuestionTypeToPB(v model.QuestionType) pb.QuestionType {
	return pb.QuestionType(pb.QuestionType_value[string(v)])
}

// ShowResultModeFromPB maps the proto ShowResultMode value to the GraphQL enum string.
func ShowResultModeFromPB(v pb.ShowResultMode) model.ShowResultMode {
	return model.ShowResultMode(v.String())
}

// ShowResultModeToPB maps the GraphQL enum back to its proto value.
func ShowResultModeToPB(v model.ShowResultMode) pb.ShowResultMode {
	return pb.ShowResultMode(pb.ShowResultMode_value[string(v)])
}

// PBToExam converts a proto Exam into the GraphQL model. Returns nil when in is nil.
func PBToExam(in *pb.Exam) *model.Exam {
	if in == nil {
		return nil
	}
	out := &model.Exam{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.OwnerTeacherID = strconv.FormatUint(in.GetOwnerTeacherId(), 10)
	out.Title = in.GetTitle()
	out.Description = in.Description
	out.Subject = in.Subject
	out.DurationMin = int(in.GetDurationMin())
	out.TotalPoints = in.GetTotalPoints()
	out.Visibility = ExamVisibilityFromPB(in.GetVisibility())
	if in.CommunityStatus != nil { v := ExamCommunityStatusFromPB(*in.CommunityStatus); out.CommunityStatus = &v }
	out.RejectReason = in.RejectReason
	out.ShuffleQuestions = in.GetShuffleQuestions()
	out.ShuffleChoices = in.GetShuffleChoices()
	out.ShowResultMode = ShowResultModeFromPB(in.GetShowResultMode())
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToExamSlice converts a slice of proto Exam into models.
func PBToExamSlice(in []*pb.Exam) []*model.Exam {
	out := make([]*model.Exam, 0, len(in))
	for _, x := range in {
		out = append(out, PBToExam(x))
	}
	return out
}

// PBToExamAssignment converts a proto ExamAssignment into the GraphQL model. Returns nil when in is nil.
func PBToExamAssignment(in *pb.ExamAssignment) *model.ExamAssignment {
	if in == nil {
		return nil
	}
	out := &model.ExamAssignment{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.ExamID = strconv.FormatUint(in.GetExamId(), 10)
	out.ClassID = strconv.FormatUint(in.GetClassId(), 10)
	out.OpenAt = in.GetOpenAt().AsTime()
	out.CloseAt = in.GetCloseAt().AsTime()
	out.MaxAttempts = int(in.GetMaxAttempts())
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToExamAssignmentSlice converts a slice of proto ExamAssignment into models.
func PBToExamAssignmentSlice(in []*pb.ExamAssignment) []*model.ExamAssignment {
	out := make([]*model.ExamAssignment, 0, len(in))
	for _, x := range in {
		out = append(out, PBToExamAssignment(x))
	}
	return out
}

// PBToQuestion converts a proto Question into the GraphQL model. Returns nil when in is nil.
func PBToQuestion(in *pb.Question) *model.Question {
	if in == nil {
		return nil
	}
	out := &model.Question{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.ExamID = strconv.FormatUint(in.GetExamId(), 10)
	out.Position = int(in.GetPosition())
	out.Type = QuestionTypeFromPB(in.GetType())
	out.Content = in.GetContent()
	out.ImageKey = in.ImageKey
	out.Points = in.GetPoints()
	out.Explanation = in.Explanation
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToQuestionSlice converts a slice of proto Question into models.
func PBToQuestionSlice(in []*pb.Question) []*model.Question {
	out := make([]*model.Question, 0, len(in))
	for _, x := range in {
		out = append(out, PBToQuestion(x))
	}
	return out
}

// PBToQuestionAnswer converts a proto QuestionAnswer into the GraphQL model. Returns nil when in is nil.
func PBToQuestionAnswer(in *pb.QuestionAnswer) *model.QuestionAnswer {
	if in == nil {
		return nil
	}
	out := &model.QuestionAnswer{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.QuestionID = strconv.FormatUint(in.GetQuestionId(), 10)
	out.AcceptedAnswer = in.GetAcceptedAnswer()
	out.CaseSensitive = in.GetCaseSensitive()
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToQuestionAnswerSlice converts a slice of proto QuestionAnswer into models.
func PBToQuestionAnswerSlice(in []*pb.QuestionAnswer) []*model.QuestionAnswer {
	out := make([]*model.QuestionAnswer, 0, len(in))
	for _, x := range in {
		out = append(out, PBToQuestionAnswer(x))
	}
	return out
}

// PBToQuestionChoice converts a proto QuestionChoice into the GraphQL model. Returns nil when in is nil.
func PBToQuestionChoice(in *pb.QuestionChoice) *model.QuestionChoice {
	if in == nil {
		return nil
	}
	out := &model.QuestionChoice{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.QuestionID = strconv.FormatUint(in.GetQuestionId(), 10)
	out.Position = int(in.GetPosition())
	out.Content = in.GetContent()
	out.IsCorrect = in.GetIsCorrect()
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToQuestionChoiceSlice converts a slice of proto QuestionChoice into models.
func PBToQuestionChoiceSlice(in []*pb.QuestionChoice) []*model.QuestionChoice {
	out := make([]*model.QuestionChoice, 0, len(in))
	for _, x := range in {
		out = append(out, PBToQuestionChoice(x))
	}
	return out
}

