// Code generated by grpc-gen. DO NOT EDIT.
// Model→PB input converters for service "lesson".

package convert

import (
	"strconv"

	"google.golang.org/protobuf/types/known/timestamppb"

	pb "github.com/thaily/lms/proto/lesson"
	"github.com/thaily/lms/src/server/graph/model"
)

// CreateLessonAttendanceInputToPB converts the GraphQL input into the proto request.
func CreateLessonAttendanceInputToPB(in model.CreateLessonAttendanceInput) *pb.CreateLessonAttendanceRequest {
	out := &pb.CreateLessonAttendanceRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.LessonID, 10, 64); err == nil { out.LessonId = v }
	if v, err := strconv.ParseUint(in.StudentID, 10, 64); err == nil { out.StudentId = v }
	out.Status = AttendanceStatusToPB(in.Status)
	out.Note = in.Note
	if v, err := strconv.ParseUint(in.MarkedByTeacherID, 10, 64); err == nil { out.MarkedByTeacherId = v }
	out.MarkedAt = timestamppb.New(in.MarkedAt)
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateLessonInputToPB converts the GraphQL input into the proto request.
func CreateLessonInputToPB(in model.CreateLessonInput) *pb.CreateLessonRequest {
	out := &pb.CreateLessonRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.ClassID, 10, 64); err == nil { out.ClassId = v }
	out.Title = in.Title
	out.Description = in.Description
	out.StartAt = timestamppb.New(in.StartAt)
	out.EndAt = timestamppb.New(in.EndAt)
	out.Mode = LessonModeToPB(in.Mode)
	out.Location = in.Location
	out.MeetingUrl = in.MeetingURL
	out.Status = LessonStatusToPB(in.Status)
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateLessonVideoInputToPB converts the GraphQL input into the proto request.
func CreateLessonVideoInputToPB(in model.CreateLessonVideoInput) *pb.CreateLessonVideoRequest {
	out := &pb.CreateLessonVideoRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.LessonID, 10, 64); err == nil { out.LessonId = v }
	out.Title = in.Title
	out.StorageKey = in.StorageKey
	if in.DurationSec != nil { v := int32(*in.DurationSec); out.DurationSec = &v }
	if in.SizeBytes != nil { v := int64(*in.SizeBytes); out.SizeBytes = &v }
	out.MimeType = in.MimeType
	out.ThumbnailKey = in.ThumbnailKey
	out.Status = VideoStatusToPB(in.Status)
	if in.UploadedAt != nil { out.UploadedAt = timestamppb.New(*in.UploadedAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// UpdateLessonAttendanceInputToPB converts the GraphQL input + filters into the proto request.
func UpdateLessonAttendanceInputToPB(filters []*model.FilterCriteria, in model.UpdateLessonAttendanceInput) *pb.UpdateLessonAttendanceRequest {
	out := &pb.UpdateLessonAttendanceRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	if in.Status != nil { v := AttendanceStatusToPB(*in.Status); out.Status = &v }
	out.Note = in.Note
	if in.MarkedAt != nil { out.MarkedAt = timestamppb.New(*in.MarkedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateLessonInputToPB converts the GraphQL input + filters into the proto request.
func UpdateLessonInputToPB(filters []*model.FilterCriteria, in model.UpdateLessonInput) *pb.UpdateLessonRequest {
	out := &pb.UpdateLessonRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.Title = in.Title
	out.Description = in.Description
	if in.StartAt != nil { out.StartAt = timestamppb.New(*in.StartAt) }
	if in.EndAt != nil { out.EndAt = timestamppb.New(*in.EndAt) }
	if in.Mode != nil { v := LessonModeToPB(*in.Mode); out.Mode = &v }
	out.Location = in.Location
	out.MeetingUrl = in.MeetingURL
	if in.Status != nil { v := LessonStatusToPB(*in.Status); out.Status = &v }
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateLessonVideoInputToPB converts the GraphQL input + filters into the proto request.
func UpdateLessonVideoInputToPB(filters []*model.FilterCriteria, in model.UpdateLessonVideoInput) *pb.UpdateLessonVideoRequest {
	out := &pb.UpdateLessonVideoRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.Title = in.Title
	if in.DurationSec != nil { v := int32(*in.DurationSec); out.DurationSec = &v }
	if in.SizeBytes != nil { v := int64(*in.SizeBytes); out.SizeBytes = &v }
	out.MimeType = in.MimeType
	out.ThumbnailKey = in.ThumbnailKey
	if in.Status != nil { v := VideoStatusToPB(*in.Status); out.Status = &v }
	if in.UploadedAt != nil { out.UploadedAt = timestamppb.New(*in.UploadedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

