// Code generated by grpc-gen. DO NOT EDIT.
// Model→PB input converters for service "material".

package convert

import (
	"strconv"

	"google.golang.org/protobuf/types/known/timestamppb"

	pb "github.com/thaily/lms/proto/material"
	"github.com/thaily/lms/src/server/graph/model"
)

// CreateMaterialClassInputToPB converts the GraphQL input into the proto request.
func CreateMaterialClassInputToPB(in model.CreateMaterialClassInput) *pb.CreateMaterialClassRequest {
	out := &pb.CreateMaterialClassRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.MaterialID, 10, 64); err == nil { out.MaterialId = v }
	if v, err := strconv.ParseUint(in.ClassID, 10, 64); err == nil { out.ClassId = v }
	out.AttachedAt = timestamppb.New(in.AttachedAt)
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateMaterialInputToPB converts the GraphQL input into the proto request.
func CreateMaterialInputToPB(in model.CreateMaterialInput) *pb.CreateMaterialRequest {
	out := &pb.CreateMaterialRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.OwnerTeacherID, 10, 64); err == nil { out.OwnerTeacherId = v }
	out.Title = in.Title
	out.Description = in.Description
	out.SourceType = MaterialSourceTypeToPB(in.SourceType)
	out.Url = in.URL
	out.StorageKey = in.StorageKey
	out.FileName = in.FileName
	out.FileType = in.FileType
	if in.SizeBytes != nil { v := int64(*in.SizeBytes); out.SizeBytes = &v }
	out.Visibility = MaterialVisibilityToPB(in.Visibility)
	if in.CommunityStatus != nil { v := CommunityStatusToPB(*in.CommunityStatus); out.CommunityStatus = &v }
	out.RejectReason = in.RejectReason
	out.DownloadCount = uint32(in.DownloadCount)
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateMaterialTagInputToPB converts the GraphQL input into the proto request.
func CreateMaterialTagInputToPB(in model.CreateMaterialTagInput) *pb.CreateMaterialTagRequest {
	out := &pb.CreateMaterialTagRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.MaterialID, 10, 64); err == nil { out.MaterialId = v }
	out.Tag = in.Tag
	out.CreatedBy = in.CreatedBy
	return out
}

// UpdateMaterialClassInputToPB converts the GraphQL input + filters into the proto request.
func UpdateMaterialClassInputToPB(filters []*model.FilterCriteria, in model.UpdateMaterialClassInput) *pb.UpdateMaterialClassRequest {
	out := &pb.UpdateMaterialClassRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	if in.AttachedAt != nil { out.AttachedAt = timestamppb.New(*in.AttachedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateMaterialInputToPB converts the GraphQL input + filters into the proto request.
func UpdateMaterialInputToPB(filters []*model.FilterCriteria, in model.UpdateMaterialInput) *pb.UpdateMaterialRequest {
	out := &pb.UpdateMaterialRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.Title = in.Title
	out.Description = in.Description
	if in.Visibility != nil { v := MaterialVisibilityToPB(*in.Visibility); out.Visibility = &v }
	out.CommunityStatus = CommunityStatusToPB(in.CommunityStatus)
	out.RejectReason = in.RejectReason
	if in.DownloadCount != nil { v := uint32(*in.DownloadCount); out.DownloadCount = &v }
	out.Url = in.URL
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateMaterialTagInputToPB converts the GraphQL input + filters into the proto request.
func UpdateMaterialTagInputToPB(filters []*model.FilterCriteria, in model.UpdateMaterialTagInput) *pb.UpdateMaterialTagRequest {
	out := &pb.UpdateMaterialTagRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.Tag = in.Tag
	out.UpdatedBy = in.UpdatedBy
	return out
}

