// Code generated by grpc-gen. DO NOT EDIT.
// proto ↔ gqlgen-model converters for service "material".

package convert

import (
	"strconv"

	pb "github.com/thaily/lms/proto/material"
	"github.com/thaily/lms/src/server/graph/model"
)

// CommunityStatusFromPB maps the proto CommunityStatus value to the GraphQL enum string.
func CommunityStatusFromPB(v pb.CommunityStatus) model.CommunityStatus {
	return model.CommunityStatus(v.String())
}

// CommunityStatusToPB maps the GraphQL enum back to its proto value.
func CommunityStatusToPB(v model.CommunityStatus) pb.CommunityStatus {
	return pb.CommunityStatus(pb.CommunityStatus_value[string(v)])
}

// MaterialSourceTypeFromPB maps the proto MaterialSourceType value to the GraphQL enum string.
func MaterialSourceTypeFromPB(v pb.MaterialSourceType) model.MaterialSourceType {
	return model.MaterialSourceType(v.String())
}

// MaterialSourceTypeToPB maps the GraphQL enum back to its proto value.
func MaterialSourceTypeToPB(v model.MaterialSourceType) pb.MaterialSourceType {
	return pb.MaterialSourceType(pb.MaterialSourceType_value[string(v)])
}

// MaterialVisibilityFromPB maps the proto MaterialVisibility value to the GraphQL enum string.
func MaterialVisibilityFromPB(v pb.MaterialVisibility) model.MaterialVisibility {
	return model.MaterialVisibility(v.String())
}

// MaterialVisibilityToPB maps the GraphQL enum back to its proto value.
func MaterialVisibilityToPB(v model.MaterialVisibility) pb.MaterialVisibility {
	return pb.MaterialVisibility(pb.MaterialVisibility_value[string(v)])
}

// PBToMaterial converts a proto Material into the GraphQL model. Returns nil when in is nil.
func PBToMaterial(in *pb.Material) *model.Material {
	if in == nil {
		return nil
	}
	out := &model.Material{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.OwnerTeacherID = strconv.FormatUint(in.GetOwnerTeacherId(), 10)
	out.Title = in.GetTitle()
	out.Description = in.Description
	out.SourceType = MaterialSourceTypeFromPB(in.GetSourceType())
	out.URL = in.Url
	out.StorageKey = in.StorageKey
	out.FileName = in.FileName
	out.FileType = in.FileType
	if in.SizeBytes != nil { v := int(*in.SizeBytes); out.SizeBytes = &v }
	out.Visibility = MaterialVisibilityFromPB(in.GetVisibility())
	if in.CommunityStatus != nil { v := CommunityStatusFromPB(*in.CommunityStatus); out.CommunityStatus = &v }
	out.RejectReason = in.RejectReason
	out.DownloadCount = int(in.GetDownloadCount())
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToMaterialSlice converts a slice of proto Material into models.
func PBToMaterialSlice(in []*pb.Material) []*model.Material {
	out := make([]*model.Material, 0, len(in))
	for _, x := range in {
		out = append(out, PBToMaterial(x))
	}
	return out
}

// PBToMaterialClass converts a proto MaterialClass into the GraphQL model. Returns nil when in is nil.
func PBToMaterialClass(in *pb.MaterialClass) *model.MaterialClass {
	if in == nil {
		return nil
	}
	out := &model.MaterialClass{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.MaterialID = strconv.FormatUint(in.GetMaterialId(), 10)
	out.ClassID = strconv.FormatUint(in.GetClassId(), 10)
	out.AttachedAt = in.GetAttachedAt().AsTime()
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToMaterialClassSlice converts a slice of proto MaterialClass into models.
func PBToMaterialClassSlice(in []*pb.MaterialClass) []*model.MaterialClass {
	out := make([]*model.MaterialClass, 0, len(in))
	for _, x := range in {
		out = append(out, PBToMaterialClass(x))
	}
	return out
}

// PBToMaterialTag converts a proto MaterialTag into the GraphQL model. Returns nil when in is nil.
func PBToMaterialTag(in *pb.MaterialTag) *model.MaterialTag {
	if in == nil {
		return nil
	}
	out := &model.MaterialTag{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.MaterialID = strconv.FormatUint(in.GetMaterialId(), 10)
	out.Tag = in.GetTag()
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToMaterialTagSlice converts a slice of proto MaterialTag into models.
func PBToMaterialTagSlice(in []*pb.MaterialTag) []*model.MaterialTag {
	out := make([]*model.MaterialTag, 0, len(in))
	for _, x := range in {
		out = append(out, PBToMaterialTag(x))
	}
	return out
}

