// Code generated by grpc-gen. DO NOT EDIT.
// proto ↔ gqlgen-model converters for service "notification".

package convert

import (
	"strconv"

	pb "github.com/thaily/lms/proto/notification"
	"github.com/thaily/lms/src/server/graph/model"
)

// ReportStatusFromPB maps the proto ReportStatus value to the GraphQL enum string.
func ReportStatusFromPB(v pb.ReportStatus) model.ReportStatus {
	return model.ReportStatus(v.String())
}

// ReportStatusToPB maps the GraphQL enum back to its proto value.
func ReportStatusToPB(v model.ReportStatus) pb.ReportStatus {
	return pb.ReportStatus(pb.ReportStatus_value[string(v)])
}

// ReportTargetTypeFromPB maps the proto ReportTargetType value to the GraphQL enum string.
func ReportTargetTypeFromPB(v pb.ReportTargetType) model.ReportTargetType {
	return model.ReportTargetType(v.String())
}

// ReportTargetTypeToPB maps the GraphQL enum back to its proto value.
func ReportTargetTypeToPB(v model.ReportTargetType) pb.ReportTargetType {
	return pb.ReportTargetType(pb.ReportTargetType_value[string(v)])
}

// PBToCommunityReport converts a proto CommunityReport into the GraphQL model. Returns nil when in is nil.
func PBToCommunityReport(in *pb.CommunityReport) *model.CommunityReport {
	if in == nil {
		return nil
	}
	out := &model.CommunityReport{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.ReporterUserID = strconv.FormatUint(in.GetReporterUserId(), 10)
	out.TargetType = ReportTargetTypeFromPB(in.GetTargetType())
	out.TargetID = strconv.FormatUint(in.GetTargetId(), 10)
	out.Reason = in.GetReason()
	out.Note = in.Note
	out.Status = ReportStatusFromPB(in.GetStatus())
	if in.ResolvedByAdminId != nil { s := strconv.FormatUint(*in.ResolvedByAdminId, 10); out.ResolvedByAdminID = &s }
	if in.ResolvedAt != nil { t := in.ResolvedAt.AsTime(); out.ResolvedAt = &t }
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToCommunityReportSlice converts a slice of proto CommunityReport into models.
func PBToCommunityReportSlice(in []*pb.CommunityReport) []*model.CommunityReport {
	out := make([]*model.CommunityReport, 0, len(in))
	for _, x := range in {
		out = append(out, PBToCommunityReport(x))
	}
	return out
}

// PBToNotification converts a proto Notification into the GraphQL model. Returns nil when in is nil.
func PBToNotification(in *pb.Notification) *model.Notification {
	if in == nil {
		return nil
	}
	out := &model.Notification{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.UserID = strconv.FormatUint(in.GetUserId(), 10)
	out.Type = in.GetType()
	out.Title = in.GetTitle()
	out.Body = in.Body
	out.Payload = in.Payload
	if in.ReadAt != nil { t := in.ReadAt.AsTime(); out.ReadAt = &t }
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToNotificationSlice converts a slice of proto Notification into models.
func PBToNotificationSlice(in []*pb.Notification) []*model.Notification {
	out := make([]*model.Notification, 0, len(in))
	for _, x := range in {
		out = append(out, PBToNotification(x))
	}
	return out
}

