// Code generated by grpc-gen. DO NOT EDIT.
// Model→PB input converters for service "notification".

package convert

import (
	"strconv"

	"google.golang.org/protobuf/types/known/timestamppb"

	pb "github.com/thaily/lms/proto/notification"
	"github.com/thaily/lms/src/server/graph/model"
)

// CreateCommunityReportInputToPB converts the GraphQL input into the proto request.
func CreateCommunityReportInputToPB(in model.CreateCommunityReportInput) *pb.CreateCommunityReportRequest {
	out := &pb.CreateCommunityReportRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.ReporterUserID, 10, 64); err == nil { out.ReporterUserId = v }
	out.TargetType = ReportTargetTypeToPB(in.TargetType)
	if v, err := strconv.ParseUint(in.TargetID, 10, 64); err == nil { out.TargetId = v }
	out.Reason = in.Reason
	out.Note = in.Note
	out.Status = ReportStatusToPB(in.Status)
	if in.ResolvedByAdminID != nil {
		if v, err := strconv.ParseUint(*in.ResolvedByAdminID, 10, 64); err == nil {
			out.ResolvedByAdminId = &v
		}
	}
	if in.ResolvedAt != nil { out.ResolvedAt = timestamppb.New(*in.ResolvedAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateNotificationInputToPB converts the GraphQL input into the proto request.
func CreateNotificationInputToPB(in model.CreateNotificationInput) *pb.CreateNotificationRequest {
	out := &pb.CreateNotificationRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.UserID, 10, 64); err == nil { out.UserId = v }
	out.Type = in.Type
	out.Title = in.Title
	out.Body = in.Body
	out.Payload = in.Payload
	if in.ReadAt != nil { out.ReadAt = timestamppb.New(*in.ReadAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// UpdateCommunityReportInputToPB converts the GraphQL input + filters into the proto request.
func UpdateCommunityReportInputToPB(filters []*model.FilterCriteria, in model.UpdateCommunityReportInput) *pb.UpdateCommunityReportRequest {
	out := &pb.UpdateCommunityReportRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	if in.Status != nil { v := ReportStatusToPB(*in.Status); out.Status = &v }
	if in.ResolvedByAdminID != nil {
		if v, err := strconv.ParseUint(*in.ResolvedByAdminID, 10, 64); err == nil {
			out.ResolvedByAdminId = &v
		}
	}
	if in.ResolvedAt != nil { out.ResolvedAt = timestamppb.New(*in.ResolvedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateNotificationInputToPB converts the GraphQL input + filters into the proto request.
func UpdateNotificationInputToPB(filters []*model.FilterCriteria, in model.UpdateNotificationInput) *pb.UpdateNotificationRequest {
	out := &pb.UpdateNotificationRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	if in.ReadAt != nil { out.ReadAt = timestamppb.New(*in.ReadAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

