// Code generated by grpc-gen. DO NOT EDIT.
// proto ↔ gqlgen-model converters for service "submission".

package convert

import (
	"strconv"

	pb "github.com/thaily/lms/proto/submission"
	"github.com/thaily/lms/src/server/graph/model"
)

// AttemptStatusFromPB maps the proto AttemptStatus value to the GraphQL enum string.
func AttemptStatusFromPB(v pb.AttemptStatus) model.AttemptStatus {
	return model.AttemptStatus(v.String())
}

// AttemptStatusToPB maps the GraphQL enum back to its proto value.
func AttemptStatusToPB(v model.AttemptStatus) pb.AttemptStatus {
	return pb.AttemptStatus(pb.AttemptStatus_value[string(v)])
}

// PBToAttemptAnswer converts a proto AttemptAnswer into the GraphQL model. Returns nil when in is nil.
func PBToAttemptAnswer(in *pb.AttemptAnswer) *model.AttemptAnswer {
	if in == nil {
		return nil
	}
	out := &model.AttemptAnswer{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.AttemptID = strconv.FormatUint(in.GetAttemptId(), 10)
	out.QuestionID = strconv.FormatUint(in.GetQuestionId(), 10)
	out.SelectedChoiceIds = in.SelectedChoiceIds
	out.TextAnswer = in.TextAnswer
	out.UploadedFileKey = in.UploadedFileKey
	out.AutoScore = in.AutoScore
	out.ManualScore = in.ManualScore
	out.TeacherComment = in.TeacherComment
	if in.GradedAt != nil { t := in.GradedAt.AsTime(); out.GradedAt = &t }
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToAttemptAnswerSlice converts a slice of proto AttemptAnswer into models.
func PBToAttemptAnswerSlice(in []*pb.AttemptAnswer) []*model.AttemptAnswer {
	out := make([]*model.AttemptAnswer, 0, len(in))
	for _, x := range in {
		out = append(out, PBToAttemptAnswer(x))
	}
	return out
}

// PBToExamAttempt converts a proto ExamAttempt into the GraphQL model. Returns nil when in is nil.
func PBToExamAttempt(in *pb.ExamAttempt) *model.ExamAttempt {
	if in == nil {
		return nil
	}
	out := &model.ExamAttempt{}
	out.ID = strconv.FormatUint(in.GetId(), 10)
	out.ExamID = strconv.FormatUint(in.GetExamId(), 10)
	out.StudentID = strconv.FormatUint(in.GetStudentId(), 10)
	if in.AssignmentId != nil { s := strconv.FormatUint(*in.AssignmentId, 10); out.AssignmentID = &s }
	out.StartedAt = in.GetStartedAt().AsTime()
	if in.SubmittedAt != nil { t := in.SubmittedAt.AsTime(); out.SubmittedAt = &t }
	out.AutoScore = in.AutoScore
	out.ManualScore = in.ManualScore
	out.TotalScore = in.TotalScore
	out.Status = AttemptStatusFromPB(in.GetStatus())
	if in.GradedByTeacherId != nil { s := strconv.FormatUint(*in.GradedByTeacherId, 10); out.GradedByTeacherID = &s }
	if in.GradedAt != nil { t := in.GradedAt.AsTime(); out.GradedAt = &t }
	out.CreatedAt = in.GetCreatedAt().AsTime()
	out.UpdatedAt = in.GetUpdatedAt().AsTime()
	out.CreatedBy = in.CreatedBy
	out.UpdatedBy = in.UpdatedBy
	return out
}

// PBToExamAttemptSlice converts a slice of proto ExamAttempt into models.
func PBToExamAttemptSlice(in []*pb.ExamAttempt) []*model.ExamAttempt {
	out := make([]*model.ExamAttempt, 0, len(in))
	for _, x := range in {
		out = append(out, PBToExamAttempt(x))
	}
	return out
}

