// Code generated by grpc-gen. DO NOT EDIT.
// Model→PB input converters for service "submission".

package convert

import (
	"strconv"

	"google.golang.org/protobuf/types/known/timestamppb"

	pb "github.com/thaily/lms/proto/submission"
	"github.com/thaily/lms/src/server/graph/model"
)

// CreateAttemptAnswerInputToPB converts the GraphQL input into the proto request.
func CreateAttemptAnswerInputToPB(in model.CreateAttemptAnswerInput) *pb.CreateAttemptAnswerRequest {
	out := &pb.CreateAttemptAnswerRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.AttemptID, 10, 64); err == nil { out.AttemptId = v }
	if v, err := strconv.ParseUint(in.QuestionID, 10, 64); err == nil { out.QuestionId = v }
	out.SelectedChoiceIds = in.SelectedChoiceIds
	out.TextAnswer = in.TextAnswer
	out.UploadedFileKey = in.UploadedFileKey
	out.AutoScore = in.AutoScore
	out.ManualScore = in.ManualScore
	out.TeacherComment = in.TeacherComment
	if in.GradedAt != nil { out.GradedAt = timestamppb.New(*in.GradedAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateExamAttemptInputToPB converts the GraphQL input into the proto request.
func CreateExamAttemptInputToPB(in model.CreateExamAttemptInput) *pb.CreateExamAttemptRequest {
	out := &pb.CreateExamAttemptRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.ExamID, 10, 64); err == nil { out.ExamId = v }
	if v, err := strconv.ParseUint(in.StudentID, 10, 64); err == nil { out.StudentId = v }
	if in.AssignmentID != nil {
		if v, err := strconv.ParseUint(*in.AssignmentID, 10, 64); err == nil {
			out.AssignmentId = &v
		}
	}
	out.StartedAt = timestamppb.New(in.StartedAt)
	if in.SubmittedAt != nil { out.SubmittedAt = timestamppb.New(*in.SubmittedAt) }
	out.AutoScore = in.AutoScore
	out.ManualScore = in.ManualScore
	out.TotalScore = in.TotalScore
	out.Status = AttemptStatusToPB(in.Status)
	if in.GradedByTeacherID != nil {
		if v, err := strconv.ParseUint(*in.GradedByTeacherID, 10, 64); err == nil {
			out.GradedByTeacherId = &v
		}
	}
	if in.GradedAt != nil { out.GradedAt = timestamppb.New(*in.GradedAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// UpdateAttemptAnswerInputToPB converts the GraphQL input + filters into the proto request.
func UpdateAttemptAnswerInputToPB(filters []*model.FilterCriteria, in model.UpdateAttemptAnswerInput) *pb.UpdateAttemptAnswerRequest {
	out := &pb.UpdateAttemptAnswerRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.SelectedChoiceIds = in.SelectedChoiceIds
	out.TextAnswer = in.TextAnswer
	out.UploadedFileKey = in.UploadedFileKey
	out.AutoScore = in.AutoScore
	out.ManualScore = in.ManualScore
	out.TeacherComment = in.TeacherComment
	if in.GradedAt != nil { out.GradedAt = timestamppb.New(*in.GradedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateExamAttemptInputToPB converts the GraphQL input + filters into the proto request.
func UpdateExamAttemptInputToPB(filters []*model.FilterCriteria, in model.UpdateExamAttemptInput) *pb.UpdateExamAttemptRequest {
	out := &pb.UpdateExamAttemptRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	if in.SubmittedAt != nil { out.SubmittedAt = timestamppb.New(*in.SubmittedAt) }
	out.AutoScore = in.AutoScore
	out.ManualScore = in.ManualScore
	out.TotalScore = in.TotalScore
	if in.Status != nil { v := AttemptStatusToPB(*in.Status); out.Status = &v }
	if in.GradedByTeacherID != nil {
		if v, err := strconv.ParseUint(*in.GradedByTeacherID, 10, 64); err == nil {
			out.GradedByTeacherId = &v
		}
	}
	if in.GradedAt != nil { out.GradedAt = timestamppb.New(*in.GradedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

