// Code generated by grpc-gen. DO NOT EDIT.
// Model→PB input converters for service "user".

package convert

import (
	"strconv"

	"google.golang.org/protobuf/types/known/timestamppb"

	pb "github.com/thaily/lms/proto/user"
	"github.com/thaily/lms/src/server/graph/model"
)

// CreatePasswordResetInputToPB converts the GraphQL input into the proto request.
func CreatePasswordResetInputToPB(in model.CreatePasswordResetInput) *pb.CreatePasswordResetRequest {
	out := &pb.CreatePasswordResetRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.UserID, 10, 64); err == nil { out.UserId = v }
	out.TokenHash = in.TokenHash
	out.ExpiresAt = timestamppb.New(in.ExpiresAt)
	if in.UsedAt != nil { out.UsedAt = timestamppb.New(*in.UsedAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateRefreshTokenInputToPB converts the GraphQL input into the proto request.
func CreateRefreshTokenInputToPB(in model.CreateRefreshTokenInput) *pb.CreateRefreshTokenRequest {
	out := &pb.CreateRefreshTokenRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.UserID, 10, 64); err == nil { out.UserId = v }
	out.TokenHash = in.TokenHash
	out.UserAgent = in.UserAgent
	out.IpAddress = in.IPAddress
	out.ExpiresAt = timestamppb.New(in.ExpiresAt)
	if in.RevokedAt != nil { out.RevokedAt = timestamppb.New(*in.RevokedAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateStudentProfileInputToPB converts the GraphQL input into the proto request.
func CreateStudentProfileInputToPB(in model.CreateStudentProfileInput) *pb.CreateStudentProfileRequest {
	out := &pb.CreateStudentProfileRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.UserID, 10, 64); err == nil { out.UserId = v }
	out.Grade = in.Grade
	out.SchoolName = in.SchoolName
	out.ParentName = in.ParentName
	out.ParentPhone = in.ParentPhone
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateTeacherProfileInputToPB converts the GraphQL input into the proto request.
func CreateTeacherProfileInputToPB(in model.CreateTeacherProfileInput) *pb.CreateTeacherProfileRequest {
	out := &pb.CreateTeacherProfileRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	if v, err := strconv.ParseUint(in.UserID, 10, 64); err == nil { out.UserId = v }
	out.Bio = in.Bio
	out.Subjects = in.Subjects
	if in.YearsExp != nil { v := int32(*in.YearsExp); out.YearsExp = &v }
	out.FacebookUrl = in.FacebookURL
	out.CreatedBy = in.CreatedBy
	return out
}

// CreateUserInputToPB converts the GraphQL input into the proto request.
func CreateUserInputToPB(in model.CreateUserInput) *pb.CreateUserRequest {
	out := &pb.CreateUserRequest{}
	if in.ID != nil {
		if v, err := strconv.ParseUint(*in.ID, 10, 64); err == nil {
			out.Id = &v
		}
	}
	out.Email = in.Email
	out.Phone = in.Phone
	out.PasswordHash = in.PasswordHash
	out.FullName = in.FullName
	out.AvatarUrl = in.AvatarURL
	out.Role = UserRoleToPB(in.Role)
	out.Status = UserStatusToPB(in.Status)
	if in.EmailVerifiedAt != nil { out.EmailVerifiedAt = timestamppb.New(*in.EmailVerifiedAt) }
	if in.LastLoginAt != nil { out.LastLoginAt = timestamppb.New(*in.LastLoginAt) }
	out.CreatedBy = in.CreatedBy
	return out
}

// UpdatePasswordResetInputToPB converts the GraphQL input + filters into the proto request.
func UpdatePasswordResetInputToPB(filters []*model.FilterCriteria, in model.UpdatePasswordResetInput) *pb.UpdatePasswordResetRequest {
	out := &pb.UpdatePasswordResetRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	if in.UsedAt != nil { out.UsedAt = timestamppb.New(*in.UsedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateRefreshTokenInputToPB converts the GraphQL input + filters into the proto request.
func UpdateRefreshTokenInputToPB(filters []*model.FilterCriteria, in model.UpdateRefreshTokenInput) *pb.UpdateRefreshTokenRequest {
	out := &pb.UpdateRefreshTokenRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	if in.RevokedAt != nil { out.RevokedAt = timestamppb.New(*in.RevokedAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateStudentProfileInputToPB converts the GraphQL input + filters into the proto request.
func UpdateStudentProfileInputToPB(filters []*model.FilterCriteria, in model.UpdateStudentProfileInput) *pb.UpdateStudentProfileRequest {
	out := &pb.UpdateStudentProfileRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.Grade = in.Grade
	out.SchoolName = in.SchoolName
	out.ParentName = in.ParentName
	out.ParentPhone = in.ParentPhone
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateTeacherProfileInputToPB converts the GraphQL input + filters into the proto request.
func UpdateTeacherProfileInputToPB(filters []*model.FilterCriteria, in model.UpdateTeacherProfileInput) *pb.UpdateTeacherProfileRequest {
	out := &pb.UpdateTeacherProfileRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.Bio = in.Bio
	out.Subjects = in.Subjects
	if in.YearsExp != nil { v := int32(*in.YearsExp); out.YearsExp = &v }
	out.FacebookUrl = in.FacebookURL
	out.UpdatedBy = in.UpdatedBy
	return out
}

// UpdateUserInputToPB converts the GraphQL input + filters into the proto request.
func UpdateUserInputToPB(filters []*model.FilterCriteria, in model.UpdateUserInput) *pb.UpdateUserRequest {
	out := &pb.UpdateUserRequest{Filters: FilterCriteriaInputSliceToPB(filters)}
	out.Email = in.Email
	out.Phone = in.Phone
	out.PasswordHash = in.PasswordHash
	out.FullName = in.FullName
	out.AvatarUrl = in.AvatarURL
	if in.Role != nil { v := UserRoleToPB(*in.Role); out.Role = &v }
	if in.Status != nil { v := UserStatusToPB(*in.Status); out.Status = &v }
	if in.EmailVerifiedAt != nil { out.EmailVerifiedAt = timestamppb.New(*in.EmailVerifiedAt) }
	if in.LastLoginAt != nil { out.LastLoginAt = timestamppb.New(*in.LastLoginAt) }
	out.UpdatedBy = in.UpdatedBy
	return out
}

