// Code generated by grpc-gen. DO NOT EDIT.
// Source of truth: proto entity fields.
// Default: every entity field is filterable. To block a field, add
// `[(common.filterable) = false]` to it in the .proto and regen.

package handler

// LessonVideoFilterableFields is the runtime whitelist for filter conditions.
// When FILTER_STRICT is on (default), denied fields used in filters cause the
// server to return InvalidArgument listing the rejected field names.
var LessonVideoFilterableFields = map[string]bool{
	"id":            true,
	"created_at":    true,
	"updated_at":    true,
	"created_by":    true,
	"updated_by":    true,
	"lesson_id":     true,
	"title":         true,
	"storage_key":   true,
	"duration_sec":  true,
	"size_bytes":    true,
	"mime_type":     true,
	"thumbnail_key": true,
	"status":        true,
	"uploaded_at":   true,
}
