// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"encoding/json"
	"fmt"
	"reflect"
	"sync"
	"time"

	"github.com/expr-lang/expr"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"golang.org/x/crypto/bcrypt"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	"github.com/thaily/lms/src/server/graph/client"
)

// Step is one step of an Action. Kind selects the behaviour:
//   fetch   — load rows of Entity filtered by Where, bind to env[As]
//   compute — evaluate Expr (expr-lang), bind the result to env[As]
//   write   — call mutation Op; Where = filters (Update/Delete), Set = fields
type Step struct {
	Kind   string
	As     string
	Entity string
	Where  []Criteria
	Expr   string
	Op     string
	Set    map[string]string
}

// Action is a custom multi-step operation stored in MongoDB. Output is an
// optional expr-lang expression producing the result map.
type Action struct {
	Name   string
	Steps  []Step
	Output string
}

// ActionStore loads actions from MongoDB.
type ActionStore struct {
	coll   *mongo.Collection
	mu     sync.RWMutex
	byName map[string]Action
}

// NewActionStore connects to Mongo and does the initial load.
func NewActionStore(ctx context.Context, mongoURI, db, collection string) (*ActionStore, error) {
	cl, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		return nil, fmt.Errorf("mongo connect: %w", err)
	}
	pctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := cl.Ping(pctx, nil); err != nil {
		return nil, fmt.Errorf("mongo ping: %w", err)
	}
	s := &ActionStore{coll: cl.Database(db).Collection(collection), byName: map[string]Action{}}
	if err := s.Reload(ctx); err != nil {
		return nil, err
	}
	return s, nil
}

// Reload re-reads every action from Mongo.
func (s *ActionStore) Reload(ctx context.Context) error {
	cur, err := s.coll.Find(ctx, bson.M{})
	if err != nil {
		return fmt.Errorf("action find: %w", err)
	}
	var acts []Action
	if err := cur.All(ctx, &acts); err != nil {
		return fmt.Errorf("action decode: %w", err)
	}
	idx := map[string]Action{}
	for _, a := range acts {
		idx[a.Name] = a
	}
	s.mu.Lock()
	s.byName = idx
	s.mu.Unlock()
	return nil
}

// Get returns the named action.
func (s *ActionStore) Get(name string) (Action, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	a, ok := s.byName[name]
	return a, ok
}

// Count is the number of loaded actions.
func (s *ActionStore) Count() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.byName)
}

// ActionEngine runs Actions — a declarative fetch/compute/write pipeline.
// Everything an action does is data (the Action document); this is the
// generic interpreter.
type ActionEngine struct {
	store    *ActionStore
	registry map[string]ListFunc
	clients  *client.Clients
}

// NewActionEngine binds the action store to the entity registry + clients.
func NewActionEngine(store *ActionStore, registry map[string]ListFunc, clients *client.Clients) *ActionEngine {
	return &ActionEngine{store: store, registry: registry, clients: clients}
}

// Run executes the named action. input is the caller-supplied argument map,
// referenced in steps as $input.<key>. Returns the action's Output map (or
// {ok:true} when no Output expr is set).
func (a *ActionEngine) Run(ctx context.Context, name string, input map[string]any) (map[string]any, error) {
	act, ok := a.store.Get(name)
	if !ok {
		return nil, fmt.Errorf("unknown action %q", name)
	}
	env := map[string]any{"input": input, "now": time.Now().UTC().Format(time.RFC3339)}

	for i, st := range act.Steps {
		switch st.Kind {
		case "fetch":
			lf, ok := a.registry[st.Entity]
			if !ok {
				return nil, fmt.Errorf("action %q step %d: unknown entity %q", name, i, st.Entity)
			}
			rows, err := lf(ctx, buildSearch(st.Where, env))
			if err != nil {
				return nil, fmt.Errorf("action %q step %d fetch: %w", name, i, err)
			}
			env[st.As] = rows
		case "compute":
			v, err := evalExpr(st.Expr, env)
			if err != nil {
				return nil, fmt.Errorf("action %q step %d compute: %w", name, i, err)
			}
			env[st.As] = v
		case "write":
			reqJSON, err := buildWriteJSON(st, env)
			if err != nil {
				return nil, fmt.Errorf("action %q step %d write: %w", name, i, err)
			}
			resp, err := mutate(ctx, a.clients, st.Op, reqJSON)
			if err != nil {
				return nil, fmt.Errorf("action %q step %d %s: %w", name, i, st.Op, err)
			}
			if st.As != "" {
				env[st.As] = resp
			}
		default:
			return nil, fmt.Errorf("action %q step %d: unknown kind %q", name, i, st.Kind)
		}
	}

	if act.Output != "" {
		out, err := evalExpr(act.Output, env)
		if err != nil {
			return nil, fmt.Errorf("action %q output: %w", name, err)
		}
		if m, ok := out.(map[string]any); ok {
			return m, nil
		}
		return map[string]any{"result": out}, nil
	}
	return map[string]any{"ok": true}, nil
}

// evalExpr runs an expr-lang expression returning any value. verifyPassword
// is exposed as a primitive so login-style actions can check a bcrypt hash
// without baking crypto into a document.
func evalExpr(code string, env map[string]any) (any, error) {
	program, err := expr.Compile(code, expr.Env(env), expr.AllowUndefinedVariables(),
		expr.Function("verifyPassword", func(args ...any) (any, error) {
			if len(args) != 2 {
				return false, fmt.Errorf("verifyPassword(hash, plain) needs 2 args")
			}
			hash, _ := args[0].(string)
			plain, _ := args[1].(string)
			return bcrypt.CompareHashAndPassword([]byte(hash), []byte(plain)) == nil, nil
		}),
		minutesSinceOpt())
	if err != nil {
		return nil, fmt.Errorf("compile %q: %w", code, err)
	}
	return expr.Run(program, env)
}

// buildWriteJSON assembles the protojson body of a write step: Where becomes
// the request's "filters", Set becomes the field values (refs resolved,
// types preserved).
func buildWriteJSON(st Step, env map[string]any) ([]byte, error) {
	obj := map[string]any{}
	if len(st.Where) > 0 {
		raws := make([]json.RawMessage, 0, len(st.Where))
		for _, c := range st.Where {
			b, err := protojson.Marshal(buildCriteria(c, env))
			if err != nil {
				return nil, err
			}
			raws = append(raws, b)
		}
		obj["filters"] = raws
	}
	for field, ref := range st.Set {
		obj[field] = resolveAny(ref, env)
	}
	return json.Marshal(obj)
}

// resolveAny is resolveRef but type-preserving — a computed number stays a
// number in the write payload instead of being stringified.
func resolveAny(raw string, env map[string]any) any {
	if len(raw) == 0 || raw[0] != '$' {
		return raw
	}
	parts := splitDots(raw[1:])
	if parts[0] == "now" {
		return env["now"]
	}
	var cur any = env[parts[0]]
	for _, seg := range parts[1:] {
		switch c := cur.(type) {
		case map[string]any:
			cur = c[seg]
		case []map[string]any:
			idx := atoiSafe(seg)
			if idx < 0 || idx >= len(c) {
				return nil
			}
			cur = c[idx]
		case []any:
			idx := atoiSafe(seg)
			if idx < 0 || idx >= len(c) {
				return nil
			}
			cur = c[idx]
		default:
			return nil
		}
	}
	return cur
}

// mutate dispatches a gRPC mutation by RPC name via reflection on the client
// wrappers — so the action engine can call any Create/Update/Delete without
// per-operation Go code. The reqJSON is protojson-unmarshalled into the
// correct request type.
func mutate(ctx context.Context, c *client.Clients, op string, reqJSON []byte) (map[string]any, error) {
	field, ok := opClientField[op]
	if !ok {
		return nil, fmt.Errorf("unknown mutation %q", op)
	}
	cv := reflect.ValueOf(c).Elem().FieldByName(field)
	if !cv.IsValid() || cv.IsNil() {
		return nil, fmt.Errorf("client %q not available", field)
	}
	m := cv.MethodByName(op)
	if !m.IsValid() {
		return nil, fmt.Errorf("%q has no method %q", field, op)
	}
	inT := m.Type().In(1) // *pb.<Op>Request
	reqMsg, ok := reflect.New(inT.Elem()).Interface().(proto.Message)
	if !ok {
		return nil, fmt.Errorf("%s: request type is not a proto.Message", op)
	}
	if err := protojson.Unmarshal(reqJSON, reqMsg); err != nil {
		return nil, fmt.Errorf("build %s request: %w", op, err)
	}
	rets := m.Call([]reflect.Value{reflect.ValueOf(ctx), reflect.ValueOf(reqMsg)})
	if e := rets[1]; !e.IsNil() {
		return nil, e.Interface().(error)
	}
	out := map[string]any{}
	if respMsg, ok := rets[0].Interface().(proto.Message); ok && respMsg != nil {
		if b, err := (protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: true}).Marshal(respMsg); err == nil {
			_ = json.Unmarshal(b, &out)
		}
	}
	return out, nil
}

func splitDots(s string) []string {
	out := []string{}
	cur := ""
	for _, r := range s {
		if r == '.' {
			out = append(out, cur)
			cur = ""
		} else {
			cur += string(r)
		}
	}
	return append(out, cur)
}

func atoiSafe(s string) int {
	n := 0
	for _, r := range s {
		if r < '0' || r > '9' {
			return -1
		}
		n = n*10 + int(r-'0')
	}
	if s == "" {
		return -1
	}
	return n
}
