// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/expr-lang/expr"

	commonpb "github.com/thaily/lms/proto/common"
)

// Engine evaluates business rules. It holds no rules itself — every rule is
// read from the RuleStore (MongoDB) at request time.
type Engine struct {
	rules    *RuleStore
	registry map[string]ListFunc
}

// NewEngine binds the rule store to the entity registry.
func NewEngine(rules *RuleStore, registry map[string]ListFunc) *Engine {
	return &Engine{rules: rules, registry: registry}
}

// RuleError is returned when a rule's condition evaluates false — i.e. the
// mutation is business-invalid (vs. an infrastructure error).
type RuleError struct {
	Rule    string
	Message string
}

func (e *RuleError) Error() string { return e.Message }

// Check runs every enabled rule for operation against the request map.
// reqFilters is the triggering Update/Delete request's own Filters (nil for
// Create) — fetch steps with UseRequestFilters load exactly those rows.
// Returns nil when all pass (or no rules exist), a *RuleError on the first
// rule whose condition is false, or a plain error on infrastructure failure.
func (e *Engine) Check(ctx context.Context, operation string, reqMap map[string]any, reqFilters []*commonpb.FilterCriteria) error {
	return e.evalRules(ctx, e.rules.ForOperation(operation), reqMap, reqFilters)
}

// evalRules is the rule loop, split out so tests can drive it with a
// hand-built rule slice instead of a live Mongo-backed RuleStore.
func (e *Engine) evalRules(ctx context.Context, rules []Rule, reqMap map[string]any, reqFilters []*commonpb.FilterCriteria) error {
	if len(rules) == 0 {
		return nil
	}
	now := time.Now().UTC().Format(time.RFC3339)

	for _, r := range rules {
		// Each rule gets a fresh env: the request, the clock, and whatever
		// its own fetch steps produce.
		env := map[string]any{"req": reqMap, "now": now}

		for _, fs := range r.Fetch {
			lf, ok := e.registry[fs.Entity]
			if !ok {
				return fmt.Errorf("rule %q: unknown entity %q", r.Rule, fs.Entity)
			}
			search := buildSearch(fs.Where, env)
			if fs.UseRequestFilters {
				// Load the exact row(s) the Update/Delete targets — prepend
				// the request's own filters to this fetch.
				search.Filters = append(append([]*commonpb.FilterCriteria{}, reqFilters...), search.Filters...)
			}
			rows, err := lf(ctx, search)
			if err != nil {
				return fmt.Errorf("rule %q fetch %q: %w", r.Rule, fs.As, err)
			}
			env[fs.As] = rows
		}

		ok, err := evalCondition(r.Condition, env)
		if err != nil {
			return fmt.Errorf("rule %q condition: %w", r.Rule, err)
		}
		if !ok {
			msg := r.Message
			if msg == "" {
				msg = "business rule " + r.Rule + " denied the request"
			}
			return &RuleError{Rule: r.Rule, Message: msg}
		}
	}
	return nil
}

// minutesSinceOpt exposes minutesSince(rfc3339) to rule/action expressions —
// minutes elapsed since an RFC3339 timestamp. Lets a rule enforce a duration
// or deadline (e.g. an exam attempt's time limit) without baking time math
// into Go.
func minutesSinceOpt() expr.Option {
	return expr.Function("minutesSince", func(args ...any) (any, error) {
		if len(args) != 1 {
			return 0.0, fmt.Errorf("minutesSince(rfc3339) needs 1 arg")
		}
		s, _ := args[0].(string)
		t, err := time.Parse(time.RFC3339, s)
		if err != nil {
			return 0.0, nil
		}
		return time.Since(t).Minutes(), nil
	})
}

// evalCondition compiles + runs an expr-lang boolean expression. Empty or
// "true" always passes; "false" always fails.
func evalCondition(condition string, env map[string]any) (bool, error) {
	condition = strings.TrimSpace(condition)
	switch condition {
	case "", "true":
		return true, nil
	case "false":
		return false, nil
	}
	program, err := expr.Compile(condition, expr.AsBool(), expr.Env(env),
		expr.AllowUndefinedVariables(), minutesSinceOpt())
	if err != nil {
		return false, fmt.Errorf("compile %q: %w", condition, err)
	}
	out, err := expr.Run(program, env)
	if err != nil {
		return false, fmt.Errorf("run %q: %w", condition, err)
	}
	b, _ := out.(bool)
	return b, nil
}

// buildSearch turns a rule's declarative WHERE tree into a
// common.SearchRequest. Top-level entries are AND-ed (SearchRequest.Filters
// semantics); each entry recurses through buildCriteria so nested AND/OR
// groups round-trip into common.FilterGroup.
func buildSearch(where []Criteria, env map[string]any) *commonpb.SearchRequest {
	crits := make([]*commonpb.FilterCriteria, 0, len(where))
	for _, c := range where {
		crits = append(crits, buildCriteria(c, env))
	}
	return &commonpb.SearchRequest{Filters: crits}
}

// buildCriteria compiles one Criteria node — leaf condition or logical
// group — into a proto FilterCriteria, recursing into nested groups.
func buildCriteria(c Criteria, env map[string]any) *commonpb.FilterCriteria {
	if c.Logic != "" {
		sub := make([]*commonpb.FilterCriteria, 0, len(c.Group))
		for _, g := range c.Group {
			sub = append(sub, buildCriteria(g, env))
		}
		return &commonpb.FilterCriteria{
			Criteria: &commonpb.FilterCriteria_Group{
				Group: &commonpb.FilterGroup{
					Logic:   logicalFromString(c.Logic),
					Filters: sub,
				},
			},
		}
	}
	return &commonpb.FilterCriteria{
		Criteria: &commonpb.FilterCriteria_Condition{
			Condition: &commonpb.FilterCondition{
				Field:    c.Field,
				Operator: operatorFromString(c.Op),
				Values:   resolveValues(c.Value, env),
			},
		},
	}
}

// logicalFromString maps a group's logic string to the proto enum,
// defaulting to AND.
func logicalFromString(logic string) commonpb.LogicalCondition {
	if v, ok := commonpb.LogicalCondition_value[strings.ToUpper(strings.TrimSpace(logic))]; ok {
		return commonpb.LogicalCondition(v)
	}
	return commonpb.LogicalCondition_AND
}

// resolveValues turns a filter Value into the []string the proto expects.
// For IN / NOT_IN a comma-separated literal becomes multiple values.
func resolveValues(raw string, env map[string]any) []string {
	v := resolveRef(raw, env)
	if strings.Contains(v, ",") {
		parts := strings.Split(v, ",")
		for i := range parts {
			parts[i] = strings.TrimSpace(parts[i])
		}
		return parts
	}
	return []string{v}
}

// resolveRef resolves a filter value. A leading $ marks a reference:
//   $now                      current RFC3339 time
//   $req.<field>              request field
//   $<fetchAs>.<idx>.<field>  earlier fetch row field
// Anything else is a literal. An unresolvable reference yields "" — the
// resulting query simply matches nothing, which rules can test with len().
func resolveRef(raw string, env map[string]any) string {
	if !strings.HasPrefix(raw, "$") {
		return raw
	}
	path := strings.Split(strings.TrimPrefix(raw, "$"), ".")
	if path[0] == "now" {
		if s, ok := env["now"].(string); ok {
			return s
		}
		return ""
	}
	cur := env[path[0]]
	for _, seg := range path[1:] {
		switch c := cur.(type) {
		case map[string]any:
			cur = c[seg]
		case []map[string]any:
			i, err := strconv.Atoi(seg)
			if err != nil || i < 0 || i >= len(c) {
				return ""
			}
			cur = c[i]
		case []any:
			i, err := strconv.Atoi(seg)
			if err != nil || i < 0 || i >= len(c) {
				return ""
			}
			cur = c[i]
		default:
			return ""
		}
	}
	if cur == nil {
		return ""
	}
	return fmt.Sprint(cur)
}

// operatorFromString maps a rule's op string to the proto enum, defaulting
// to EQUAL for anything unrecognised.
func operatorFromString(op string) commonpb.FilterOperator {
	if v, ok := commonpb.FilterOperator_value[strings.ToUpper(strings.TrimSpace(op))]; ok {
		return commonpb.FilterOperator(v)
	}
	return commonpb.FilterOperator_EQUAL
}
