// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"encoding/json"
	"log"
	"reflect"
	"strings"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	commonpb "github.com/thaily/lms/proto/common"
)

// UnaryInterceptor returns a gRPC client interceptor that runs business rules
// before every Create/Update/Delete call the gateway makes.
//
// getEngine is an indirection: the engine needs the gRPC clients, the clients
// are dialed with this interceptor — so main.go builds the interceptor first
// and the closure returns the engine once it exists.
//
// Failure policy: a rule whose condition is false -> FailedPrecondition (the
// mutation is business-invalid). An engine/infra error (Mongo down, bad rule)
// -> fail OPEN with a loud log, so a broken rule store can't wedge every
// write. That is the opposite of the authz enforcer, which fails closed:
// authz protects data exposure, business rules protect data integrity, and a
// dead rule engine blocking all writes is worse than the alternative here.
func UnaryInterceptor(getEngine func() *Engine) grpc.UnaryClientInterceptor {
	return func(
		ctx context.Context, method string, req, reply any,
		cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption,
	) error {
		op := method[strings.LastIndex(method, "/")+1:]
		if !isMutation(op) {
			return invoker(ctx, method, req, reply, cc, opts...)
		}
		eng := getEngine()
		if eng == nil {
			return invoker(ctx, method, req, reply, cc, opts...)
		}
		switch err := eng.Check(ctx, op, messageToMap(req), extractFilters(req)).(type) {
		case nil:
			return invoker(ctx, method, req, reply, cc, opts...)
		case *RuleError:
			return status.Error(codes.FailedPrecondition, err.Message)
		default:
			log.Printf("business-rule engine error on %s: %v (allowing call)", op, err)
			return invoker(ctx, method, req, reply, cc, opts...)
		}
	}
}

// extractFilters pulls the Filters field off an Update/Delete request via
// reflection — those requests are filter-based, so their Filters identify
// the exact rows the mutation targets. Create requests have no Filters and
// yield nil.
func extractFilters(req any) []*commonpb.FilterCriteria {
	rv := reflect.ValueOf(req)
	for rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return nil
		}
		rv = rv.Elem()
	}
	if rv.Kind() != reflect.Struct {
		return nil
	}
	f := rv.FieldByName("Filters")
	if !f.IsValid() {
		return nil
	}
	if fc, ok := f.Interface().([]*commonpb.FilterCriteria); ok {
		return fc
	}
	return nil
}

// isMutation reports whether the gRPC method is a write the rules guard.
func isMutation(op string) bool {
	return strings.HasPrefix(op, "Create") ||
		strings.HasPrefix(op, "Update") ||
		strings.HasPrefix(op, "Delete")
}

// messageToMap renders a proto request as a map keyed by proto field names,
// so rule filter references ($req.exam_id) resolve.
func messageToMap(req any) map[string]any {
	m, ok := req.(proto.Message)
	if !ok {
		return map[string]any{}
	}
	b, err := protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: true}.Marshal(m)
	if err != nil {
		return map[string]any{}
	}
	var out map[string]any
	if json.Unmarshal(b, &out) != nil {
		return map[string]any{}
	}
	return out
}
