// Code generated by grpc-gen. DO NOT EDIT.

package domain

import (
	"context"
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	auditpb "github.com/thaily/lms/proto/audit"
	classpb "github.com/thaily/lms/proto/class"
	exampb "github.com/thaily/lms/proto/exam"
	lessonpb "github.com/thaily/lms/proto/lesson"
	materialpb "github.com/thaily/lms/proto/material"
	notificationpb "github.com/thaily/lms/proto/notification"
	submissionpb "github.com/thaily/lms/proto/submission"
	userpb "github.com/thaily/lms/proto/user"
	commonpb "github.com/thaily/lms/proto/common"
	"github.com/thaily/lms/src/server/graph/client"
)

// ListFunc runs a filtered List for one entity and returns each row as a
// plain map[string]any so rule conditions / fetch references can read
// fields generically without per-entity Go code.
type ListFunc func(ctx context.Context, search *commonpb.SearchRequest) ([]map[string]any, error)

// NewRegistry wires one ListFunc per entity over the gRPC clients.
// Calls go through .Stub() — the RAW gRPC client — deliberately
// bypassing the response cache: a business rule must decide on the
// current truth, never a stale cached list.
func NewRegistry(c *client.Clients) map[string]ListFunc {
	return map[string]ListFunc{
		"AttemptAnswer": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Submission.Stub().ListAttemptAnswer(ctx, &submissionpb.ListAttemptAnswerRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetAttemptAnswer())
		},
		"AuditLog": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Audit.Stub().ListAuditLog(ctx, &auditpb.ListAuditLogRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetAuditLog())
		},
		"Class": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Class.Stub().ListClass(ctx, &classpb.ListClassRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetClass())
		},
		"ClassInviteKey": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Class.Stub().ListClassInviteKey(ctx, &classpb.ListClassInviteKeyRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetClassInviteKey())
		},
		"CommunityReport": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Notification.Stub().ListCommunityReport(ctx, &notificationpb.ListCommunityReportRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetCommunityReport())
		},
		"Enrollment": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Class.Stub().ListEnrollment(ctx, &classpb.ListEnrollmentRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetEnrollment())
		},
		"Exam": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Exam.Stub().ListExam(ctx, &exampb.ListExamRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetExam())
		},
		"ExamAssignment": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Exam.Stub().ListExamAssignment(ctx, &exampb.ListExamAssignmentRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetExamAssignment())
		},
		"ExamAttempt": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Submission.Stub().ListExamAttempt(ctx, &submissionpb.ListExamAttemptRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetExamAttempt())
		},
		"Lesson": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Lesson.Stub().ListLesson(ctx, &lessonpb.ListLessonRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetLesson())
		},
		"LessonAttendance": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Lesson.Stub().ListLessonAttendance(ctx, &lessonpb.ListLessonAttendanceRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetLessonAttendance())
		},
		"LessonVideo": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Lesson.Stub().ListLessonVideo(ctx, &lessonpb.ListLessonVideoRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetLessonVideo())
		},
		"Material": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Material.Stub().ListMaterial(ctx, &materialpb.ListMaterialRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetMaterial())
		},
		"MaterialClass": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Material.Stub().ListMaterialClass(ctx, &materialpb.ListMaterialClassRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetMaterialClass())
		},
		"MaterialTag": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Material.Stub().ListMaterialTag(ctx, &materialpb.ListMaterialTagRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetMaterialTag())
		},
		"Notification": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Notification.Stub().ListNotification(ctx, &notificationpb.ListNotificationRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetNotification())
		},
		"PasswordReset": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.User.Stub().ListPasswordReset(ctx, &userpb.ListPasswordResetRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetPasswordReset())
		},
		"Question": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Exam.Stub().ListQuestion(ctx, &exampb.ListQuestionRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetQuestion())
		},
		"QuestionAnswer": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Exam.Stub().ListQuestionAnswer(ctx, &exampb.ListQuestionAnswerRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetQuestionAnswer())
		},
		"QuestionChoice": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.Exam.Stub().ListQuestionChoice(ctx, &exampb.ListQuestionChoiceRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetQuestionChoice())
		},
		"RefreshToken": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.User.Stub().ListRefreshToken(ctx, &userpb.ListRefreshTokenRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetRefreshToken())
		},
		"StudentProfile": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.User.Stub().ListStudentProfile(ctx, &userpb.ListStudentProfileRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetStudentProfile())
		},
		"TeacherProfile": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.User.Stub().ListTeacherProfile(ctx, &userpb.ListTeacherProfileRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetTeacherProfile())
		},
		"User": func(ctx context.Context, s *commonpb.SearchRequest) ([]map[string]any, error) {
			r, err := c.User.Stub().ListUser(ctx, &userpb.ListUserRequest{Search: s})
			if err != nil {
				return nil, err
			}
			return toMaps(r.GetUser())
		},
	}
}

// toMaps converts a slice of proto messages to plain maps via protojson,
// so rule conditions can address any field by its proto (snake_case) name.
func toMaps[T proto.Message](items []T) ([]map[string]any, error) {
	mo := protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: true}
	out := make([]map[string]any, 0, len(items))
	for _, it := range items {
		b, err := mo.Marshal(it)
		if err != nil {
			return nil, err
		}
		var m map[string]any
		if err := json.Unmarshal(b, &m); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, nil
}

// opClientField maps a Create/Update/Delete RPC name to the client
// wrapper field on *client.Clients that exposes it.
var opClientField = map[string]string{
	"CreateAttemptAnswer": "Submission",
	"CreateAuditLog": "Audit",
	"CreateClass": "Class",
	"CreateClassInviteKey": "Class",
	"CreateCommunityReport": "Notification",
	"CreateEnrollment": "Class",
	"CreateExam": "Exam",
	"CreateExamAssignment": "Exam",
	"CreateExamAttempt": "Submission",
	"CreateLesson": "Lesson",
	"CreateLessonAttendance": "Lesson",
	"CreateLessonVideo": "Lesson",
	"CreateMaterial": "Material",
	"CreateMaterialClass": "Material",
	"CreateMaterialTag": "Material",
	"CreateNotification": "Notification",
	"CreatePasswordReset": "User",
	"CreateQuestion": "Exam",
	"CreateQuestionAnswer": "Exam",
	"CreateQuestionChoice": "Exam",
	"CreateRefreshToken": "User",
	"CreateStudentProfile": "User",
	"CreateTeacherProfile": "User",
	"CreateUser": "User",
	"DeleteAttemptAnswer": "Submission",
	"DeleteAuditLog": "Audit",
	"DeleteClass": "Class",
	"DeleteClassInviteKey": "Class",
	"DeleteCommunityReport": "Notification",
	"DeleteEnrollment": "Class",
	"DeleteExam": "Exam",
	"DeleteExamAssignment": "Exam",
	"DeleteExamAttempt": "Submission",
	"DeleteLesson": "Lesson",
	"DeleteLessonAttendance": "Lesson",
	"DeleteLessonVideo": "Lesson",
	"DeleteMaterial": "Material",
	"DeleteMaterialClass": "Material",
	"DeleteMaterialTag": "Material",
	"DeleteNotification": "Notification",
	"DeletePasswordReset": "User",
	"DeleteQuestion": "Exam",
	"DeleteQuestionAnswer": "Exam",
	"DeleteQuestionChoice": "Exam",
	"DeleteRefreshToken": "User",
	"DeleteStudentProfile": "User",
	"DeleteTeacherProfile": "User",
	"DeleteUser": "User",
	"UpdateAttemptAnswer": "Submission",
	"UpdateAuditLog": "Audit",
	"UpdateClass": "Class",
	"UpdateClassInviteKey": "Class",
	"UpdateCommunityReport": "Notification",
	"UpdateEnrollment": "Class",
	"UpdateExam": "Exam",
	"UpdateExamAssignment": "Exam",
	"UpdateExamAttempt": "Submission",
	"UpdateLesson": "Lesson",
	"UpdateLessonAttendance": "Lesson",
	"UpdateLessonVideo": "Lesson",
	"UpdateMaterial": "Material",
	"UpdateMaterialClass": "Material",
	"UpdateMaterialTag": "Material",
	"UpdateNotification": "Notification",
	"UpdatePasswordReset": "User",
	"UpdateQuestion": "Exam",
	"UpdateQuestionAnswer": "Exam",
	"UpdateQuestionChoice": "Exam",
	"UpdateRefreshToken": "User",
	"UpdateStudentProfile": "User",
	"UpdateTeacherProfile": "User",
	"UpdateUser": "User",
}
