// Code generated by grpc-gen. DO NOT EDIT.

// Package domain is the dynamic business-rule engine. Rules live entirely in
// MongoDB — adding / editing / disabling a rule is a data change, no
// redeploy. The only Go code is rule-agnostic machinery: the Mongo loader
// (this file), the entity registry, the engine, and the gRPC interceptor.
package domain

import (
	"context"
	"fmt"
	"sort"
	"sync"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// Criteria is one node of a rule's WHERE tree. It is EITHER a leaf condition
// (Field/Op/Value set) OR a logical group: when Logic is non-empty
// ("AND" | "OR") the node groups the nested Group criteria instead — so a
// rule can express arbitrarily nested AND/OR, exactly like the gRPC
// common.FilterCriteria it compiles down to.
//
// Value (on a leaf) is a literal or a reference resolved at eval time:
//   $req.<field>             a field of the mutation request
//   $now                     current time (RFC3339 UTC)
//   $<fetchAs>.<idx>.<field>  a field of an earlier fetch result row
type Criteria struct {
	Field string // leaf: field name
	Op    string // leaf: EQUAL | NOT_EQUAL | IN | GREATER_THAN | ...
	Value string // leaf: literal or $-reference

	Logic string     // group: "AND" | "OR" — non-empty marks this a group
	Group []Criteria // group: nested criteria
}

// FetchStep declares one data load: List<Entity> filtered by Where, exposed
// to the condition expression (and to later fetches) under the name As.
// Top-level Where entries are AND-ed (gRPC SearchRequest.Filters semantics);
// use a Logic group entry for OR / nesting.
type FetchStep struct {
	As     string
	Entity string
	Where  []Criteria

	// UseRequestFilters prepends the triggering Update/Delete request's own
	// Filters to this fetch — so a rule can load the exact row(s) the
	// mutation targets, which is what state-transition and delete-dependency
	// checks need ($current.0.status, $current.0.id, ...). No effect on
	// Create requests (they carry no Filters).
	UseRequestFilters bool `bson:"use_request_filters"`
}

// Rule is one business-rule document. Condition is an expr-lang expression
// over {req, now, <each fetch As>}; when it evaluates false the guarded
// mutation is rejected with Message.
type Rule struct {
	Operation string // gRPC method, e.g. "CreateExamAttempt"
	Rule      string // human name
	Enabled   bool
	Priority  int
	Fetch     []FetchStep
	Condition string
	Message   string
}

// RuleStore loads rules from MongoDB and indexes them by operation.
type RuleStore struct {
	coll *mongo.Collection
	mu   sync.RWMutex
	byOp map[string][]Rule
}

// NewRuleStore connects to Mongo and does the initial load.
func NewRuleStore(ctx context.Context, mongoURI, db, collection string) (*RuleStore, error) {
	client, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		return nil, fmt.Errorf("mongo connect: %w", err)
	}
	pctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := client.Ping(pctx, nil); err != nil {
		return nil, fmt.Errorf("mongo ping: %w", err)
	}
	s := &RuleStore{
		coll: client.Database(db).Collection(collection),
		byOp: map[string][]Rule{},
	}
	if err := s.Reload(ctx); err != nil {
		return nil, err
	}
	return s, nil
}

// Reload re-reads every rule from Mongo. Safe to call from a ticker or a
// dashboard webhook so edits take effect without a gateway restart.
func (s *RuleStore) Reload(ctx context.Context) error {
	cur, err := s.coll.Find(ctx, bson.M{})
	if err != nil {
		return fmt.Errorf("rule find: %w", err)
	}
	var rules []Rule
	if err := cur.All(ctx, &rules); err != nil {
		return fmt.Errorf("rule decode: %w", err)
	}
	idx := map[string][]Rule{}
	for _, r := range rules {
		idx[r.Operation] = append(idx[r.Operation], r)
	}
	for op := range idx {
		ops := idx[op]
		sort.SliceStable(ops, func(i, j int) bool { return ops[i].Priority < ops[j].Priority })
	}
	s.mu.Lock()
	s.byOp = idx
	s.mu.Unlock()
	return nil
}

// ForOperation returns the enabled rules guarding the given gRPC operation,
// in priority order.
func (s *RuleStore) ForOperation(op string) []Rule {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return enabledRules(s.byOp[op])
}

// OperationCount reports how many distinct operations currently have at
// least one enabled rule — handy for a startup log line.
func (s *RuleStore) OperationCount() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	n := 0
	for op := range s.byOp {
		if len(enabledRules(s.byOp[op])) > 0 {
			n++
		}
	}
	return n
}

func enabledRules(in []Rule) []Rule {
	out := make([]Rule, 0, len(in))
	for _, r := range in {
		if r.Enabled {
			out = append(out, r)
		}
	}
	return out
}
