version: '3.8'

services:
  lesson:
    build:
      context: ../../..
      dockerfile: src/service/lesson/Dockerfile
    image: github.com/thaily/lms/lesson:latest
    container_name: lesson_service
    env_file:
      - lesson.env
    ports:
      - "50053:50053"
    volumes:
      - .:/app/service:ro
      - ../../../logs:/app/logs
    networks:
      - lesson_network
    restart: unless-stopped

networks:
  lesson_network:
    driver: bridge
