// Hand-written (NOT generated by grpc-gen) — implements the Enforcer
// interface from enforcer.go using Casbin + a MongoDB policy store, the same
// lms_policy.casbin_rule collection the policy-engine dashboard manages.
//
// add-gateway only (re)writes enforcer.go in this package; this file is left
// alone on regeneration.
package policy

import (
	"context"
	_ "embed"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"
	mongodbadapter "github.com/casbin/mongodb-adapter/v4"
	"github.com/expr-lang/expr"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"

	"github.com/thaily/lms/src/server/graph/auth"
)

//go:embed model.conf
var modelConf string

// CasbinEnforcer implements Enforcer. Policies live in MongoDB; the embedded
// model.conf defines an RBAC + ABAC matcher where the policy `condition`
// column is an expr-lang expression evaluated against the request context.
type CasbinEnforcer struct {
	e  *casbin.Enforcer
	mu sync.RWMutex
}

var _ Enforcer = (*CasbinEnforcer)(nil)

// NewCasbin connects to Mongo, builds the enforcer from the embedded model +
// the policy collection, and registers the evalCondition helper.
func NewCasbin(ctx context.Context, mongoURI, db, collection string) (*CasbinEnforcer, error) {
	client, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		return nil, fmt.Errorf("mongo connect: %w", err)
	}
	pctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := client.Ping(pctx, nil); err != nil {
		return nil, fmt.Errorf("mongo ping: %w", err)
	}

	adapter, err := mongodbadapter.NewAdapterByDB(client, &mongodbadapter.AdapterConfig{
		DatabaseName:   db,
		CollectionName: collection,
	})
	if err != nil {
		return nil, fmt.Errorf("mongo adapter: %w", err)
	}

	m, err := model.NewModelFromString(modelConf)
	if err != nil {
		return nil, fmt.Errorf("parse model: %w", err)
	}

	e, err := casbin.NewEnforcer(m, adapter)
	if err != nil {
		return nil, fmt.Errorf("new enforcer: %w", err)
	}

	ce := &CasbinEnforcer{e: e}
	ce.registerEvalCondition()
	return ce, nil
}

// HasRole satisfies @auth. A viewer carries the role if its JWT role matches
// directly, or Casbin role inheritance (g rules) grants it.
func (c *CasbinEnforcer) HasRole(_ context.Context, v *auth.Viewer, role string) bool {
	if v == nil {
		return false
	}
	if role == "*" || v.Role == role {
		// "*" = any authenticated viewer.
		return true
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	if ok, _ := c.e.HasRoleForUser(v.UserID, role); ok {
		return true
	}
	if ok, _ := c.e.HasRoleForUser(v.Role, role); ok {
		return true
	}
	return false
}

// EvalRule satisfies @policy. rule is the Casbin object name (e.g.
// "User.email"); the viewer + parent object are flattened into the request
// ctx map so a stored policy condition can reference ctx.viewer_id,
// ctx.role, ctx.target_id (+ any auth.Viewer.Extra attributes).
func (c *CasbinEnforcer) EvalRule(_ context.Context, rule string, v *auth.Viewer, obj any) (bool, error) {
	reqCtx := map[string]any{
		"viewer_id": "",
		"role":      "",
		"target_id": extractID(obj),
	}
	sub := ""
	if v != nil {
		sub = v.Role
		reqCtx["viewer_id"] = v.UserID
		reqCtx["role"] = v.Role
		for k, val := range v.Extra {
			reqCtx[k] = val
		}
	}
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.e.Enforce(sub, rule, "read", reqCtx)
}

// Reload re-reads policies from Mongo so dashboard edits take effect without
// a gateway restart. Wire it to a ticker or a webhook in main.go.
func (c *CasbinEnforcer) Reload() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.e.LoadPolicy()
}

// registerEvalCondition adds the evalCondition(ctx, expr) function the matcher
// calls. Empty / "true" condition always allows; otherwise the expression is
// compiled with expr-lang and run against {ctx: <request ctx map>}.
func (c *CasbinEnforcer) registerEvalCondition() {
	c.e.AddFunction("evalCondition", func(args ...any) (any, error) {
		if len(args) < 2 {
			return false, fmt.Errorf("evalCondition expects (ctx, expression)")
		}
		reqCtx, _ := args[0].(map[string]any)
		expression, _ := args[1].(string)

		expression = strings.TrimSpace(expression)
		switch expression {
		case "", "true":
			return true, nil
		case "false":
			return false, nil
		}
		if reqCtx == nil {
			reqCtx = map[string]any{}
		}
		env := map[string]any{"ctx": reqCtx}
		program, err := expr.Compile(expression, expr.AsBool(), expr.Env(env))
		if err != nil {
			return false, fmt.Errorf("compile policy condition %q: %w", expression, err)
		}
		out, err := expr.Run(program, env)
		if err != nil {
			return false, fmt.Errorf("run policy condition %q: %w", expression, err)
		}
		b, _ := out.(bool)
		return b, nil
	})
}

// extractID best-effort pulls a string id from the parent GraphQL object.
// gqlgen model structs expose `ID string` (or `*string` when the field is
// nullable), so reflection on the "ID" field covers every entity.
func extractID(obj any) string {
	if obj == nil {
		return ""
	}
	rv := reflect.ValueOf(obj)
	for rv.Kind() == reflect.Pointer {
		if rv.IsNil() {
			return ""
		}
		rv = rv.Elem()
	}
	if rv.Kind() != reflect.Struct {
		return ""
	}
	f := rv.FieldByName("ID")
	if !f.IsValid() {
		return ""
	}
	switch f.Kind() {
	case reflect.String:
		return f.String()
	case reflect.Pointer:
		if !f.IsNil() && f.Elem().Kind() == reflect.String {
			return f.Elem().String()
		}
	}
	return ""
}
