// Code generated by grpc-gen. DO NOT EDIT.
// Enforcer is the abstraction the @auth/@policy directives call into.
// main.go is expected to wire a real impl (e.g. Casbin reading from the
// policy-engine MongoDB collection). DenyAll is the safe default.

package policy

import (
	"context"
	"errors"

	"github.com/thaily/lms/src/server/graph/auth"
)

// ErrUnauthenticated and ErrForbidden are the two failure modes resolvers
// surface to clients. Wrap them with %w if you need more detail.
var (
	ErrUnauthenticated = errors.New("unauthenticated")
	ErrForbidden       = errors.New("forbidden")
)

// Enforcer is the seam between directives and the actual policy backend.
// Implementations live in main.go (or a separate package the user owns).
type Enforcer interface {
	// HasRole returns true if viewer carries the given role string. nil
	// viewer means anonymous and should return false for every role.
	HasRole(ctx context.Context, v *auth.Viewer, role string) bool

	// EvalRule runs a named expression against the binding map. obj is the
	// parent GraphQL object (may be nil for top-level fields); extras
	// surface request-scoped ABAC attributes.
	EvalRule(ctx context.Context, rule string, v *auth.Viewer, obj any) (bool, error)
}

// DenyAll rejects everything; useful as the zero value before main.go wires
// a real enforcer, so the directive runners fail closed.
type DenyAll struct{}

func (DenyAll) HasRole(context.Context, *auth.Viewer, string) bool { return false }
func (DenyAll) EvalRule(context.Context, string, *auth.Viewer, any) (bool, error) {
	return false, nil
}
